# Generic constants required for the application to function
from datetime import datetime
from collections import OrderedDict

from my_logger import get_console_logger

SqftInAcre = 43560  # Square foot in one Acre
METERS_IN_MILE = 1609
FEET_IN_MILE = 5280

DISTANCE_UNITS = {
    'nassau': METERS_IN_MILE,
    'suffolk': FEET_IN_MILE
}

WHITELISTED_PROPERTY_CLASS_CODES = {
    # nassau check for property_class and property_class_type
    # ''' sql filters for nassau
    # AND ((p.property_class = 2100 AND p.property_class_type = 1)
    # OR (p.property_class = 2102 AND p.property_class_type = 1)
    # OR (p.property_class = 2150 AND p.property_class_type = 1)
    # OR (p.property_class = 2200 AND p.property_class_type = 1)
    # OR (p.property_class = 2300 AND p.property_class_type = 1)
    # OR (p.property_class = 2400 AND p.property_class_type = 1)
    # OR (p.property_class = 2500 AND p.property_class_type = 1)
    # OR (p.property_class = 2600 AND p.property_class_type = 1)
    # OR (p.property_class = 2800 AND p.property_class_type = 1)
    # OR (p.property_class = 4122 AND p.property_class_type = 1)
    # OR (p.property_class = 4830 AND p.property_class_type = 1))
    # '''
    'nassau': [(2100, 1), (2102, 1), (2150, 1), (2200, 1), (2300, 1),
               (2400, 1), (2500, 1), (2600, 1), (2800, 1), (4122, 1),
               (4830, 1)],
    'suffolk': [],
    # broward format (property_class, property_class_type)
    'broward': [(1, 1), (1, 2), (1, 4), (1, 5), (1, 6), (8, 1), (8, 2), (8, 3), (8, 4),
                # vacant
                (0, 1), (0, 3), (0, 4), (0, None)],
    'palmbeach': [0, 10, 30, 40, 50, 100, 101, 104, 105, 110, 130, 140, 150, 300, 304,
                  400, 410, 700, 800, 1200, 1204, 2014],
    # miamidade simply check for property_class
    'miamidade': [1, 4, 5, 7, 10, 17, 23, 40, 65, 66, 80, 81, 89,
                  101, 102, 104, 105, 405, 407, 410, 802, 803]
}

BASEMENT_TYPE_MAP = {
    'suffolk': OrderedDict([
        (0, 'none'),
        (1, 'slab'),
        (2, 'crawl'),
        (3, 'half'),
        (4, 'full'),
        (5, 'pier'),
        (6, 'partial'),
        (7, 'part')]),
    'nassau': OrderedDict([
        (0, 'none'),
        (1, '1/4 bsmt/slab'),
        (2, '1/2 bsmt/crawl'),
        (3, '3/4 bsmt'),
        (4, 'full')
    ]),
    'broward': OrderedDict(),
    'miamidade': OrderedDict(),
    'palmbeach': OrderedDict()
}

PATIO_TYPE_MAP = {
    'suffolk': OrderedDict(),
    'nassau': OrderedDict(),
    'broward': OrderedDict(),
    'miamidade': OrderedDict([
        # the index of mapping is a value, stored into database
        (0, 'NONE'),
        (1, 'Patio - Concrete Slab'),
        (2, 'Patio - Brick, Tile, Flagstone'),
        (3, 'Patio - Terrazzo, Pebble'),
        (4, 'Patio - Concrete Slab w/Roof Aluminum or Fiber'),
        (5, 'Patio - Screened over Concrete Slab'),
        (6, 'Patio - Wood Deck'),
        (7, 'Patio - Marble'),
        (8, 'Patio - Concrete stamped or stained'),
        (9, 'Patio - Exotic hardwood, Ipe, Tigerwood, Mahagony'),
        (10, 'ATTACHED COVERED PATIO'),
        (11, 'ALUM COVERED PATIO'),
        (12, 'PATIO ENCLOSURE'),
    ]),
    'palmbeach': OrderedDict([
        (0, 'NONE'),
        (1, 'Patio'),
    ])
}

PAVING_TYPE_MAP = {
    'suffolk': OrderedDict(),
    'nassau': OrderedDict(),
    'broward': OrderedDict(),
    'palmbeach': OrderedDict(),
    'miamidade': OrderedDict([
        (0, 'NONE'),
        (1, 'Paving - Asphalt'),
        (2, 'Paving - Concrete'),
    ]),
}

HEAT_TYPE_MAP = {
    'suffolk': OrderedDict(),
    'nassau': OrderedDict(),
    'broward': OrderedDict(),
    'miamidade': OrderedDict(),
    'palmbeach': OrderedDict([
        (1, 'NONE'),
        (2, 'CONVECTION'),
        (3, 'FORCED / NO DUCT'),
        (4, 'FORCED AIR DUCT'),
        (5, 'HOT WATER'),
        (6, 'STEAM'),
        (7, 'RADIANT ELEC'),
        (8, 'RADIANT WATER'),
        (9, 'CHILLED WATER')
    ]),
}

PORCH_TYPE_MAP = {
    'suffolk': OrderedDict(),
    'nassau': OrderedDict(),
    'broward': OrderedDict(),
    'miamidade': OrderedDict(),
    'palmbeach': OrderedDict([
        (0, 'NONE'),
        (1, 'FINISHED ENCL. PORCH'),
        (2, 'FINISHED OPEN PORCH'),
        (3, 'FIN SCREEN PORCH'),
        (4, 'UNFIN ENCLOSED PORCH'),
        (5, 'UNFIN OPEN PORCH')
    ]),
}

LOCATION_STYLE_MAP = {
    'nassau': OrderedDict([
        ('0', 'NO LOCATION'),
        ('1', 'CENTRAL BUSINESS DISTRICT'),
        ('2', 'PERIM CENTRAL BUSINESS DISTRICT'),
        ('3', 'BUSINESS CLUSTER'),
        ('4', 'MAJOR STRIP'),
        ('5', 'SECONDARY STRIP'),
        ('6', 'NEIGHBORHOOD OR SPOT'),
        ('7', 'COMMERCIAL/INDUSTRIAL PARK'),
        ('8', 'APARTMENT/CONDO COMPLEX'),
        ('20', 'NO LOCATION INFLUENCE'),
        ('21', 'MAJOR HIGHWAY'),
        ('22', 'SECONDARY STREET'),
        ('23', 'LONG ISLAND RAIL ROAD'),
        ('24', 'COMMERCIAL OR INDUSTRIAL'),
        ('25', 'APARTMENT BUILDING'),
        ('26', 'CONTAMINATED SITE'),
        ('27', 'GOLF COURSE'),
        ('28', 'RELIGIOUS INSTITUTION'),
        ('29', 'SCHOOL'),
        ('30', 'PARK'),
        ('31', 'CEMETERY'),
        ('32', 'ABUTS FIRE STATION'),
        ('33', 'SPLIT SCHOOL DISTRICT'),
        ('34', 'NOISE')
    ]),
    'palmbeach': OrderedDict([
        ('0', 'OCEAN VIEW'),
        ('1', 'OCEAN')
    ])
}

PROPERTY_STYLE_MAP = {
    'suffolk': OrderedDict([
        (1, 'RANCH'),
        (2, 'RAISE RANCH'),
        (3, 'SPLIT'),
        (4, 'CAPE'),
        (5, 'COLONIAL'),
        (6, 'CONTEMPORARY'),
        (7, 'MANSION'),
        (8, 'OLD STYLE'),
        (9, 'COTTAGE'),
        (10, 'ROW'),
        (11, 'LOG HOME'),
        (12, 'DUPLEX'),
        (13, 'BUNGALOW'),
        (14, 'OTHER'),
        (15, 'TOWNHOUSE'),
        (16, 'A-FRAME'),
        (17, 'MANUFACTURED HOUSING'),
    ]),
    'nassau': OrderedDict([
        (1, 'RANCH'),
        (2, 'RAISED RANCH/HI RANCH'),
        (3, 'SPLIT LEVEL'),
        (4, 'MODIFIED RANCH'),
        (5, 'CAPE'),
        (6, 'COLONIAL'),
        (7, 'VICTORIAN'),
        (8, 'CONTEMPORARY'),
        (9, 'OLD STYLE'),
        (10, 'BUNGALOW,COTTAGE'),
        (11, 'DUPLEX OR TRIPLEX'),
        (12, 'MANSION, ESTATE'),
        (13, 'TOWNHOUSE'),
        (14, 'CONDO'),
        (15, 'CO-OP'),
        (16, 'HOMOWNER ASSOC'),
        (17, 'OTHER'),
        (18, 'SPLANCH'),
        (19, 'CARRIAGE HOUSE'),
        (20, 'Tudor'),
        (21, 'Store/Dwell')
    ]),
    'broward': OrderedDict([
        (1, 'RESIDENTIAL'),
        (2, 'COMMERCIAL'),
        (3, 'INSTITUTIONAL'),
        (4, 'AGRICULTURAL'),
        (5, 'GOVERNMENT'),
        (6, 'MISCELLANEOUS'),
        (7, 'CENTRALLY ASSESSED'),
        (8, 'NON-AGRICULTURAL ACREAGE'),
    ]),
    'miamidade': OrderedDict(),
    'palmbeach': OrderedDict()
}

NASSAU_VILLAGES = [
    ('None', 'Select Village:'), ('No Village', 'No Village'),
    ('OB', 'Old Brookville'), ('KP', 'Kings Point'), ('FPS', 'South Floral Park'),
    ('CED', 'Cedarhurst'), ('PN', 'Port Washington North'),
    ('KE', 'Kensington'), ('FPT', 'Freeport'), ('HN', 'Hewlett Neck'),
    ('MH', 'Manorhaven'), ('CN', 'Cove Neck'), ('UB', 'Upper Brookville'),
    ('GE', 'Great Neck Estates'), ('CI', 'Centre Island'), ('PL', 'Plandome'),
    ('RVC', 'Rockville Centre'), ('HH', 'Hewlett Harbor'), ('EW', 'East Williston'),
    ('NHP', 'New Hyde Park'), ('RH', 'Roslyn Harbor'), ('MI', 'Mineola'),
    ('BRO', 'Brookville'), ('EH', 'East Hills'),
    ('MP', 'Munsey Park'), ('LYN', 'Lynbrook'), ('LH', 'Laurel Hollow,'),
    ('HEM', 'Hempstead'), ('SC', 'Sea Cliff'), ('SM', 'Stewart Manor'),
    ('GC', 'Garden City'), ('BLR', 'Bellerose'), ('FM', 'Farmingdale'),
    ('GLC', 'Glen Cove'), ('NH', 'North Hills'), ('AB', 'Atlantic Beach'),
    ('LT', 'Lattingtown'), ('RG', 'Russell Gardens'), ('MU', 'Muttontown'),
    ('SR', 'Saddle Rock'), ('MAL', 'Malverne'), ('RO', 'Roslyn'),
    ('FP', 'Floral Park'), ('PH', 'Plandome Heights'), ('ER', 'East Rockaway'),
    ('SU', 'Lake Success'), ('MN', 'Mill Neck'), ('SP', 'Sands Point'),
    ('RE', 'Roslyn Estates'), ('LB', 'Long Beach'), ('WBG', 'Woodsburgh'),
    ('HBP', 'Hewlett Bay Park'), ('GN', 'Great Neck'), ('OW', 'Old Westbury'),
    ('WE', 'Westbury'), ('TH', 'Thomaston'), ('GP', 'Great Neck Plaza'),
    ('OC', 'Oyster Bay Cove'), ('WP', 'Williston Park'), ('MK', 'Matinecock'),
    ('VS', 'Valley Stream'), ('BE', 'Baxter Estates'), ('LAW', 'Lawrence'),
    ('BAY', 'Bayville'), ('IP', 'Island Park'), ('PM', 'Plandome Manor'),
    ('FH', 'Flower Hill')
]


def get_field_type_desc(value_type, county, map_name: dict):
    """
    Get property field type description
    """
    assert map_name in (PATIO_TYPE_MAP, PAVING_TYPE_MAP, HEAT_TYPE_MAP, PORCH_TYPE_MAP)

    values = map_name.get(county)
    if values:
        return values.get(value_type)
    return None


def get_nassau_villages():
    """
    return tuple for the select field at masscma endpoint
    """
    nv = NASSAU_VILLAGES[:]
    nv.pop(0)
    nv.pop(0)
    nv.insert(0, ('All Villages', 'All Villages'))
    nv.insert(0, ('Whole County', 'Whole County'))
    return nv


def get_townships(towns, county):
    """return tuple for the select field at masscma endpoint"""
    county_map = towns.get(county.lower())
    result = [('Whole County', 'Whole County')]
    result += [(town, town) for _, town in county_map.items()]
    return result


# PROPERTY_CLASSES_MAP = {
#     'nassau': OrderedDict([
#         (0, 2100),
#         (1, 2102),
#         (2, 2150),
#         (3, 2200),
#         (4, 2300),
#         (5, 2400),
#         (6, 2500),
#         (7, 2600),
#         (8, 2800),
#         (9, 4121),
#         (10, 4122),
#         (11, 4127),
#         (12, 4830),
#         (13, 4831),
#         (14, 4832),
#     ]),
#     'suffolk': OrderedDict(),
#     'broward': OrderedDict(),
#     'miamidade': OrderedDict(),
#     'palmbeach': OrderedDict()
# }

PROPERTY_LAND_TAGS = {
    'nassau': {},
    'suffolk': {},
    'broward': {
        1: 'OCEAN FRONT ONLY',
        2: 'OCEAN FRONT/INTRACOSTAL',
        3: 'INTRACOASTAL LOT',
        4: 'INTRACOASTAL POINT LOT/MULTI WATER',
        5: 'DRY/INTRACOASTAL DOCKAGE',
        6: 'DRY/DOCKAGE ACROSS THE STREET OCEAN ACCESS',
        7: 'INLET',
        8: 'WATER/OCEAN ACCESS/NO FIXED BRIDGES',
        9: 'WATER/OCEAN ACCESS/POINT LOT',
        10: 'WATER/OCEAN ACCESS/POINT LOT/MULTI EXPOSURE',
        11: 'WATER/OCEAN ACCESS/END OF CANAL',
        12: 'WATER/FIXED BRIDGE OCEAN ACCESS',
        13: 'WATER/FIXED BRIDGE POINT LOT OCEAN ACCESS',
        14: 'WATER/FIXED BRIDGE/POINT LOT/MULTI EXPOSURE OCEAN ACCESS',
        15: 'WATER/FIXED BRIDGE/END OF CANAL OCEAN ACCESS',
        16: 'LOT WITH WATER INFLUENCE',
        17: 'NOT USED',
        18: 'NOT USED',
        19: 'NOT USED',
        20: 'GOLF COURSE LOT',
        21: 'DRY LOT',
        22: 'DRY LOT ABUTTING NON RESIDENTIAL PROPERTY',
        23: 'DRY LOT TWNHSE/PATIO HOME/ZERO LOT LINE HOMES',
        24: 'INTRACOASTAL TWNHSE/PATIO HOME/ZERO LOT LINE',
        25: 'WATER TWNHSE/PATIO HOME/ZERO LOT LINE OCEAN ACCESS',
        26: 'WATER TWNHSE/PATIO HOME/ZERO LOT LINE FIXED BRIDGE OCEAN ACCESS',
        27: 'GOLF COURSE TWNHSE/PATIO HOME/ZERO LOT LINE',
        28: 'TWNHSE/PATIO HOME/ZERO LOT LINE WITH WATER INFLUENCE',
        29: 'COMMON AREA RESIDENTIAL',
        30: 'PARENT PARCEL',
        31: 'MANUFACTURED HOUSING LOTS',
        51: 'LANDS ABUTTING EXPRESSWAY SYSTEMS',
        52: 'LANDS LOCATED ON US1/FEDERAL HWY SYSTEM WITH CORNER INFLUENCE',
        53: 'LANDS LOCATED ON US1/FEDERAL HWY SYSTEM WITH NO CORNER INFLUENCE',
        54: 'LANDS LOCATED ON STATE ROADS WITH CORNER INFLUENCE',
        55: 'LANDS LOCATED ON STATE ROADS WITH NO CORNER INFLUENCE',
        56: 'LANDS LOCATED ON PRIMARY LOCAL ROADS WITH CORNER INFLUENCE',
        57: 'LANDS LOCATED ON PRIMARY LOCAL ROADS WITH NO CORNER INFLUENCE',
        58: 'LANDS LOCATED ON LOCAL ROADS WITH CORNER INFLUENCE',
        59: 'LANDS LOCATED ON LOCAL ROADS WITH NO CORNER INFLUENCE',
        60: 'LANDS LOCATED ON FRONTAGE ROAD',
        61: 'BARRIER ISLAND - DRY LOT',
        62: 'BARRIER ISLAND - OCEAN FRONT',
        63: 'BARRIER ISLAND - DEEP WATER OCEAN ACCESS',
        64: 'LANDS LOCATED ON INTRACOASTAL WATERWAY NOT ON BARRIER ISLAND',
        65: 'OUTPARCEL',
        66: 'LANDS LOCATED IN PORT FACILITIES',
        67: 'LANDS LOCATED WITHIN AIRPORTS',
        68: 'GOLF COURSE',
        69: 'BARRIER ISLAND - LOCATED ON STATE ROADS WITH CORNER INFLUENCE',
        70: 'BARRIER ISLAND - LOCATED ON STATE ROADS WITH NO CORNER INFLUENCE',
        71: 'BARRIER ISLAND - LOCATED ON LOCAL ROADS WITH CORNER INFLUENCE',
        72: 'BARRIER ISLAND - LOCATED ON LOCAL ROADS WITH NO CORNER INFLUENCE',
        73: 'AGRICULTURE - USE CODES 50-69',
        74: 'GOVERNMENT - USE CODES 80-89',
        75: 'MISCELLANEOUS - USE CODES 90-97',
        76: 'RENTAL MANUFACTURED HOUSING LOT',
        77: 'WATER/OCEAN ACCESS/NO FIXED BRIDGES',
        78: 'WATER/OCEAN ACCESS/POINT LOT',
        79: 'WATER/OCEAN ACCESS/POINT LOT/MULTI EXPOSURE',
        80: 'WATER/OCEAN ACCESS/END OF CANAL',
        81: 'WATER/FIXED BRIDGE OCEAN ACCESS',
        82: 'WATER/FIXED BRIDGE POINT LOT OCEAN ACCESS',
        83: 'WATER/FIXED BRIDGE/POINT LOT/MULTI EXPOSURE OCEAN ACCESS',
        84: 'WATER/FIXED BRIDGE/END OF CANAL OCEAN ACCESS',
        85: 'LOT WITH WATER INFLUENCE',
        86: 'WORKING WATERFRONT PROPERTY',
    },
    'palmbeach': {},
    'miamidade': {},
}

PROPERTY_WATER_CATEGORY = {
    'nassau': {},
    'suffolk': {},
    'broward': {
        1: 'Ocean Front',
        2: 'Intercoastal',
        3: 'Point Lot',
        4: 'Ocean Access',
        5: 'Fixed Bridge',
        6: 'Water Influence'
    },
    'palmbeach': {},
    'miamidade': {},
}


# def get_property_classes(county_name: str) -> OrderedDict:
#     """
#     Get property classes by county name
#     """
#     return PROPERTY_CLASSES_MAP.get(county_name, OrderedDict())


def get_all_towns(towns):
    all_towns = []
    for _, county in towns.items():
        for _, town in county.items():
            all_towns.append(town)
    return all_towns


def get_town_code(towns, county, town_name):
    if not county:
        return None
    c = towns.get(county)
    return {value: key for key, value in c.items()}.get(town_name)


def get_town_name(towns, county, town_code):
    c = towns.get(county)
    return c.get(town_code)


def get_rule_for(property_rule, rule_name, price_start=None, price_end=None):
    """
    RulesController get_rule_for method to be used at jinja2
    """
    from app.rules.controllers import RulesController

    c = RulesController(property_rule)
    return c.get_rule_for(rule_name, price=price_start)[2] or c.get_rule_for(
        rule_name, price=price_end)[2]


class County:
    NASSAU = "nassau"
    SUFFOLK = "suffolk"
    BROWARD = "broward"
    MIAMIDADE = "miamidade"
    PALMBEACH = "palmbeach"

    _names_map = {
        NASSAU: "Nassau",
        SUFFOLK: "Suffolk",
        BROWARD: "Broward",
        MIAMIDADE: "Miami Dade",
        PALMBEACH: "Palm Beach"
    }

    _numbers_map = {
        # TODO: what is the numbers for the nassau, suffolk?!
        NASSAU: 0,
        SUFFOLK: 1,
        BROWARD: 16,
        MIAMIDADE: 23,
        PALMBEACH: 60
    }

    @classmethod
    def get_florida_counties(cls):
        return [cls.BROWARD, cls.MIAMIDADE, cls.PALMBEACH]

    @classmethod
    def get_counties(cls):
        """Get list on counties"""
        return [cls.NASSAU, cls.SUFFOLK, cls.BROWARD, cls.MIAMIDADE, cls.PALMBEACH]

    @classmethod
    def get_code(cls, name: str):
        """
        Get county code representation as we stored in database
        """
        if not name:
            return None

        name_parts = name.strip().split()

        # 'Palm Beach' or 'Miami Dade' case
        if len(name_parts) == 2:
            code = name_parts[0].lower() + name_parts[1].lower()

        # 'Nassau', 'Suffolk', 'Broward' case
        elif len(name_parts) == 1:
            code = name.lower()

        # invalid name
        else:
            return None

        # validate county code
        if code in cls.get_counties():
            return code
        else:
            return None

    @classmethod
    def names_map(cls):
        return cls._names_map

    @classmethod
    def numbers_map(cls):
        return cls._numbers_map


def extract_date_from_photo_name(photo_name):
    try:
        photo_name = photo_name.replace('.jpg', '')
        date_str = photo_name.split('_')[2]
        return datetime.strptime(date_str, "%Y-%m-%d").date()
    except IndexError:
        return None


console_log = get_console_logger('console_logger')

MIAMIDADE_CONDO_CODES = {
    '0BF': 'BAY FRONT',
    '0BV': 'BAY VIEW (OR HARBOR)',
    '0CF': 'CANAL FRONT',
    '0CY': 'CITY VIEW',
    '0GF': 'GOLF COURSE EXPOSURE',
    '0GR': 'ON GREEN BELT',
    '0GV': 'GOLF COURSE VIEW',
    '0IN': 'ON INTERCOASTAL',
    '0LF': 'LAKE FRONT EXPOSURE',
    '0LV': 'LAKEVIEW',
    '0NV': 'NO VIEW',
    '0OB': 'OBSTRUCTED VIEW',
    '0OF': 'OCEAN FRONT EXPOSURE',
    '0OV': 'OCEAN VIEW',
    '0PK': 'PARKING LOT EXPOSURE',
    '0PL': 'POOL AREA EXPOSURE',
    '0RA': 'RECREATIONAL AREA',
    '0ST': 'STREET EXPOSURE',
    '0UN': 'UNOBSTRUCTED VIEW',
    '1BV': 'CORNER W/BAY VIEW (OR HARBOR)',
    '1CF': 'CORNER CANAL FRONT',
    '1CY': 'CORNER CITY VIEW',
    '1GF': 'CORNER GOLF COURSE EXPOSURE',
    '1NE': 'NORTH EAST EXPOSURE',
    '1NW': 'NORTH WEST EXPOSURE',
    '1SE': 'SOUTH EAST EXPOSURE',
    '1SW': 'SOUTH WEST EXPOSURE',
    '1UN': 'CORNER UNOBSTRUCTED VIEW',
    '2BF': 'INTERIOR BAY FRONT (OR HARBOR)',
    '2BV': 'INTERIOR W/ BAY VIEW',
    '2CY': 'INTERIOR CITY VIEW',
    '2GF': 'INTERIOR GOLF COURSE EXPOSURE',
    '2GV': 'INTERIOR W/ GOLF COURSE VIEW',
    '2IN': 'INTERIOR ON INTRACOASTAL',
    '2NE': 'NORTH EAST EXPOSURE',
    '2NV': 'INTERIOR NO VIEW',
    '2NW': 'NORTH WEST EXPOSURE',
    '2OB': 'INTERIOR OBSTRUCTED VIEW',
    '2OV': 'INTERIOR W/ OCEAN VIEW',
    '2PK': 'INTERIOR PARKING LOT EXPOSUE',
    '2RA': 'INTERIOR RECREATION AREA',
    '2SE': 'INTERIOR SOUTH EAST EXPOSURE',
    '2SW': 'INTERIOR SOUTH WEST EXPOSURE',
    '2UN': 'INTERIOR UNOBSTRUCTED VIEW',
    '4BF': 'TOP FLOOR CORNER BAY FRONT',
    '4BV': 'TOP FLOOR CORNER W/BAY VIEW',
    '4CF': 'TOP FLOOR CORNER CANAL FRONT',
    '4CY': 'TOP FLOOR CORNER CITY VIEW',
    '4GF': 'TOP FLOOR CORNER GOLF COURSE EXPOSURE',
    '4GR': 'TOP FLOOR CORNER ON GREEN BELT',
    '4GV': 'TOP FLOOR CORNER W/ GOLF COURSE VIEW',
    '4IN': 'TOP FLOOR CORNER ON INTERCOASTAL',
    '4LF': 'TOP FLOOR CORNER LAKE FRONT EXPOSURE',
    '4LV': 'TOP FLOOR CORNER W/ LAKEVIEW',
    '4NE': 'TOP FLOOR CORNER NORTH EAST EXPOSURE',
    '4NV': 'TOP FLOOR CORNER NO VIEW',
    '4NW': 'TOP FLOOR CORNER NORTH WEST EXPOSURE',
    '4OB': 'TOP FLOOR CORNER OBSTRUCTED VIEW',
    '4OF': 'TOP FLOOR CORNER OCEAN FRONT',
    '4OV': 'TOP FLOOR CORNER W/ OCEAN VIEW',
    '4PK': 'TOP FLOOR CORNER PARKING LOT',
    '4PL': 'TOP FLOOR CORNER POOL AREA EXPOSURE',
    '4RA': 'TOP FLOOR CORNER RECREATION AREA',
    '4SE': 'TOP FLOOR CORNER SOUTH EAST EXPOSURE',
    '4ST': 'TOP FLOOR CORNER STREET EXPOSURE',
    '4SW': 'TOP FLOOR CORNER SOUTH WEST EXPOSURE',
    '4UN': 'TOP FLOOR CORNER UNOBSTRUCTED VIEW',
    '5BF': 'TOP FLOOR INTERIOR BAY FRONT',
    '5BV': 'TOP FLOOR INTERIOR W/BAY VIEW',
    '5CF': 'TOP FLOOR INTERIOR CANAL FRONT',
    '5CY': 'TOP FLOOR INTERIOR CITY VIEW',
    '5GF': 'TOP FLOOR INTERIOR GOLF COURSE',
    '5GR': 'TOP FLOOR INTERIOR GREEN BELT',
    '5GV': 'TOP FLOOR INTERIOR INTRACOSTAL',
    '5LF': 'TOP FLOOR INTERIOR LAKE FRONT',
    '5LV': 'TOP FLOOR INTERIOR W/ LAKEVIEW',
    '5NE': 'TOP FLOOR INTERIOR NORTH EAST EXPOSURE',
    '5NV': 'TOP FLOOR INTERIOR NO VIEW',
    '5NW': 'TOP FLOOR INTERIOR NORTH WEST EXPOSURE',
    '5OB': 'TOP FLOOR INTERIOR OBSTRUCTED VIEW',
    '5OF': 'TOP FLOOR INTERIOR OCEAN FRONT',
    '5OV': 'TOP FLOOR INTERIOR OCEAN VIEW',
    '5PK': 'TOP FLOOR INTERIOR PARKING LOT',
    '5PL': 'TOP FLOOR INTERIOR POOL AREA EXPOSURE',
    '5RA': 'TOP FLOOR INTERIOR RECREATION AREA',
    '5SE': 'TOP FLOOR INTERIOR SOUTH EAST EXPOSURE',
    '5ST': 'TOP FLOOR INTERIOR STREET EXPOSURE',
    '5SW': 'TOP FLOOR INTERIOR SOUTH WEST EXPOSURE',
    '5UN': 'TOP FLOOR INTERIOR UNOBSTRUCTED VIEW',
    '9CA': 'COMMON AREA (USE)',
    '9CB': 'CABANA (USE)',
    '9CO': 'COMMERCIAL OFFICE (USE)',
    '9CR': 'COMMERCIAL RETAIL (USE)',
    '9CS': 'COMMERCIAL SHELL (USE)',
    '9DK': 'DOCK (USE)',
    '9GA': 'GARAGE (USE)',
    '9HU': 'HOTEL UNIT',
    '9LA': 'LAUNDRY (USE)',
    '9NC': 'NOT YET CONSTRUCTED (USE)',
    '9PS': 'PARKING SPACE (USE)',
    '9PT': 'PATIO TERRACE (USE)',
    '9SG': 'STORAGE (USE)',
    '1BF': 'CORNER BAY FRONT',
    '1GR': 'CORNER ON GREEN BELT',
    '1GV': 'CORNER W/ GOLF COURSE VIEW',
    '1IN': 'CORNER ON INTRACOASTAL',
    '1LF': 'CORNER LAKE FRONT EXPOSURE',
    '1LV': 'CORNER W/ LAKEVIEW',
    '1NV': 'CORNER NO VIEW',
    '1OF': 'CORNER OCEAN FRONT EXPOSURE',
    '1OV': 'CORNER OCEAN VIEW',
    '1PK': 'CORNER PARKING LOT EXPOSURE',
    '1PL': 'CORNER POOL AREA EXPOSURE',
    '1RA': 'CORNER RECREATION AREA',
    '1ST': 'CORNER STREET EXPOSURE',
    '2CF': 'INTERIOR CANAL FRONT',
    '2CV': 'LAND',
    '2GR': 'INTERIOR ON GREEN BELT',
    '2LF': 'INTERIOR LAKE FRONT EXPOSURE',
    '2LV': 'INTERIOR W/ LAKEVIEW',
    '2OF': 'INTERIOR OCEAN FRONT EXPOSURE',
    '2OL': 'OVERSIZE LOT ADJUSTMENT 2',
    '2PL': 'INTERIOR POOL AREA EXPOSURE',
    '2ST': 'INTERIOR STREET EXPOSURE',
    '1OL': 'OVERSIZE LOT ADJUSTMENT 1',
    '3BV': 'CUL-DE-SAC W/ BAY VIEW',
    '3CF': 'CUL-DE-SAC CANAL FRONT',
    '3FA': 'CUL-DE-SAC FLOOD AREA',
    '3GR': 'CUL-DE-SAC ON GREEN BELT',
    '3LF': 'CUL-DE-SAC LAKE FRONT EXPOSURE',
    '3LV': 'CUL-DE-SAC W/ LAKEVIEW',
    '3NV': 'CUL-DE-SAC NO VIEW',
    '3ST': 'CUL-DE-SAC STREET EXPOSURE',
    '9E1': 'ECONOMIC OBSOLESCENCE 1',
    '9E2': 'ECONOMIC OBSOLESCENCE 2',
    '9E3': 'ECONOMIC OBSOLESCENCE 3',
    '9E4': 'ECONOMIC OBSOLESCENCE 4',
    '9E6': 'ECONOMIC OBS 6 LIFT STATION',
    'IEE': "LOT W/INGRESS & EGRESS EASM'T",
    'OSL': 'OVERSIZE LOT ADJUSTMENT',
    'SBF': 'SPCL INTERIOR BAY FRONT',
    'SCF': 'SPECIAL CANAL FRONT',
    'SCR': 'SPCL CORNER NO VIEW',
    'SL1': 'SPCL CORNER LK EXPOSURE',
    'SL2': 'SPCL INTERIOR LK EXPOSURE',
    'SLF': 'SPECIAL LAKE FRONT',
    'SV1': 'SPCL CORNER VIEW EXPOSURE',
    'SV2': 'SPCL INTERIOR LAKE VIEW'
}


def get_broward_property_code_descriptions():
    return OrderedDict([
        (0, 'Vacant residential'),
        (1, 'Single family'),
        (2, 'Mobile homes'),
        (3, 'Multi-family – 10 units or more'),
        (4, 'Condominium'),
        (5, 'Cooperatives'),
        (6, 'Retirement homes (not eligible for exemption under section 196.192 F.S. others '
            'shall be given an institutional classification)'),
        (7, 'Miscellaneous residential (migrant camp, boarding homes, etc.)'),
        (8, 'Multi-family – less than 10 units'),
        (9, 'Residential common elements/areas'),
        (10, 'Vacant commercial'),
        (11, 'Stores, 1-story'),
        (12, 'Mixed use – store and office or store and residential or residential combination'),
        (13, 'Department stores'),
        (14, 'Supermarkets'),
        (15, 'Regional shopping centers'),
        (16, 'Community shopping centers'),
        (17, 'Office buildings, non-professional services buildings, one-story'),
        (18, 'Office buildings, non-professional services buildings, multi-story'),
        (19, 'Professional services building'),
        (20, 'Airports (private or commercial), bus terminals, marine terminals, piers, marinas'),
        (21, 'Restaurants, cafeterias'),
        (22, 'Drive-in restaurants'),
        (23, 'Financial institutions (banks, savings & loan companies, mortgage companies, credit services)'),
        (24, 'Insurance company offices'),
        (25, 'Repair service shops (excluding automotive), radio & TV repair, laundries, laundromats'),
        (26, 'Service stations'),
        (27, 'Auto sales, repair and storage, auto-service shops, body and fender shops, commercial garages, farm and '
             'machinery sales and services, auto rental, marine equipment, mobile home sales, motorcycles, '
             'construction vehicle sales'),
        (28, 'Parking lots (commercial or patron), mobile home parks'),
        (29, 'Wholesale outlets, produce houses, manufacturing outlets'),
        (30, 'Florist, greenhouses'),
        (31, 'Drive-in theatres, open stadiums'),
        (32, 'Enclosed theatres, enclosed auditoriums'),
        (33, 'Nightclubs, cocktail lounges, bars, yacht clubs, social clubs, tennis clubs, clubhouses'),
        (34, 'Bowling alleys, skating rinks, pool halls, enclosed arenas'),
        (35, 'Tourist attractions, permanent exhibits, other entertainment facilities, fairgrounds (privately owned)'),
        (36, 'Camps'),
        (37, 'Race tracks, horse, auto or dog'),
        (38, 'Golf courses, driving ranges'),
        (39, 'Hotels, motels'),
        (40, 'Vacant industrial'),
        (41, 'Light manufacturing, small equipment manufacturing plants, small machine shops, instrument '
             'manufacturing, printing plants'),
        (42, 'Heavy industrial, heavy equipment manufacturing, large machine shops, foundries, steel fabricating '
             'plants, auto or aircraft plants'),
        (43, 'Lumber yards, sawmills, planning mills'),
        (44, 'Packing plants, fruit & vegetable packing plants, meat packing plants'),
        (45, 'Canneries, fruit & vegetable, bottlers & brewers, distillers, wineries'),
        (46, 'Other food processing, candy factories, bakeries, potato chip factories'),
        (47, 'Mineral processing, phosphate processing, cement plants, refineries, clay plants, rock & gravel plants'),
        (48, 'Warehousing, distribution terminals, trucking terminals, van & storage warehousing'),
        (49, 'Open storage, new & used bldg supplies, junk yards, auto wrecking, fuel storage, equipment & '
             'materials storage'),
        (50, 'Improved agricultural'),
        (51, 'Cropland soil capability class I'),
        (51, 'Cropland soil capability class II'),
        (53, 'Cropland soil capability class III'),
        (54, 'Timberland – site index 90 & above'),
        (55, 'Timberland – site index 80-89'),
        (56, 'Timberland – site index 70-79'),
        (57, 'Timberland – site index 60-69'),
        (58, 'Timberland – site index 50-59'),
        (59, 'Timberland not classified by site index to pines'),
        (60, 'Grazing land soil capability class I'),
        (61, 'Grazing land soil capability class II'),
        (62, 'Grazing land soil capability class III'),
        (63, 'Grazing land soil capability class IV'),
        (64, 'Grazing land soil capability class V'),
        (65, 'Grazing land soil capability class VI'),
        (66, 'Orchard groves, citrus, etc'),
        (67, 'Poultry, bees, tropical fish, rabbits, etc.'),
        (68, 'Dairies, feed lots'),
        (69, 'Ornamentals, miscellaneous agriculture'),
        (70, 'Vacant institutional'),
        (71, 'Churches'),
        (72, 'Private schools and colleges'),
        (73, 'Privately owned hospitals'),
        (74, 'Homes for the aged'),
        (75, 'Orphanages, other non-profit or charitable services'),
        (76, 'Mortuaries, cemeteries, crematoriums'),
        (77, 'Clubs, lodges, union halls'),
        (78, 'Sanitariums, convalescent & rest homes'),
        (79, 'Cultural organizations, facilities'),
        (80, 'Vacant governmental'),
        (81, 'Military'),
        (82, 'Forests, parks, recreational areas'),
        (83, 'Public county schools – includes all property of board of public instruction'),
        (84, 'Colleges'),
        (85, 'Hospitals'),
        (86, 'Counties (other than public schools, colleges, hospitals) including non-municipal'),
        (87, 'State other than military, forests, parks, recreational areas, colleges, hospitals'),
        (88, 'Federal other than military, forests, parks, recreational areas, hospitals, colleges'),
        (89, 'Municipal other than parks, recreational areas, colleges, hospitals'),
        (90, 'Leasehold interests (government owned property leased by a non-governmental lessee)'),
        (91, 'Utility, gas & electricity, telephone & telegraph, locally assessed railroads, water & sewer service, '
             'pipelines, canals, radio/television communication'),
        (92, 'Mining lands, petroleum lands, or gas lands'),
        (93, 'Subsurface rights'),
        (94, 'Right-of-way, streets, roads, irrigation channel, ditch, etc.'),
        (95, 'Rivers & lakes, submerged lands'),
        (96, 'Sewage disposal, solid waste, borrow pits, drainage reservoirs, waste lands, marsh, sand dunes, swamps'),
        (97, 'Outdoor recreational or park land subject to classified use assessment'),
        (98, 'Centrally assessed'),
        (99, 'Acreage not zoned agricultural'),
    ])


def get_miamidade_property_code_descriptions():
    return OrderedDict([
        (0, 'REFERENCE FOLIO'),
        (1, 'VACANT RESIDENTIAL : RESIDENTIAL - SINGLE FAMILY'),
        (4, 'VACANT RESIDENTIAL : RESIDENTIAL - TOTAL VALUE'),
        (5, 'VACANT RESIDENTIAL : CLUSTER HOME'),
        (7, 'VACANT RESIDENTIAL: CONDO'),
        (10, 'VACANT : TOWNHOUSE'),
        (17, 'VACANT RESIDENTIAL : COMMERCIAL - TOTAL VALUE'),
        (23, 'VACANT RESIDENTIAL : CONDOMINIUM - TIMESHARING'),
        (40, 'VACANT RESIDENTIAL : MUNICIPAL'),
        (65, 'VACANT RESIDENTIAL : PARKING LOT'),
        (66, 'VACANT RESIDENTIAL : EXTRA FEA OTHER THAN PARKING'),
        (80, 'VACANT RESIDENTIAL : VACANT LAND - GOVERNMENTAL'),
        (81, 'VACANT RESIDENTIAL : VACANT LAND'),
        (89, 'VACANT RESIDENTIAL : BACK ASSESSMENT'),
        (101, 'RESIDENTIAL - SINGLE FAMILY : 1 UNIT'),
        (102, 'RESIDENTIAL - SINGLE FAMILY : 2 LIVING UNITS'),
        (103, 'RESIDENTIAL - SINGLE FAMILY : MULTIFAMILY 3 OR MORE UNITS'),
        (104, 'RESIDENTIAL - SINGLE FAMILY : RESIDENTIAL - TOTAL VALUE'),
        (105, 'RESIDENTIAL - SINGLE FAMILY : CLUSTER HOME'),
        (109, 'RESIDENTIAL - SINGLE FAMILY : MIXED USE - RESIDENTIAL'),
        (121, 'RESIDENTIAL - SINGLE FAMILY : HOTEL'),
        (125, 'RESIDENTIAL - SINGLE FAMILY : ENTERPRISE ZONE TOTAL VALUE'),
        (132, 'RESIDENTIAL - SINGLE FAMILY : LIGHT MFG & FOOD PROCESSING'),
        (166, 'RESIDENTIAL - SINGLE FAMILY : EXTRA FEA OTHER THAN PARKING'),
        (189, 'RESIDENTIAL - SINGLE FAMILY : BACK ASSESSMENT'),
        (206, 'MOBILE HOME : MOBILE HOME'),
        (217, 'MOBILE HOME : COMMERCIAL - TOTAL VALUE'),
        (289, 'MOBILE HOME : BACK ASSESSMENT'),
        (303, 'MULTIFAMILY 10 UNITS PLUS : MULTIFAMILY 3 OR MORE UNITS'),
        (313, 'MULTIFAMILY 10 UNITS PLUS : OFFICE BUILDING'),
        (317, 'MULTIFAMILY 10 UNITS PLUS : COMMERCIAL - TOTAL VALUE'),
        (325, 'MULTIFAMILY 10 UNITS PLUS : ENTERPRISE ZONE TOTAL VALUE'),
        (329, 'MULTIFAMILY 10 UNITS PLUS : MIXED USE - COMMERCIAL'),
        (389, 'MULTIFAMILY 10 UNITS PLUS : BACK ASSESSMENT'),
        (404, 'RESIDENTIAL - TOTAL VALUE : RESIDENTIAL - TOTAL VALUE'),
        (405, 'RESIDENTIAL - TOTAL VALUE : CLUSTER HOME'),
        (407, 'RESIDENTIAL - TOTAL VALUE : CONDOMINIUM - RESIDENTIAL'),
        (410, 'RESIDENTIAL - TOTAL VALUE : TOWNHOUSE'),
        (417, 'RESIDENTIAL - TOTAL VALUE : COMMERCIAL - TOTAL VALUE'),
        (418, 'RESIDENTIAL - TOTAL VALUE : CONDOMINIUM - COMMERCIAL'),
        (420, 'RESIDENTIAL - TOTAL VALUE : DOCK - TOTAL VALUE'),
        (423, 'RESIDENTIAL - TOTAL VALUE : CONDOMINIUM - TIMESHARING'),
        (425, 'RESIDENTIAL - TOTAL VALUE : ENTERPRISE ZONE TOTAL VALUE'),
        (466, 'RESIDENTIAL - TOTAL VALUE : EXTRA FEA OTHER THAN PARKING'),
        (489, 'RESIDENTIAL - TOTAL VALUE : BACK ASSESSMENT'),
        (508, 'COOPERATIVE - RESIDENTIAL : COOPERATIVE - RESIDENTIAL'),
        (617, 'RETIREMENT HOME : COMMERCIAL - TOTAL VALUE'),
        (643, 'RETIREMENT HOME : HEALTH CARE'),
        (703, 'MISCELLANEOUS - RESIDENTIAL : MULTIFAMILY 3 OR MORE UNITS'),
        (709, 'MISCELLANEOUS - RESIDENTIAL : MIXED USE - RESIDENTIAL'),
        (713, 'MISCELLANEOUS - RESIDENTIAL : OFFICE BUILDING'),
        (717, 'MISCELLANEOUS - RESIDENTIAL : COMMERCIAL - TOTAL VALUE'),
        (719, 'MISCELLANEOUS - RESIDENTIAL : AUTOMOTIVE OR MARINE'),
        (724, 'MISCELLANEOUS - RESIDENTIAL : CAMPSITE'),
        (741, 'MISCELLANEOUS - RESIDENTIAL : EDUCATIONAL - PRIVATE'),
        (743, 'MISCELLANEOUS - RESIDENTIAL : HEALTH CARE'),
        (744, 'MISCELLANEOUS - RESIDENTIAL : RELIGIOUS'),
        (789, 'MISCELLANEOUS - RESIDENTIAL : BACK ASSESSMENT'),
        (801, 'MULTIFAMILY 2-9 UNITS : RESIDENTIAL - SINGLE FAMILY'),
        (802, 'MULTIFAMILY 2-9 UNITS : 2 LIVING UNITS'),
        (803, 'MULTIFAMILY 2-9 UNITS : MULTIFAMILY 3 OR MORE UNITS'),
        (817, 'MULTIFAMILY 2-9 UNITS : COMMERCIAL - TOTAL VALUE'),
        (819, 'MULTIFAMILY 2-9 UNITS : AUTOMOTIVE OR MARINE'),
        (837, 'MULTIFAMILY 2-9 UNITS : WAREHOUSE OR STORAGE'),
        (841, 'MULTIFAMILY 2-9 UNITS : EDUCATIONAL - PRIVATE'),
        (865, 'MULTIFAMILY 2-9 UNITS : PARKING LOT'),
        (866, 'MULTIFAMILY 2-9 UNITS : EXTRA FEA OTHER THAN PARKING'),
        (881, 'MULTIFAMILY 2-9 UNITS : VACANT LAND'),
        (889, 'MULTIFAMILY 2-9 UNITS : BACK ASSESSMENT'),
        (1001, 'XF ON COMMERCIAL AC'),
        (1009, 'VACANT LAND - COMMERCIAL : MIXED USE - RESIDENTIAL'),
        (1017, 'VACANT LAND - COMMERCIAL : COMMERCIAL - TOTAL VALUE'),
        (1018, 'VACANT COMMERCIAL - CONDO'),
        (1031, 'VACANT LAND - COMMERCIAL : MINERAL PROCESSING'),
        (1036, 'VACANT LAND - COMMERCIAL : HEAVY IND OR LUMBER YARD'),
        (1053, 'VACANT LAND - COMMERCIAL : GOLF COURSE'),
        (1065, 'VACANT LAND - COMMERCIAL : PARKING LOT'),
        (1066, 'VACANT LAND - COMMERCIAL : EXTRA FEA OTHER THAN PARKING'),
        (1080, 'VACANT LAND - COMMERCIAL : VACANT LAND - GOVERNMENTAL'),
        (1081, 'VACANT LAND - COMMERCIAL : VACANT LAND'),
        (1084, 'VACANT LAND - COMMERCIAL : RECREATIONAL OR ENDANGERED'),
        (1089, 'VACANT LAND - COMMERCIAL : BACK ASSESSMENT'),
        (1109, 'STORE : MIXED USE - RESIDENTIAL'),
        (1111, 'STORE : RETAIL OUTLET'),
        (1112, 'STORE : REPAIRS - NON AUTOMOTIVE'),
        (1113, 'STORE : OFFICE BUILDING'),
        (1115, 'STORE : ENTERTAINMENT'),
        (1117, 'STORE : COMMERCIAL - TOTAL VALUE'),
        (1118, 'STORE : CONDOMINIUM - COMMERCIAL'),
        (1119, 'STORE : AUTOMOTIVE OR MARINE'),
        (1126, 'STORE : SERVICE STATION - AUTOMOTIVE'),
        (1129, 'STORE : MIXED USE - COMMERCIAL'),
        (1136, 'STORE : HEAVY IND OR LUMBER YARD'),
        (1139, 'STORE : MIXED USE - INDUSTRIAL'),
        (1143, 'STORE : HEALTH CARE'),
        (1144, 'STORE : RELIGIOUS'),
        (1166, 'STORE : EXTRA FEA OTHER THAN PARKING'),
        (1189, 'STORE : BACK ASSESSMENT'),
        (1206, 'MIXED USE-STORE/RESIDENTIAL : MOBILE HOME'),
        (1209, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - RESIDENTIAL'),
        (1211, 'MIXED USE-STORE/RESIDENTIAL : RETAIL OUTLET'),
        (1212, 'MIXED USE-STORE/RESIDENTIAL : REPAIRS - NON AUTOMOTIVE'),
        (1213, 'MIXED USE-STORE/RESIDENTIAL : OFFICE BUILDING'),
        (1214, 'MIXED USE-STORE/RESIDENTIAL : WHOLESALE OUTLET'),
        (1215, 'MIXED USE-STORE/RESIDENTIAL : ENTERTAINMENT'),
        (1217, 'MIXED USE-STORE/RESIDENTIAL : COMMERCIAL - TOTAL VALUE'),
        (1218, 'MIXED USE-STORE/RESIDENTIAL : CONDOMINIUM - COMMERCIAL'),
        (1219, 'MIXED USE-STORE/RESIDENTIAL : AUTOMOTIVE OR MARINE'),
        (1225, 'MIXED USE-STORE/RESIDENTIAL : ENTERPRISE ZONE TOTAL VALUE'),
        (1229, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - COMMERCIAL'),
        (1232, 'MIXED USE-STORE/RESIDENTIAL : LIGHT MFG & FOOD PROCESSING'),
        (1234, 'MIXED USE-STORE/RESIDENTIAL : CANNERIES - BOTTLER'),
        (1236, 'MIXED USE-STORE/RESIDENTIAL : HEAVY IND OR LUMBER YARD'),
        (1237, 'MIXED USE-STORE/RESIDENTIAL : WAREHOUSE OR STORAGE'),
        (1239, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - INDUSTRIAL'),
        (1244, 'MIXED USE-STORE/RESIDENTIAL : RELIGIOUS'),
        (1249, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - GOVERNMENTAL'),
        (1259, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - INSTITUTIONAL'),
        (1279, 'MIXED USE-STORE/RESIDENTIAL : MIXED USE - AGRICULTURAL'),
        (1289, 'MIXED USE-STORE/RESIDENTIAL : BACK ASSESSMENT'),
        (1311, 'DEPARTMENT STORE : RETAIL OUTLET'),
        (1317, 'DEPARTMENT STORE : COMMERCIAL - TOTAL VALUE'),
        (1411, 'SUPERMARKET : RETAIL OUTLET'),
        (1489, 'REGIONAL SHOPPING CENTER : BACK ASSESSMENT'),
        (1511, 'REGIONAL SHOPPING CENTER : RETAIL OUTLET'),
        (1517, 'REGIONAL SHOPPING CENTER : COMMERCIAL - TOTAL VALUE'),
        (1531, 'REGIONAL SHOPPING CENTER : MINERAL PROCESSING'),
        (1607, 'COMMUNITY SHOPPING CENTER : CONDOMINIUM - RESIDENTIAL'),
        (1611, 'COMMUNITY SHOPPING CENTER : RETAIL OUTLET'),
        (1617, 'COMMUNITY SHOPPING CENTER : COMMERCIAL - TOTAL VALUE'),
        (1619, 'COMMUNITY SHOPPING CENTER : AUTOMOTIVE OR MARINE'),
        (1629, 'COMMUNITY SHOPPING CENTER : MIXED USE - COMMERCIAL'),
        (1689, 'COMMUNITY SHOPPING CENTER : BACK ASSESSMENT'),
        (1701, 'OFFICE BUILDING - ONE STORY : RESIDENTIAL - SINGLE FAMILY'),
        (1709, 'OFFICE BUILDING - ONE STORY : MIXED USE - RESIDENTIAL'),
        (1711, 'OFFICE BUILDING - ONE STORY : RETAIL OUTLET'),
        (1712, 'OFFICE BUILDING - ONE STORY : REPAIRS - NON AUTOMOTIVE'),
        (1713, 'OFFICE BUILDING - ONE STORY : OFFICE BUILDING'),
        (1714, 'OFFICE BUILDING - ONE STORY : WHOLESALE OUTLET'),
        (1719, 'OFFICE BUILDING - ONE STORY : AUTOMOTIVE OR MARINE'),
        (1729, 'OFFICE BUILDING - ONE STORY : MIXED USE - COMMERCIAL'),
        (1740, 'OFFICE BUILDING - ONE STORY : MUNICIPAL'),
        (1741, 'OFFICE BUILDING - ONE STORY : EDUCATIONAL - PRIVATE'),
        (1742, 'OFFICE BUILDING - ONE STORY : CLUB OR HALL - PRIVATE'),
        (1743, 'OFFICE BUILDING - ONE STORY : HEALTH CARE'),
        (1744, 'OFFICE BUILDING - ONE STORY : RELIGIOUS'),
        (1789, 'OFFICE BUILDING - ONE STORY : BACK ASSESSMENT'),
        (1811, 'OFFICE BUILDING - MULTISTORY : RETAIL OUTLET'),
        (1813, 'OFFICE BUILDING - MULTISTORY : OFFICE BUILDING'),
        (1817, 'OFFICE BUILDING - MULTISTORY : COMMERCIAL - TOTAL VALUE'),
        (1818, 'OFFICE BUILDING - MULTISTORY : CONDOMINIUM - COMMERCIAL'),
        (1819, 'OFFICE BUILDING - MULTISTORY : AUTOMOTIVE OR MARINE'),
        (1829, 'OFFICE BUILDING - MULTISTORY : MIXED USE - COMMERCIAL'),
        (1841, 'OFFICE BUILDING - MULTISTORY : EDUCATIONAL - PRIVATE'),
        (1842, 'OFFICE BUILDING - MULTISTORY : CLUB OR HALL - PRIVATE'),
        (1863, 'OFFICE BUILDING - MULTISTORY : UTILITY'),
        (1889, 'OFFICE BUILDING - MULTISTORY : BACK ASSESMENT'),
        (1909, 'PROFESSIONAL SERVICE BLDG : MIXED USE - RESIDENTIAL'),
        (1911, 'PROFESSIONAL SERVICE BLDG : RETAIL OUTLET'),
        (1912, 'PROFESSIONAL SERVICE BLDG : REPAIRS - NON AUTOMOTIVE'),
        (1913, 'PROFESSIONAL SERVICE BLDG : OFFICE BUILDING'),
        (1915, 'PROFESSIONAL SERVICE BLDG : ENTERTAINMENT'),
        (1917, 'PROFESSIONAL SERVICE BLDG : COMMERCIAL TOTAL VALUE'),
        (1918, 'PROFESSIONAL SERVICE BLDG : CONDOMINIUM - COMMERCIAL'),
        (1919, 'PROFESSIONAL SERVICE BLDG : AUTOMOTIVE OR MARINE'),
        (1929, 'PROFESSIONAL SERVICE BLDG : MIXED USE - COMMERCIAL'),
        (1939, 'PROFESSIONAL SERVICE BLDG : MIXED USE - INDUSTRIAL'),
        (1940, 'PROFESSIONAL SERVICE BLDG : MUNICIPAL'),
        (1941, 'PROFESSIONAL SERVICE BLDG : EDUCATIONAL - PRIVATE'),
        (1943, 'PROFESSIONAL SERVICE BLDG : HEALTH CARE'),
        (1969, 'PROFESSIONAL SERVICE BLDG : MIXED USE - MISCELLANEOUS'),
        (1989, 'PROFESSIONAL SERVICE BLDG : BACK ASSESSMENT'),
        (2006, 'AIRPORT/TERMINAL OR MARINA : MOBILE HOME'),
        (2011, 'AIRPORT/TERMINAL OR MARINA : RETAIL OUTLET'),
        (2017, 'AIRPORT/TERMINAL OR MARINA : COMMERCIAL - TOTAL VALUE'),
        (2020, 'AIRPORT/TERMINAL OR MARINA : DOCK - TOTAL VALUE'),
        (2061, 'AIRPORT/TERMINAL OR MARINA : AIRPORT/TERMINAL OR MARINA'),
        # (2089
        (2101, 'RESTAURANT OR CAFETERIA : RESIDENTIAL - SINGLE FAMILY'),
        (2111, 'RESTAURANT OR CAFETERIA : RETAIL OUTLET'),
        (2112, 'RESTAURANT OR CAFETERIA : REPAIRS - NON AUTOMOTIVE'),
        (2113, 'RESTAURANT OR CAFETERIA : OFFICE BUILDING'),
        (2115, 'RESTAURANT OR CAFETERIA : ENTERTAINMENT'),
        (2117, 'RESTAURANT OR CAFETERIA : COMMERCIAL - TOTAL VALUE'),
        (2119, 'RESTAURANT OR CAFETERIA : AUTOMOTIVE OR MARINE'),
        (2129, 'RESTAURANT OR CAFETERIA : MIXED USE - COMMERCIAL'),
        (2142, 'RESTAURANT OR CAFETERIA : CLUB OR HALL - PRIVATE'),
        (2144, 'RESTAURANT OR CAFETERIA : RELIGIOUS'),
        (2189, 'RESTAURANT OR CAFETERIA : BACK ASSESSMENT'),
        (2211, 'DRIVE-IN RESTAURANT : RETAIL OUTLET'),
        (2217, 'DRIVE-IN RESTAURANT : COMMERCIAL - TOTAL VALUE'),
        (2289, 'DRIVE-IN RESTAURANT : BACK ASSESSMENT'),
        (2311, 'FINANCIAL INSTITUTION : RETAIL OUTLET'),
        (2312, 'FINANCIAL INSTITUTION : REPAIRS - NON AUTOMOTIVE'),
        (2313, 'FINANCIAL INSTITUTION : OFFICE BUILDING'),
        (2318, 'FINANCIAL INSTITUTION : CONDOMINIUM - COMMERCIAL'),
        (2329, 'FINANCIAL INSTITUTION : MIXED USE - COMMERCIAL'),
        (2389, 'FINANCIAL INSTITUTION : BACK ASSESSMENT'),
        (2413, 'INSURANCE COMPANY : OFFICE BUILDING'),
        (2511, 'REPAIR SHOP/NON AUTOMOTIVE : RETAIL OUTLET'),
        (2512, 'REPAIR SHOP/NON AUTOMOTIVE : REPAIRS - NON AUTOMOTIVE'),
        (2529, 'REPAIR SHOP/NON AUTOMOTIVE : MIXED USE - COMMERCIAL'),
        (2537, 'REPAIR SHOP/NON AUTOMOTIVE : WAREHOUSE OR STORAGE'),
        (2566, 'REPAIR SHOP/NON AUTOMOTIVE : EXTRA FEA OTHER THAN PARKING'),
        (2611, 'SERVICE STATION : RETAIL OUTLET'),
        (2617, 'SERVICE STATION : COMMERCIAL - TOTAL VALUE'),
        (2619, 'SERVICE STATION : AUTOMOTIVE OR MARINE'),
        (2625, 'SERVICE STATION : ENTERPRISE ZONE TOTAL VALUE'),
        (2626, 'SERVICE STATION : SERVICE STATION - AUTOMOTIVE'),
        (2629, 'SERVICE STATION : MIXED USE - COMMERCIAL'),
        (2689, 'SERVICE STATION : BACK ASSESSMENT'),
        (2711, 'AUTOMOTIVE OR MARINE : RETAIL OUTLET'),
        (2712, 'AUTOMOTIVE OR MARINE : REPAIRS - NON AUTOMOTIVE'),
        (2713, 'AUTOMOTIVE OR MARINE : OFFICE BUILDING'),
        (2717, 'AUTOMOTIVE OR MARINE : COMMERCIAL - TOTAL VALUE'),
        (2719, 'AUTOMOTIVE OR MARINE : AUTOMOTIVE OR MARINE'),
        (2729, 'AUTOMOTIVE OR MARINE : MIXED USE - COMMERCIAL'),
        (2732, 'AUTOMOTIVE OR MARINE : LIGHT MFG & FOOD PROCESSING'),
        (2736, 'AUTOMOTIVE OR MARINE : HEAVY IND OR LUMBER YARD'),
        (2737, 'AUTOMOTIVE OR MARINE : WAREHOUSE OR STORAGE'),
        (2739, 'AUTOMOTIVE OR MARINE : MIXED USE - INDUSTRIAL'),
        (2765, 'AUTOMOTIVE OR MARINE : PARKING LOT'),
        (2789, 'AUTOMOTIVE OR MARINE : BACK ASSESSMENT'),
        (2806, 'PARKING LOT/MOBILE HOME PARK : MOBILE HOME'),
        (2807, 'PARKING GARAGE - RESIDENTIAL CONDO'),
        (2809, 'PARKING LOT/MOBILE HOME PARK : MIXED USE - RESIDENTIAL'),
        (2817, 'PARKING LOT/MOBILE HOME PARK : COMMERCIAL - TOTAL VALUE'),
        (2818, 'PARKING LOT/COMMERCIAL CONDO'),
        (2865, 'PARKING LOT/MOBILE HOME PARK : PARKING LOT'),
        (2866, 'PARKING LOT/MOBILE HOME PARK : EXTRA FEA OTHER THAN PARKING'),
        (2881, 'PARKING LOT/MOBILE HOME PARK : VACANT LAND'),
        (2889, 'PARKING LOT/MOBILE HOME PARK : BACK ASSESSMENT'),
        (2911, 'WHOLESALE OUTLET : RETAIL OUTLET'),
        (2914, 'WHOLESALE OUTLET : WHOLESALE OUTLET'),
        (2919, 'WHOLESALE OUTLET : AUTOMOTIVE OR MARINE'),
        (2932, 'WHOLESALE OUTLET : LIGHT MFG & FOOD PROCESSING'),
        (2936, 'WHOLESALE OUTLET : HEAVY IND OR LUMBER YARD'),
        (2989, 'WHOLESALE OUTLET : BACK ASSESSMENT'),
        (3011, 'FLORIST OR GREENHOUSE : RETAIL OUTLET'),
        (3115, 'DRIVE-IN THEATER OR STADIUM : ENTERTAINMENT'),
        (3211, 'ENCLOSED THEATER/AUDITORIUM : RETAIL OUTLET'),
        (3215, 'ENCLOSED THEATER/AUDITORIUM : ENTERTAINMENT'),
        (3219, 'ENCLOSED THEATER/AUDITORIUM : AUTOMOTIVE OR MARINE'),
        (3229, 'ENCLOSED THEATER/AUDITORIUM : MIXED USE - COMMERCIAL'),
        (3241, 'ENCLOSED THEATER/AUDITORIUM : EDUCATIONAL - PRIVATE'),
        (3311, 'NIGHTCLUB LOUNGE OR BAR : RETAIL OUTLET'),
        (3315, 'NIGHTCLUB LOUNGE OR BAR : ENTERTAINMENT'),
        (3319, 'NIGHTCLUB LOUNGE OR BAR : AUTOMOTIVE OR MARINE'),
        (3415, 'ENCLOSED RECEATIONAL ARENA : ENTERTAINMENT'),
        (3442, 'ENCLOSED RECEATIONAL ARENA : CLUB OR HALL - PRIVATE'),
        (3507, 'TOURIST ATTRACTION/EXHIBIT : CONDOMINIUM - RESIDENTIAL'),
        (3515, 'TOURIST ATTRACTION/EXHIBIT : ENTERTAINMENT'),
        (3517, 'TOURIST ATTRACTION/EXHIBIT : COMMERCIAL - TOTAL VALUE'),
        (3542, 'TOURIST ATTRACTION/EXHIBIT : CLUB OR HALL - PRIVATE'),
        (3617, 'CAMP : COMMERCIAL - TOTAL VALUE'),
        (3624, 'CAMP : CAMPSITE'),
        (3632, 'CAMP : LIGHT MFG & FOOD PROCESSING'),
        (3665, 'CAMP : PARKING LOT'),
        (3715, 'RACE TRACK : ENTERTAINMENT'),
        (3815, 'GOLF COURSE OR DRIVING RANGE : ENTERTAINMENT'),
        (3840, 'GOLF COURSE OR DRIVING RANGE : MUNICIPAL'),
        (3848, 'GOLF COURSE OR DRIVING RANGE : BOARD OF PUBLIC INSTRUCTION'),
        (3853, 'GOLF COURSE OR DRIVING RANGE : GOLF COURSE'),
        (3917, 'HOTEL OR MOTEL : COMMERCIAL - TOTAL VALUE'),
        (3918, 'HOTEL OR MOTEL : CONDOMINIUM - COMMERCIAL'),
        (3921, 'HOTEL OR MOTEL : HOTEL'),
        (3922, 'HOTEL OR MOTEL : MOTEL'),
        (3923, 'HOTEL OR MOTEL : CONDOMINIUM - TIMESHARING'),
        (3925, 'HOTEL OR MOTEL : ENTERPRISE ZONE TOTAL VALUE'),
        (3989, 'HOTEL OR MOTEL : BACK ASSESSMENT'),
        (4005, 'VACANT LAND - INDUSTRIAL : CLUSTER HOME'),
        (4007, 'VACANT LAND - INDUSTRIAL : CONDOMINIUM - RESIDENTIAL'),
        (4017, 'VACANT LAND - INDUSTRIAL : COMMERCIAL - TOTAL VALUE'),
        (4018, 'VACANT INDUSTRIAL - CONDO'),
        (4019, 'VACANT LAND - INDUSTRIAL : AUTOMOTIVE OR MARINE'),
        (4025, 'VACANT LAND - INDUSTRIAL : ENTERPRISE ZONE TOTAL VALUE'),
        (4065, 'VACANT LAND - INDUSTRIAL : PARKING LOT'),
        (4066, 'VACANT LAND - INDUSTRIAL : EXTRA FEA OTHER THAN PARKING'),
        (4080, 'VACANT LAND - INDUSTRIAL : VACANT LAND - GOVERNMENTAL'),
        (4081, 'VACANT LAND - INDUSTRIAL : VACANT LAND'),
        (4089, 'VACANT LAND - INDUSTRIAL : BACK ASSESSMENT'),
        (4109, 'LIGHT MANUFACTURING : MIXED USE - RESIDENTIAL'),
        (4111, 'LIGHT MANUFACTURING : RETAIL OUTLET'),
        (4112, 'LIGHT MANUFACTURING : REPAIRS - NON AUTOMOTIVE'),
        (4113, 'LIGHT MANUFACTURING : OFFICE BUILDING'),
        (4114, 'LIGHT MANUFACTURING : WHOLESALE OUTLET'),
        (4118, 'LIGHT MANUFACTURING : CONDOMINIUM - COMMERCIAL'),
        (4119, 'LIGHT MANUFACTURING : AUTOMOTIVE OR MARINE'),
        (4125, 'LIGHT MANUFACTURING : ENTERPRISE ZONE TOTAL VALUE'),
        (4132, 'LIGHT MANUFACTURING : LIGHT MFG & FOOD PROCESSING'),
        (4136, 'LIGHT MANUFACTURING : HEAVY IND OR LUMBER YARD'),
        (4137, 'LIGHT MANUFACTURING : WAREHOUSE OR STORAGE'),
        (4139, 'LIGHT MANUFACTURING : MIXED USE - INDUSTRIAL'),
        (4156, 'LIGHT MANUFACTURING : SCIENTIFIC'),
        (4189, 'LIGHT MANUFACTURING : BACK ASSESSMENT'),
        (4211, 'HEAVY INDUSTRIAL : RETAIL OUTLET'),
        (4214, 'HEAVY INDUSTRIAL : WHOLESALE OUTLET'),
        (4217, 'HEAVY INDUSTRIAL : COMMERCIAL - TOTAL VALUE'),
        (4219, 'HEAVY INDUSTRIAL : AUTOMOTIVE OR MARINE'),
        (4232, 'HEAVY INDUSTRIAL : LIGHT MFG & FOOD PROCESSING'),
        (4234, 'HEAVY INDUSTRIAL : CANNERIES - BOTTLER'),
        (4236, 'HEAVY INDUSTRIAL : HEAVY IND OR LUMBER YARD'),
        (4237, 'HEAVY INDUSTRIAL : WAREHOUSE OR STORAGE'),
        (4239, 'HEAVY INDUSTRIAL : MIXED USE - INDUSTRIAL'),
        (4289, 'HEAVY INDUSTRIAL: BACK ASSESSMENT'),
        (4311, 'LUMBER YARD OR MILL : RETAIL OUTLET'),
        (4332, 'LUMBER YARD OR MILL : LIGHT MFG & FOOD PROCESSING'),
        (4336, 'LUMBER YARD OR MILL : HEAVY IND OR LUMBER YARD'),
        (4337, 'LUMBER YARD OR MILL : WAREHOUSE OR STORAGE'),
        (4432, 'PACKING PLANT : LIGHT MFG & FOOD PROCESSING'),
        (4436, 'PACKING PLANT : HEAVY IND OR LUMBER YARD'),
        (4489, 'PACKING PLANT : BACK ASSESSMENT'),
        (4534, 'CANNERY OR DISTILLERY : CANNERIES - BOTTLER'),
        (4536, 'CANNERY OR DISTILLERY : HEAVY IND OR LUMBER YARD'),
        (4611, 'FOOD PROCESSING : RETAIL OUTLET'),
        (4632, 'FOOD PROCESSING : LIGHT MFG & FOOD PROCESSING'),
        (4636, 'FOOD PROCESSING : HEAVY IND OR LUMBER YARD'),
        (4689, 'FOOD PROCESSING: LIGHT MFG BACK ASSESSMENT'),
        (4714, 'MINERAL PROCESSING : WHOLESALE OUTLET'),
        (4719, 'MINERAL PROCESSING : AUTOMOTIVE OR MARINE'),
        (4731, 'MINERAL PROCESSING : MINERAL PROCESSING'),
        (4734, 'MINERAL PROCESSING : CANNERIES - BOTTLER'),
        (4736, 'MINERAL PROCESSING : HEAVY IND OR LUMBER YARD'),
        (4739, 'MINERAL PROCESSING : MIXED USE - INDUSTRIAL'),
        (4811, 'WAREHOUSE TERMINAL OR STG : RETAIL OUTLET'),
        (4812, 'WAREHOUSE TERMINAL OR STG : REPAIRS - NON AUTOMOTIVE'),
        (4813, 'WAREHOUSE TERMINAL OR STG : OFFICE BUILDING'),
        (4814, 'WAREHOUSE TERMINAL OR STG : WHOLESALE OUTLET'),
        (4815, 'WAREHOUSE TERMINAL OR STG : ENTERTAINMENT'),
        (4818, 'WAREHOUSE TERMINAL OR STG : CONDOMINIUM - COMMERCIAL'),
        (4819, 'WAREHOUSE TERMINAL OR STG : AUTOMOTIVE OR MARINE'),
        (4832, 'WAREHOUSE TERMINAL OR STG : LIGHT MFG & FOOD PROCESSING'),
        (4836, 'WAREHOUSE TERMINAL OR STG : HEAVY IND OR LUMBER YARD'),
        (4837, 'WAREHOUSE TERMINAL OR STG : WAREHOUSE OR STORAGE'),
        (4839, 'WAREHOUSE TERMINAL OR STG : MIXED USE - INDUSTRIAL'),
        (4880, 'WAREHOUSE TERMINAL OR STG : VACANT LAND - GOVERNMENTAL'),
        (4889, 'WAREHOUSE TERMINAL OR STG : BACK ASSESSMENT'),
        (4936, 'OPEN STORAGE : HEAVY IND OR LUMBER YARD'),
        (4937, 'OPEN STORAGE : WAREHOUSE OR STORAGE'),
        (4965, 'OPEN STORAGE : PARKING LOT'),
        (5001, 'IMPR AGRI : RESIDENTIAL - SINGLE FAMILY'),
        (5002, 'IMPR AGRI - NOT HOMESITES : 2 LIVING UNITS'),
        (5003, 'IMPR AGRI - NOT HOMESITES : MULTIFAMILY 3 OR MORE UNITS'),
        (5006, 'IMPR AGRI - NOT HOMESITES : MOBILE HOME'),
        (5009, 'IMPR AGRI - NOT HOMESITES : MIXED USE - RESIDENTIAL'),
        (5011, 'IMPR AGRI - NOT HOMESITES : RETAIL OUTLET'),
        (5013, 'IMPR AGRI - NOT HOMESITES : OFFICE BUILDING'),
        (5014, 'IMPR AGRI - NOT HOMESITES : WHOLESALE OUTLET'),
        (5015, 'IMPR AGRI - NOT HOMESITES : ENTERTAINMENT'),
        (5019, 'IMPR AGRI - NOT HOMESITES : AUTOMOTIVE OR MARINE'),
        (5029, 'IMPR AGRI - NOT HOMESITES : MIXED USE - COMMERCIAL'),
        (5031, 'IMPR AGRI - NOT HOMESITES : MINERAL PROCESSING'),
        (5032, 'IMPR AGRI - NOT HOMESITES : LIGHT MFG & FOOD PROCESSING'),
        (5034, 'IMPR AGRI - NOT HOMESITES : CANNERIES - BOTTLER'),
        (5036, 'IMPR AGRI - NOT HOMESITES : HEAVY IND OR LUMBER YARD'),
        (5037, 'IMPR AGRI - NOT HOMESITES : WAREHOUSE OR STORAGE'),
        (5041, 'IMPR AGRI - NOT HOMESITES : EDUCATIONAL - PRIVATE'),
        (5042, 'IMPR AGRI - NOT HOMESITES : CLUB OR HALL - PRIVATE'),
        (5044, 'IMPR AGRI - NOT HOMESITES : RELIGIOUS'),
        (5047, 'IMPR AGRI - NOT HOMESITES : DADE COUNTY'),
        (5054, 'IMPR AGRI - NOT HOMESITES : CEMETERY'),
        (5063, 'IMPR AGRI - NOT HOMESITES : UTILITY'),
        (5064, 'IMPR AGRI - NOT HOMESITES : RIGHT-OF-WAY'),
        (5065, 'IMPR AGRI - NOT HOMESITES : PARKING LOT'),
        (5066, 'IMPR AGRI - NOT HOMESITES : EXTRA FEA OTHER THAN PARKING'),
        (5069, 'IMPR AGRI : MIXED USE'),
        (5071, 'IMPR AGRI : GROVE OR ORCHARD'),
        (5079, 'IMPR AGRI - NOT HOMESITES : MIXED USE - AGRICULTURAL'),
        (5081, 'IMPR AGRI : VACANT LAND'),
        (5089, 'IMPR AGRI : BACK ASSESSMENT'),
        (5111, 'CROPLAND - SOIL CLASS I : RETAIL OUTLET'),
        (5171, 'CROPLAND - SOIL CLASS I : GROVE OR ORCHARD'),
        (5179, 'CROPLAND - SOIL CLASS I : MIXED USE - AGRICULTURAL'),
        (5181, 'CROPLAND - SOIL CLASS I : VACANT LAND'),
        (5189, 'CROPLAND - SOIL CLASS I : BACK ASSESSMENT'),
        (5319, 'VEG CROPLANDS MIXED/ROTATED : AUTOMOTIVE OR MARINE'),
        (5379, 'VEG CROPLANDS MIXED/ROTATED : MIXED USE - AGRICULTURAL'),
        (5381, 'VEG CROPLANDS MIXED/ROTATED : VACANT LAND'),
        (5389, 'VEG CROPLANDS MIXED/ROTATED : BACK ASSESSMENT'),
        (6001, 'GRAZING LAND - CLASS I : RESIDENTIAL - SINGLE FAMILY'),
        (6081, 'GRAZING LAND - CLASS I : VACANT LAND'),
        (6115, 'IMPROVED PASTURES : ENTERTAINMENT'),
        (6137, 'IMPROVED PASTURES : WAREHOUSE OR STORAGE'),
        (6179, 'IMPROVED PASTURES : MIXED USE - AGRICULTURAL'),
        (6180, 'IMPROVED PASTURES : VACANT LAND - GOVERNMENTAL'),
        (6181, 'IMPROVED PASTURES : VACANT LAND'),
        (6189, 'IMPROVED PASTURES : BACK ASSESSMENT'),
        (6602, 'ORCHARD GROVES CITRUS ETC : 2 LIVING UNITS'),
        (6648, 'ORCHARD GROVES CITRUS ETC : BOARD OF PUBLIC INSTRUCTION'),
        (6666, 'ORCHARD GROVES CITRUS ETC : EXTRA FEA OTHER THAN PARKING'),
        (6671, 'LIME GROVES : GROVE OR ORCHARD'),
        (6679, 'ORCHARD GROVES CITRUS ETC : MIXED USE - AGRICULTURAL'),
        (6681, 'AVOCADO GROVES : VACANT LAND'),
        (6689, 'ORCHARD GROVES CITRUS ETC : BACK ASSESSMENT'),
        (6781, 'CHICKENS : VACANT LAND'),
        (6831, 'DAIRY : MINERAL PROCESSING'),
        (6847, 'DAIRY : DADE COUNTY'),
        (6879, 'DAIRY : MIXED USE - AGRICULTURAL'),
        (6881, 'DAIRY : VACANT LAND'),
        (6909, 'ORNAMENTAL OR MISCELLANEOUS : MIXED USE - RESIDENTIAL'),
        (6966, 'CONTAINER NURSERY ABOVE-GR: EXTRA FEA OTHER THAN PARKING'),
        (6971, 'CONTAINER NURSERY ABOVE-GR : GROVE OR ORCHARD'),
        (6981, 'CONTAINER NURSERY ABOVE-GR : VACANT LAND'),
        (6989, 'TREE NURSERY ORNAMENTAL : BACK ASSESSMENT'),
        (7043, 'VACANT LAND - INSTITUTIONAL : HEALTH CARE'),
        (7044, 'VACANT LAND - INSTITUTIONAL : RELIGIOUS'),
        (7065, 'VACANT LAND - INSTITUTIONAL : PARKING LOT'),
        (7066, 'VACANT LAND - INSTITUTIONAL : EXTRA FEA OTHER THAN PARKING'),
        (7080, 'VACANT LAND - INSTITUTIONAL : VACANT LAND - GOVERNMENTAL'),
        (7081, 'VACANT LAND - INSTITUTIONAL : VACANT LAND'),
        (7101, 'RELIGIOUS - EXEMPT : RESIDENTIAL - SINGLE FAMILY'),
        (7113, 'RELIGIOUS - EXEMPT : OFFICE BUILDING'),
        (7114, 'RELIGIOUS - EXEMPT : WHOLESALE OUTLET'),
        (7125, 'RELIGIOUS - EXEMPT : ENTERPRISE ZONE TOTAL VALUE'),
        (7129, 'RELIGIOUS - EXEMPT : MIXED USE - COMMERCIAL'),
        (7136, 'RELIGIOUS - EXEMPT : HEAVY IND OR LUMBER YARD'),
        (7140, 'RELIGIOUS - EXEMPT : MUNICIPAL'),
        (7141, 'RELIGIOUS - EXEMPT : EDUCATIONAL - PRIVATE'),
        (7142, 'RELIGIOUS - EXEMPT : CLUB OR HALL - PRIVATE'),
        (7144, 'RELIGIOUS - EXEMPT : RELIGIOUS'),
        (7149, 'RELIGIOUS - EXEMPT : MIXED USE - GOVERNMENTAL'),
        (7157, 'RELIGIOUS - EXEMPT : PARSONAGE'),
        (7181, 'RELIGIOUS - EXEMPT : VACANT LAND'),
        (7189, 'RELIGIOUS EXEMPT : BACK ASSESSMENT'),
        (7211, 'EDUCATIONAL/SCIENTIFIC - EX : RETAIL OUTLET'),
        (7241, 'EDUCATIONAL/SCIENTIFIC - EX : EDUCATIONAL - PRIVATE'),
        (7242, 'EDUCATIONAL/SCIENTIFIC - EX : CLUB OR HALL - PRIVATE'),
        (7243, 'EDUCATIONAL/SCIENTIFIC - EX : HEALTH CARE'),
        (7244, 'EDUCATIONAL/SCIENTIFIC - EX : RELIGIOUS'),
        (7256, 'EDUCATIONAL/SCIENTIFIC - EX : SCIENTIFIC'),
        (7280, 'EDUCATIONAL/SCIENTIFIC - EX : VACANT LAND - GOVERNMENTAL'),
        (7281, 'EDUCATIONAL/SCIENTIFIC - EX : VACANT LAND'),
        (7289, 'EDUCATIONAL/SCIENTIFIC - EX : BACK ASSESSMENT'),
        (7313, 'HOSPITAL - PRIVATE : OFFICE BUILDING'),
        (7341, 'HOSPITAL - PRIVATE : EDUCATIONAL - PRIVATE'),
        (7343, 'HOSPITAL - PRIVATE : HEALTH CARE'),
        (7366, 'HOSPITAL - PRIVATE : EXTRA FEA OTHER THAN PARKING'),
        (7413, 'HOME FOR THE AGED : OFFICE BUILDING'),
        (7417, 'HOME FOR THE AGED : COMMERCIAL - TOTAL VALUE'),
        (7440, 'HOME FOR THE AGED : MUNICIPAL'),
        (7443, 'HOME FOR THE AGED : HEALTH CARE'),
        (7455, 'HOME FOR THE AGED : BENEVOLENT'),
        (7503, 'CHARITABLE - EXEMPT : MULTIFAMILY 3 OR MORE UNITS'),
        (7517, 'CHARITABLE - EXEMPT : COMMERCIAL - TOTAL VALUE'),
        (7536, 'CHARITABLE - EXEMPT : HEAVY IND OR LUMBER YARD'),
        (7541, 'CHARITABLE - EXEMPT : EDUCATIONAL - PRIVATE'),
        (7542, 'CHARITABLE - EXEMPT : CLUB OR HALL - PRIVATE'),
        (7543, 'CHARITABLE - EXEMPT : HEALTH CARE'),
        (7544, 'CHARITABLE - EXEMPT : RELIGIOUS'),
        (7545, 'CHARITABLE - EXEMPT : PUBLIC ADMINISTRATION'),
        (7580, 'CHARITABLE - EXEMPT : VACANT LAND - GOVERNMENTAL'),
        (7611, 'BURIAL GROUND OR VAULT : RETAIL OUTLET'),
        (7612, 'BURIAL GROUND OR VAULT : REPAIRS - NON AUTOMOTIVE'),
        (7641, 'BURIAL GROUND OR VAULT : EDUCATIONAL - PRIVATE'),
        (7654, 'BURIAL GROUND OR VAULT : CEMETERY'),
        # (7689
        (7713, 'BENEVOLENT - EXEMPT : OFFICE BUILDING'),
        (7719, 'BENEVOLENT - EXEMPT : AUTOMOTIVE OR MARINE'),
        (7741, 'BENEVOLENT - EXEMPT : EDUCATIONAL - PRIVATE'),
        (7742, 'BENEVOLENT - EXEMPT : CLUB OR HALL - PRIVATE'),
        (7743, 'BENEVOLENT - EXEMPT : HEALTH CARE'),
        (7744, 'BENEVOLENT - EXEMPT : RELIGIOUS'),
        (7749, 'BENEVOLENT - EXEMPT : MIXED USE - GOVERNMENTAL'),
        (7755, 'BENEVOLENT - EXEMPT : BENEVOLENT'),
        (7756, 'BENEVOLENT - EXEMPT : SCIENTIFIC'),
        (7758, 'BENEVOLENT - EXEMPT : YMCA - YWCA'),
        (7781, 'BENEVOLENT - EXEMPT : VACANT LAND'),
        (7803, 'SANITARIUM/CONV OR REST HOME : MULTIFAMILY 3 OR MORE UNITS'),
        (7842, 'SANITARIUM/CONV OR REST HOME : CLUB OR HALL - PRIVATE'),
        (7843, 'SANITARIUM/CONV OR REST HOME : HEALTH CARE'),
        (7944, 'LITERARY - EXEMPT : RELIGIOUS'),
        (7950, 'LITERARY - EXEMPT : CULTURAL - LITERARY'),
        (7965, 'LITERARY - EXEMPT : PARKING LOT'),
        (8040, 'VACANT GOVERNMENTAL : MUNICIPAL'),
        (8047, 'VACANT GOVERNMENTAL : DADE COUNTY'),
        (8048, 'VACANT GOVERNMENTAL : SCHOOL BOARD'),
        (8065, 'VACANT GOVERNMENTAL:PARKING LOT'),
        (8066, 'VACANT GOVERNMENTAL : EXTRA FEA OTHER THAN PARKING'),
        (8080, 'VACANT GOVERNMENTAL : VACANT LAND - GOVERNMENTAL'),
        (8081, 'VACANT GOVERNMENTAL : VACANT LAND'),
        (8085, 'VACANT GOVERNMENTAL : SO FLORIDA WATER MGNT DIST'),
        (8088, 'VACANT GOVERNMENTAL : O/G/M RIGHTS'),
        (8089, 'VACANT GOVERNMENTAL : BACK ASSESSMENT'),
        (8098, 'VACANT GOVERNMENTAL : FEDERAL'),
        (8099, 'VACANT GOVERNMENTAL : STATE'),
        (8198, 'MILITARY : FEDERAL'),
        (8217, 'FOREST/PARK OR REC AREA : COMMERCIAL - TOTAL VALUE'),
        (8240, 'PRIVATE PARK'),
        (8247, 'FOREST/PARK OR REC AREA : DADE COUNTY'),
        (8251, 'PRIVATE PARK : COMMON AREA'),
        (8252, 'FOREST/PARK OR REC AREA : PLAYGROUND'),
        (8265, 'FOREST/PARK OR REC AREA : PARKING LOT'),
        (8280, 'FOREST/PARK OR REC AREA : VACANT LAND - GOVERNMENTAL'),
        (8289, 'FOREST/PARK OR REC AREA: BACK ASSESSMENT'),
        (8299, 'FOREST/PARK OR REC AREA : STATE OF FLORIDA'),
        (8301, 'BOARD OF PUBLIC INSTRUCTION : RESIDENTIAL - SINGLE FAMILY'),
        (8302, 'BOARD OF PUBLIC INSTRUCTION : 2 LIVING UNITS'),
        (8303, 'BOARD OF PUBLIC INSTRUCTION : MULTIFAMILY 3 OR MORE UNITS'),
        (8340, 'BOARD OF PUBLIC INSTRUCTION : MUNICIPAL'),
        (8341, 'BOARD OF PUBLIC INSTRUCTION : EDUCATIONAL - PRIVATE'),
        (8343, 'BOARD OF PUBLIC INSTRUCTION : HEALTH CARE'),
        (8347, 'BOARD OF PUBLIC INSTRUCTION : DADE COUNTY'),
        (8348, 'BOARD OF PUBLIC INSTRUCTION : BOARD OF PUBLIC INSTRUCTION'),
        (8365, 'BOARD OF PUBLIC INSTRUCTION : PARKING LOT'),
        (8366, 'BOARD OF PUBLIC INSTRUCTION : EXTRA FEA OTHER THAN PARKING'),
        (8380, 'BOARD OF PUBLIC INSTRUCTION : VACANT LAND - GOVERNMENTAL'),
        (8381, 'BOARD OF PUBLIC INSTRUCTION : VACANT LAND'),
        (8418, 'UNIVERSITY OR COLLEGE : CONDOMINIUM - COMMERCIAL'),
        (8441, 'UNIVERSITY OR COLLEGE : EDUCATIONAL - PRIVATE'),
        (8480, 'UNIVERSITY OR COLLEGE : VACANT LAND - GOVERNMENTAL'),
        (8499, 'UNIVERSITY OR COLLEGE : STATE OF FLORIDA'),
        (8543, 'HOSPITAL - GOVERNMENTAL : HEALTH CARE'),
        (8547, 'HOSPITAL - GOVERNMENTAL : DADE COUNTY'),
        (8589, 'HOSPITAL - GOVERNMENTAL : BACK ASSESSMENT'),
        (8601, 'COUNTY : RESIDENTIAL - SINGLE FAMILY'),
        (8602, 'COUNTY : 2 LIVING UNITS'),
        (8603, 'COUNTY : MULTIFAMILY 3 OR MORE UNITS'),
        (8604, 'COUNTY : RESIDENTIAL - TOTAL VALUE'),
        (8605, 'COUNTY : CLUSTER HOME'),
        (8607, 'COUNTY : CONDOMINIUM - RESIDENTIAL'),
        (8610, 'COUNTY : TOWNHOUSE'),
        (8611, 'COUNTY : RETAIL OUTLET'),
        (8613, 'COUNTY : OFFICE BUILDING'),
        (8617, 'COUNTY : COMMERCIAL - TOTAL VALUE'),
        (8619, 'COUNTY : AUTOMOTIVE OR MARINE'),
        (8626, 'COUNTY : SERVICE STATION - AUTOMOTIVE'),
        (8636, 'COUNTY : HEAVY IND OR LUMBER YARD'),
        (8637, 'COUNTY : WAREHOUSE OR STORAGE'),
        (8640, 'COUNTY : MUNICIPAL'),
        (8642, 'COUNTY : CLUB OR HALL - PRIVATE'),
        (8643, 'COUNTY : HEALTH CARE'),
        (8645, 'COUNTY : PUBLIC ADMINISTRATION'),
        (8646, 'COUNTY : PENAL INSTITUTION'),
        (8647, 'COUNTY : DADE COUNTY'),
        (8648, 'COUNTY : BOARD OF PUBLIC INSTRUCTION'),
        (8651, 'COUNTY : COMMON AREA'),
        (8663, 'COUNTY : UTILITY'),
        (8666, 'COUNTY : EXTRA FEA OTHER THAN PARKING'),
        (8680, 'COUNTY : VACANT LAND - GOVERNMENTAL'),
        (8681, 'COUNTY : VACANT LAND'),
        (8682, 'COUNTY : GLADE'),
        (8686, 'COUNTY : TRUSTEE II FUND'),
        (8698, 'COUNTY : FEDERAL'),
        (8713, 'STATE : OFFICE BUILDING'),
        (8731, 'STATE : MINERAL PROCESSING'),
        (8747, 'STATE : DADE COUNTY'),
        (8762, 'STATE : RAILROAD ASSESSMENT'),
        (8765, 'STATE : PARKING LOT'),
        (8780, 'STATE : VACANT LAND - GOVERNMENTAL'),
        (8781, 'STATE : VACANT LAND'),
        (8785, 'STATE : SO FLORIDA WATER MGMT DIST'),
        (8786, 'STATE : TRUSTEE II FUND'),
        (8798, 'STATE : FEDERAL'),
        (8799, 'STATE : STATE OF FLORIDA'),
        (8801, 'FEDERAL : RESIDENTIAL - SINGLE FAMILY'),
        (8807, 'FEDERAL : CONDOMINIUM - RESIDENTIAL'),
        (8809, 'FEDERAL : MIXED USE - RESIDENTIAL'),
        (8813, 'FEDERAL : OFFICE BUILDING'),
        (8817, 'FEDERAL : COMMERCIAL - TOTAL VALUE'),
        (8818, 'FEDERAL : CONDOMINIUM - COMMERCIAL'),
        (8845, 'FEDERAL : PUBLIC ADMINISTRATION'),
        (8847, 'FEDERAL : DADE COUNTY'),
        (8848, 'FEDERAL : BOARD OF PUBLIC INSTRUCTION'),
        (8866, 'FEDERAL : EXTRA FEA OTHER THAN PARKING'),
        (8880, 'FEDERAL : VACANT LAND - GOVERNMENTAL'),
        (8881, 'FEDERAL : VACANT LAND'),
        (8889, 'FEDERAL : BACK ASSESSMENT'),
        (8898, 'FEDERAL : FEDERAL'),
        (8899, 'FEDERAL : STATE OF FLORIDA'),
        (8903, 'MUNICIPAL : MULTIFAMILY 3 OR MORE UNITS'),
        (8907, 'MUNICIPAL : CONDOMINIUM - RESIDENTIAL'),
        (8910, 'MUNICIPAL : TOWNHOUSE'),
        (8911, 'MUNICIPAL : RETAIL OUTLET'),
        (8915, 'MUNICIPAL : ENTERTAINMENT'),
        (8917, 'MUNICIPAL : COMMERCIAL - TOTAL VALUE'),
        (8918, 'MUNICIPAL : CONDOMINIUM - COMMERCIAL'),
        (8919, 'MUNICIPAL : AUTOMOTIVE OR MARINE'),
        (8940, 'MUNICIPAL : MUNICIPAL'),
        (8942, 'MUNICIPAL : CLUB OR HALL - PRIVATE'),
        (8947, 'MUNICIPAL : DADE COUNTY'),
        (8949, 'MUNICIPAL : MIXED USE - GOVERNMENTAL'),
        (8950, 'MUNICIPAL : CULTURAL - LITERARY'),
        (8965, 'MUNICIPAL : PARKING LOT'),
        (8966, 'MUNICIPAL : EXTRA FEA OTHER THAN PARKING'),
        (8980, 'MUNICIPAL : VACANT LAND - GOVERNMENTAL'),
        (8981, 'MUNICIPAL : VACANT LAND'),
        (8986, 'MUNICIPAL : TRUSTEE II FUND'),
        (9001, 'LEASEHOLD INTEREST : RESIDENTIAL - SINGLE FAMILY'),
        (9009, 'LEASEHOLD INTEREST : MIXED USE - RESIDENTIAL'),
        (9017, 'LEASEHOLD INTEREST : COMMERCIAL - TOTAL VALUE'),
        (9018, 'LEASEHOLD INTEREST : CONDOMINIUM - COMMERCIAL'),
        (9019, 'LEASEHOLD INTEREST : AUTOMOTIVE OR MARINE'),
        (9025, 'LEASEHOLD INTEREST : ENTERPRISE ZONE TOTAL VALUE'),
        (9026, 'LEASEHOLD INTEREST : SERVICE STATION - AUTOMOTIVE'),
        (9040, 'LEASEHOLD INTEREST : MUNICIPAL'),
        (9080, 'LEASEHOLD INTEREST : VACANT LAND - GOVERNMENTAL'),
        (9081, 'LEASEHOLD INTEREST : VACANT LAND'),
        (9111, 'UTILITY : RETAIL OUTLET'),
        (9113, 'UTILITY : OFFICE BUILDING'),
        (9119, 'UTILITY : AUTOMOTIVE OR MARINE'),
        (9162, 'UTILITY : RAILROAD ASSESSMENT'),
        (9163, 'UTILITY : UTILITY'),
        (9166, 'UTILITY : EXTRA FEA OTHER THAN PARKING'),
        (9189, 'UTILITY: BACK ASSESSMENT'),
        (9231, 'MINING - OIL GAS OR MINERAL : MINERAL PROCESSING'),
        (9288, 'MINING - OIL GAS OR MINERAL : O/G/M RIGHTS'),
        (9380, 'OIL GAS OR MINERAL RTS : VACANT LAND - GOVERNMENTAL'),
        (9388, 'OIL GAS OR MINERAL RTS : O/G/M RIGHTS'),
        (9464, 'RIGHT-OF-WAY : RIGHT-OF-WAY'),
        (9551, 'RIVER LAKE OR SUBMERGED LAND : COMMON AREA'),
        (9580, 'RIVER LAKE OR SUBMERGED LAND : VACANT LAND - GOVERNMENTAL'),
        (9581, 'RIVER LAKE OR SUBMERGED LAND : VACANT LAND'),
        (9585, 'RIVER LAKE OR SUBMERGED LAND : SO FLORIDA WATER MGMT DIST'),
        (9591, 'RIVER LAKE OR SUBMERGED LAND : RIVER'),
        (9592, 'RIVER LAKE OR SUBMERGED LAND : LAKE'),
        (9593, 'RIVER LAKE OR SUBMERGED LAND : SUBMERGED LAND'),
        (9701, 'IMP EEL'),
        (9734, 'RECREATIONAL OR ENDANGERED : CANNERIES - BOTTLER'),
        (9739, 'RECREATIONAL OR ENDANGERED : MIXED USE - INDUSTRIAL'),
        (9743, 'RECREATIONAL OR ENDANGERED : HEALTH CARE'),
        (9749, 'RECREATIONAL OR ENDANGERED : MIXED USE - GOVERNMENTAL'),
        (9751, 'PVT PARK -REC AREA -ROADWAY : COMMON AREA'),
        (9755, 'RECREATIONAL OR ENDANGERED : BENEVOLENT'),
        (9762, 'RECREATIONAL OR ENDANGERED : RAILROAD ASSESSMENT'),
        (9763, 'RECREATIONAL OR ENDANGERED : UTILITY'),
        (9784, 'RECREATIONAL OR ENDANGERED : RECREATIONAL OR ENDANGERED'),
        (9862, 'CENTRALLY ASSESSED : RAILROAD ASSESSMENT'),
        (9901, 'XF ON VACANT AC'),
        (9910, 'ACREAGE NOT CLASSIFIED AG : TOWNHOUSE'),
        (9913, 'ACREAGE NOT CLASSIFIED AG : OFFICE BUILDING'),
        (9917, 'ACREAGE NOT CLASSIFIED AG : COMMERCIAL - TOTAL VALUE'),
        (9931, 'ACREAGE NOT CLASSIFIED AG : MINERAL PROCESSING'),
        (9937, 'ACREAGE NOT CLASSIFIED : WAREHOUSE OR STORAGE'),
        (9940, 'ACREAGE NOT CLASSIFIED AG : MUNICIPAL'),
        (9944, 'ACREAGE NOT CLASSIFIED AG : RELIGIOUS'),
        (9951, 'ACREAGE NOT CLASSIFIED AG : COMMON AREA'),
        (9955, 'ACREAGE NOT CLASSIFIED AG : BENEVOLENT'),
        (9965, 'ACREAGE NOT CLASSIFIED AG : PARKING LOT'),
        (9966, 'ACREAGE NOT CLASSIFIED AG : EXTRA FEA OTHER THAN PARKING'),
        (9979, 'ACREAGE NOT CLASSIFIED AG : MIXED USE - AGRICULTURAL'),
        (9980, 'ACREAGE NOT CLASSIFIED AG : VACANT LAND - GOVERNMENTAL'),
        (9981, 'ACREAGE NOT CLASSIFIED AG : VACANT LAND'),
        (9984, 'ACREAGE NOT CLASSIFIED AG : RECREATIONAL OR ENDANGERED'),
        (9985, 'ACREAGE NOT CLASSIFIED AG : SO FLORIDA WATER MGMT DIST'),
        (9989, 'ACREAGE NOT CLASSIFIED AG : BACK ASSESSMENT'),
        (9990, 'ACREAGE NOT CLASSIFIED AG : LAND AVAILABLE FOR TAXES')
    ])


PROPERTY_CLASS_DESCRIPTION_MAP = {
    'suffolk': OrderedDict([]),
    'nassau': OrderedDict([]),
    'broward': get_broward_property_code_descriptions(),
    'miamidade': get_miamidade_property_code_descriptions(),
    'palmbeach': OrderedDict([])
}
