"""create case_tag table

Revision ID: 00276e4641c3
Revises: 1c7c3f3819da
Create Date: 2020-05-02 17:07:14.834958

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '00276e4641c3'
down_revision = '1c7c3f3819da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_tag')
    # ### end Alembic commands ###
