"""case_property relationships

Revision ID: 00563a72776c
Revises: 86b07e0ce907
Create Date: 2020-04-18 23:05:44.235940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00563a72776c'
down_revision = '86b07e0ce907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_assessment', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_CaseAssessment_case_property_id', 'case_assessment', 'case_property', ['property_id'], ['id']
    )
    op.add_column('case_property', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_constraint('case_property_case_client_id_fkey', 'case_property', type_='foreignkey')
    op.create_foreign_key('fk_CaseProperty_case_client_id', 'case_property', 'case_client', ['client_id'], ['id'])
    op.drop_column('case_property', 'case_client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property', sa.Column('case_client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_CaseProperty_case_client_id', 'case_property', type_='foreignkey')
    op.create_foreign_key(
        'case_property_case_client_id_fkey', 'case_property', 'case_client', ['case_client_id'], ['id']
    )
    op.drop_column('case_property', 'client_id')
    op.drop_constraint('fk_CaseAssessment_case_property_id', 'case_assessment', type_='foreignkey')
    op.drop_column('case_assessment', 'property_id')
    # ### end Alembic commands ###
