"""added time_adjustments table

Revision ID: 01194cbd308d
Revises: 489368875a1f
Create Date: 2020-02-06 01:40:50.697016

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '01194cbd308d'
down_revision = '489368875a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_adjustments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('county', sa.String(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('month', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_adjustments')
    # ### end Alembic commands ###
