"""combined index at property table

Revision ID: 018e96ab4dee
Revises: cc230cd147b3
Create Date: 2020-04-01 16:24:20.378206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018e96ab4dee'
down_revision = 'cc230cd147b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###_
    op.execute('''
    drop index ix_property_school_district;

    create index ix_property_combined
        on property (school_district, latitude, longitude, lot_size, gla_sqft, property_class, county);
    
    drop index ix_property_apn;
    
    drop index ix_property_county;
    
    drop index property_latitude_index;
    
    drop index property_longitude_index;
    

    
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
