"""add assesment_stage to property

Revision ID: 0414899f33d9
Revises: b26eca0e588b
Create Date: 2020-07-16 18:33:50.356038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0414899f33d9'
down_revision = 'b26eca0e588b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('property', sa.Column('assessment_stage', sa.Integer(), nullable=True))
    # op.add_column('property_original', sa.Column('assessment_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('property_original', 'assessment_stage')
    # op.drop_column('property', 'assessment_stage')
    # ### end Alembic commands ###
    pass
