"""fix property indexes creation

Revision ID: 04aaf0b4c2cf
Revises: 3479a7c6f0b9
Create Date: 2020-05-02 02:36:17.310867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aaf0b4c2cf'
down_revision = '3479a7c6f0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_property_address', table_name='property')
    op.drop_index('ix_property_block', table_name='property')
    op.drop_index('ix_property_combined', table_name='property')
    op.drop_index('ix_property_lot', table_name='property')
    op.drop_index('ix_property_print_key', table_name='property')
    op.drop_index('ix_property_section', table_name='property')
    op.drop_index('ix_property_undefined_field', table_name='property')
    op.create_index('ix_property_address', 'property_original', ['address'], unique=False)
    op.create_index('ix_property_apn', 'property_original', ['apn'], unique=False)
    op.create_index('ix_property_block', 'property_original', ['block'], unique=False)
    op.create_index('ix_property_county', 'property_original', ['county'], unique=False)
    op.create_index('ix_property_lot', 'property_original', ['lot'], unique=False)
    op.create_index('ix_property_number', 'property_original', ['number'], unique=False)
    op.create_index('ix_property_print_key', 'property_original', ['print_key'], unique=False)
    op.create_index('ix_property_school_district', 'property_original', ['school_district'], unique=False)
    op.create_index('ix_property_section', 'property_original', ['section'], unique=False)
    op.create_index('ix_property_state', 'property_original', ['state'], unique=False)
    op.create_index('ix_property_street', 'property_original', ['street'], unique=False)
    op.create_index('ix_property_town', 'property_original', ['town'], unique=False)
    op.create_index('ix_property_undefined_field', 'property_original', ['undefined_field'], unique=False)
    op.create_index('ix_property_village', 'property_original', ['village'], unique=False)
    op.create_index('ix_property_zip', 'property_original', ['zip'], unique=False)
    op.drop_index('idx_property_original_geo', table_name='property_original')
    op.drop_index('ix_property_original_address', table_name='property_original')
    op.drop_index('ix_property_original_apn', table_name='property_original')
    op.drop_index('ix_property_original_block', table_name='property_original')
    op.drop_index('ix_property_original_county', table_name='property_original')
    op.drop_index('ix_property_original_lot', table_name='property_original')
    op.drop_index('ix_property_original_number', table_name='property_original')
    op.drop_index('ix_property_original_print_key', table_name='property_original')
    op.drop_index('ix_property_original_school_district', table_name='property_original')
    op.drop_index('ix_property_original_section', table_name='property_original')
    op.drop_index('ix_property_original_state', table_name='property_original')
    op.drop_index('ix_property_original_street', table_name='property_original')
    op.drop_index('ix_property_original_town', table_name='property_original')
    op.drop_index('ix_property_original_undefined_field', table_name='property_original')
    op.drop_index('ix_property_original_village', table_name='property_original')
    op.drop_index('ix_property_original_zip', table_name='property_original')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_property_original_zip', 'property_original', ['zip'], unique=False)
    op.create_index('ix_property_original_village', 'property_original', ['village'], unique=False)
    op.create_index('ix_property_original_undefined_field', 'property_original', ['undefined_field'], unique=False)
    op.create_index('ix_property_original_town', 'property_original', ['town'], unique=False)
    op.create_index('ix_property_original_street', 'property_original', ['street'], unique=False)
    op.create_index('ix_property_original_state', 'property_original', ['state'], unique=False)
    op.create_index('ix_property_original_section', 'property_original', ['section'], unique=False)
    op.create_index('ix_property_original_school_district', 'property_original', ['school_district'], unique=False)
    op.create_index('ix_property_original_print_key', 'property_original', ['print_key'], unique=False)
    op.create_index('ix_property_original_number', 'property_original', ['number'], unique=False)
    op.create_index('ix_property_original_lot', 'property_original', ['lot'], unique=False)
    op.create_index('ix_property_original_county', 'property_original', ['county'], unique=False)
    op.create_index('ix_property_original_block', 'property_original', ['block'], unique=False)
    op.create_index('ix_property_original_apn', 'property_original', ['apn'], unique=False)
    op.create_index('ix_property_original_address', 'property_original', ['address'], unique=False)
    op.create_index('idx_property_original_geo', 'property_original', ['geo'], unique=False)
    op.drop_index('ix_property_zip', table_name='property_original')
    op.drop_index('ix_property_village', table_name='property_original')
    op.drop_index('ix_property_undefined_field', table_name='property_original')
    op.drop_index('ix_property_town', table_name='property_original')
    op.drop_index('ix_property_street', table_name='property_original')
    op.drop_index('ix_property_state', table_name='property_original')
    op.drop_index('ix_property_section', table_name='property_original')
    op.drop_index('ix_property_school_district', table_name='property_original')
    op.drop_index('ix_property_print_key', table_name='property_original')
    op.drop_index('ix_property_number', table_name='property_original')
    op.drop_index('ix_property_lot', table_name='property_original')
    op.drop_index('ix_property_county', table_name='property_original')
    op.drop_index('ix_property_block', table_name='property_original')
    op.drop_index('ix_property_apn', table_name='property_original')
    op.drop_index('ix_property_address', table_name='property_original')
    op.create_index('ix_property_undefined_field', 'property', ['undefined_field'], unique=False)
    op.create_index('ix_property_section', 'property', ['section'], unique=False)
    op.create_index('ix_property_print_key', 'property', ['print_key'], unique=False)
    op.create_index('ix_property_lot', 'property', ['lot'], unique=False)
    op.create_index('ix_property_combined', 'property', ['county', 'geo', 'gla_sqft', 'lot_size'], unique=False)
    op.create_index('ix_property_block', 'property', ['block'], unique=False)
    op.create_index('ix_property_address', 'property', ['address'], unique=False)
    # ### end Alembic commands ###
