"""CmaTask modification

Revision ID: 06fb66b640af
Revises: 37228d4529e8
Create Date: 2020-01-13 15:51:42.302568

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '06fb66b640af'
down_revision = '37228d4529e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cma_result_task_id_fkey', 'cma_result', type_='foreignkey')
    op.alter_column('cma_result', 'task_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=False)
    op.add_column('cma_task', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('cma_task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('cma_task', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String())
    op.create_foreign_key('cma_task_user_id_fkey', 'cma_task', 'users', ['user_id'], ['id'])
    op.create_foreign_key('cma_result_task_id_fkey', 'cma_result', 'cma_task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cma_task_user_id_fkey', 'cma_task', type_='foreignkey')
    op.drop_constraint('cma_result_task_id_fkey', 'cma_result', type_='foreignkey')

    op.execute('''
    alter table cma_task alter column id type int using id::int;
    ''')
    # op.alter_column('cma_task', 'id',
    #                 existing_type=sa.String(),
    #                 type_=sa.INTEGER())
    op.drop_column('cma_task', 'user_id')
    op.drop_column('cma_task', 'complete')
    # op.alter_column('cma_result', 'task_id',
    #                 existing_type=sa.String(),
    #                 type_=sa.INTEGER(),
    #                 existing_nullable=False)

    op.execute('''
    alter table cma_result alter column task_id type int using task_id::int;
    ''')
    op.create_foreign_key('cma_result_task_id_fkey', 'cma_result', 'cma_task', ['task_id'], ['id'])

    # ### end Alembic commands ###
