"""dropping road rules

Revision ID: 0780e45d9536
Revises: ce4858e27107
Create Date: 2020-07-09 01:28:26.427244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0780e45d9536'
down_revision = 'ce4858e27107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'road_obsolescence_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules',
                  sa.Column('road_obsolescence_rules', postgresql.ARRAY(sa.NUMERIC(precision=6, scale=3)),
                            autoincrement=False, nullable=True))
    # ### end Alembic commands ###
