"""add condo_view_floor to properties_rules

Revision ID: 0835b43b1795
Revises: fcac39f322f4
Create Date: 2021-01-15 22:44:15.616936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0835b43b1795'
down_revision = 'fcac39f322f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_original', sa.Column('condo_view_floor', sa.String(), nullable=True))
    op.add_column('properties_rules', sa.Column('condo_view_floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'condo_view_floor')
    op.drop_column('properties_rules', 'condo_view_floor')
    # ### end Alembic commands ###
