"""add application_id foreign key to case_note table

Revision ID: 089c5952f166
Revises: 51be14c3dfec
Create Date: 2020-05-15 00:37:22.277474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089c5952f166'
down_revision = '51be14c3dfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('application_id', sa.Integer(), nullable=True))
    op.add_column('case_note', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_CaseNote_case_note_type_id', 'case_note', type_='foreignkey')
    op.create_foreign_key('fk_CaseNote_case_note_type_id', 'case_note', 'case_note_type', ['type_id'], ['id'])
    op.create_foreign_key('fk_CaseNote_case_application_id', 'case_note', 'case_application', ['application_id'],
                          ['id'], onupdate='CASCADE')
    op.drop_column('case_note', 'note_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('note_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_CaseNote_case_application_id', 'case_note', type_='foreignkey')
    op.drop_constraint('fk_CaseNote_case_note_type_id', 'case_note', type_='foreignkey')
    op.create_foreign_key('fk_CaseNote_case_note_type_id', 'case_note', 'case_note_type', ['note_type_id'], ['id'])
    op.drop_column('case_note', 'type_id')
    op.drop_column('case_note', 'application_id')
    # ### end Alembic commands ###
