"""add subdivision to property table

Revision ID: 097089ecc4eb
Revises: cba9e185d319
Create Date: 2020-09-29 21:54:56.619265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097089ecc4eb'
down_revision = 'cba9e185d319'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('property', sa.Column('subdivision', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('subdivision', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'subdivision')
    op.drop_column('property', 'subdivision')
    # ### end Alembic commands ###
