"""add changed_status_at to application

Revision ID: 0a22fbe2d57f
Revises: ad12470578db
Create Date: 2020-07-27 16:44:22.473881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a22fbe2d57f'
down_revision = 'ad12470578db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('changed_status_at', sa.DateTime(), server_default=sa.text('now()'),
                                                nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'changed_status_at')
    # ### end Alembic commands ###
