"""update unique constraints in properties_rules table

Revision ID: 0b21008389c4
Revises: cb0869951b48
Create Date: 2020-06-17 19:28:07.567245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b21008389c4'
down_revision = 'cb0869951b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_properties_rules', 'properties_rules', ['county', 'town', 'village', 'year'])
    op.drop_constraint('area_composite', 'properties_rules', type_='unique')
    op.drop_index('ix_properties_rules_county_town_year', table_name='properties_rules')
    op.drop_index('ix_properties_rules_county_year', table_name='properties_rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_rules_county_year', 'properties_rules', ['county', 'year'], unique=True)
    op.create_index('ix_properties_rules_county_town_year', 'properties_rules', ['county', 'town', 'year'], unique=True)
    op.create_unique_constraint('area_composite', 'properties_rules', ['county', 'town', 'village'])
    op.drop_constraint('uc_properties_rules', 'properties_rules', type_='unique')
    # ### end Alembic commands ###
