"""update user uniquer constraints in users table

Revision ID: 0ca96f9423f7
Revises: ce3f5f379938
Create Date: 2020-06-11 20:46:38.132908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca96f9423f7'
down_revision = 'ce3f5f379938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_users_username', 'users', ['username'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint('uc_users_username', 'users', type_='unique')
    # ### end Alembic commands ###
