"""added building_code and data_composite to property table

Revision ID: 0ef91fee4cda
Revises: 758e5872ce57
Create Date: 2020-01-14 17:57:12.235717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ef91fee4cda'
down_revision = '758e5872ce57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('building_code', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('data_composite', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'data_composite')
    op.drop_column('property', 'building_code')
    # ### end Alembic commands ###
