"""add signature_updated_at to application

Revision ID: 0f809802ce0c
Revises: 39f29588a777
Create Date: 2020-08-19 13:13:36.868890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f809802ce0c'
down_revision = '39f29588a777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('signature_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'signature_updated_at')
    # ### end Alembic commands ###
