"""add evidence file to single cma workup table

Revision ID: 0fc891b5a7ee
Revises: 6e094e13f1b0
Create Date: 2020-10-06 16:00:09.120678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fc891b5a7ee'
down_revision = '6e094e13f1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('evidence_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_single_cma_workups_evidence_file_id', 'single_sma_workups', 'files',
                          ['evidence_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_single_cma_workups_evidence_file_id', 'single_sma_workups', type_='foreignkey')
    op.drop_column('single_sma_workups', 'evidence_file_id')
    # ### end Alembic commands ###
