"""geo to property

Revision ID: 103f17f8136b
Revises: 92001734fb43
Create Date: 2020-04-09 16:05:56.848370

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '103f17f8136b'
down_revision = '92001734fb43'
branch_labels = None
depends_on = None


def upgrade():

    op.execute(
        '''
        create extension postgis;
        '''
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('geo', Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('property_overridden', sa.Column('geo', Geometry(geometry_type='POINT'), nullable=True))

    op.execute('''
    update property
    set geo = ST_Point(longitude, latitude)
    where longitude notnull and latitude notnull;
    ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_overridden', 'geo')
    op.drop_column('property', 'geo')

    op.execute(
        '''
        drop extension postgis;
        '''
    )

    # ### end Alembic commands ###
