"""add case_company_serving table

Revision ID: 106c47edaf6e
Revises: 1612a2543f8a
Create Date: 2020-04-17 23:07:12.901607

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '106c47edaf6e'
down_revision = '1612a2543f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_company_serving',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('company_name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_client', sa.Column('company_serving_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_CaseClient_case_company_serving_id', 'case_client', 'case_company_serving', ['company_serving_id'], ['id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseClient_case_company_serving_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'company_serving_id')
    op.drop_table('case_company_serving')
    # ### end Alembic commands ###
