"""application-client mixin update

Revision ID: 1177fa0fe28e
Revises: fa1c31470bcd
Create Date: 2020-07-23 22:37:33.369578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1177fa0fe28e'
down_revision = 'fa1c31470bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_application_payment_status_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_case_application_payment_type_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_Application_payment_type_id', 'case_application', 'case_payment_type',
                          ['payment_type_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_Application_payment_status_id', 'case_application', 'case_payment_status',
                          ['payment_status_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('fk_case_client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_constraint('fk_case_client_payment_status_id', 'case_client', type_='foreignkey')
    op.create_foreign_key('fk_Client_payment_status_id', 'case_client', 'case_payment_status', ['payment_status_id'],
                          ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_Client_payment_type_id', 'case_client', 'case_payment_type', ['payment_type_id'],
                          ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_constraint('fk_Client_payment_status_id', 'case_client', type_='foreignkey')
    op.create_foreign_key('fk_case_client_payment_status_id', 'case_client', 'case_payment_status',
                          ['payment_status_id'], ['id'])
    op.create_foreign_key('fk_case_client_payment_type_id', 'case_client', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    op.drop_constraint('fk_Application_payment_status_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_Application_payment_type_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_case_application_payment_type_id', 'case_application', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    op.create_foreign_key('fk_case_application_payment_status_id', 'case_application', 'case_payment_status',
                          ['payment_status_id'], ['id'])
    # ### end Alembic commands ###
