"""assessment ratio adjust

Revision ID: 11f206cffda6
Revises: 73aa57b031f8
Create Date: 2019-12-25 22:06:41.629276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f206cffda6'
down_revision = '73aa57b031f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_ratio', 'selected')
    op.drop_column('assessment_ratio', 'town_code')
    op.drop_column('assessment_ratio', 'level')
    op.drop_column('assessment_ratio', 'town_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_ratio', sa.Column('town_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assessment_ratio', sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assessment_ratio', sa.Column('town_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assessment_ratio', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
