"""vipe case data

Revision ID: 12e83ddfb0c7
Revises: fd09c0831f03
Create Date: 2020-08-01 20:21:01.641402

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '12e83ddfb0c7'
down_revision = 'fd09c0831f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('''
    # TRUNCATE TABLE case_property CASCADE;
    # TRUNCATE TABLE case_note CASCADE;
    # TRUNCATE TABLE case_email CASCADE;
    # TRUNCATE TABLE case_client_tag CASCADE;
    # TRUNCATE TABLE case_client CASCADE;
    # TRUNCATE TABLE case_billing CASCADE;
    # TRUNCATE TABLE case_application CASCADE;
    # ''')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
