"""set condo_view_floor for broward in properties_rules

Revision ID: 1331c419fb80
Revises: 0835b43b1795
Create Date: 2021-01-15 23:23:57.679833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1331c419fb80'
down_revision = '0835b43b1795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE properties_rules
        SET condo_view_floor = 1
        WHERE id=43
        AND county = 'broward';
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
