"""minor update, remove owner_state

Revision ID: 137eb853cab3
Revises: 34d2ca77eb48
Create Date: 2020-06-02 15:20:11.592622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137eb853cab3'
down_revision = '34d2ca77eb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('owner', 'owner_state')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_property_original_geo', 'property_original', ['geo'], unique=False)
    pass
    # ### end Alembic commands ###
