"""latitude and longitude index on property table

Revision ID: 14a80a230bc7
Revises: 06181b601925
Create Date: 2020-03-31 15:15:08.144037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a80a230bc7'
down_revision = '06181b601925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('''
    create index property_latitude_index
	    on property (latitude);

    create index property_longitude_index
        on property (longitude);
    ''')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    
    drop index property_latitude_index;
    drop index property_longitude_index;

    ''')

    # ### end Alembic commands ###
