"""roads and road obsolescences

Revision ID: 159eabb4730b
Revises: d50a9f0e84e3
Create Date: 2020-07-03 04:03:02.326567

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '159eabb4730b'
down_revision = 'd50a9f0e84e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('osm_id', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326),
                              nullable=False),
                    sa.Column('county', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('road_obsolescences',
                    sa.Column('affected_property_id', sa.Integer(), nullable=False),
                    sa.Column('road_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['affected_property_id'], ['property.id'], ),
                    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
                    sa.PrimaryKeyConstraint('affected_property_id', 'road_id')
                    )
    op.execute('''
    CREATE TABLE helper.scanned_roads
        (
            id          serial NOT NULL
                CONSTRAINT scanned_roads_pk
                    PRIMARY KEY,
            road_id integer
        );
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_obsolescences')
    op.drop_table('roads')
    # ### end Alembic commands ###
