"""move company, payment type to case_property

Revision ID: 1644fb2c8211
Revises: c7c0b1038251
Create Date: 2020-05-29 23:03:44.883648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1644fb2c8211'
down_revision = 'c7c0b1038251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_client_company_id', 'case_client', type_='foreignkey')
    op.drop_constraint('fk_case_client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'initials')
    op.drop_column('case_client', 'payment_type_id')
    op.drop_column('case_client', 'company_id')
    op.add_column('case_property', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('case_property', sa.Column('payment_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_case_property_payment_type_id', 'case_property', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    op.create_foreign_key('fk_case_property_company_id', 'case_property', 'case_company_serving',
                          ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_property_company_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_case_property_payment_type_id', 'case_property', type_='foreignkey')
    op.drop_column('case_property', 'payment_type_id')
    op.drop_column('case_property', 'company_id')
    op.add_column('case_client', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('initials', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_case_client_payment_type_id', 'case_client', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    op.create_foreign_key('fk_case_client_company_id', 'case_client', 'case_company_serving', ['company_id'], ['id'])
    # ### end Alembic commands ###
