"""application-case_property mixin

Revision ID: 168bb727c797
Revises: 1177fa0fe28e
Create Date: 2020-07-23 23:30:35.817251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '168bb727c797'
down_revision = '1177fa0fe28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_assessment')
    op.drop_constraint('fk_case_application_property_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_case_application_company_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_Application_company_id', 'case_application', 'case_company_serving', ['company_id'],
                          ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_Application_property_id', 'case_application', 'property', ['property_id'], ['id'],
                          onupdate='CASCADE')
    op.drop_constraint('fk_case_property_property_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_case_property_company_id', 'case_property', type_='foreignkey')
    op.create_foreign_key('fk_CaseProperty_company_id', 'case_property', 'case_company_serving', ['company_id'], ['id'],
                          onupdate='CASCADE')
    op.create_foreign_key('fk_CaseProperty_property_id', 'case_property', 'property', ['property_id'], ['id'],
                          onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseProperty_property_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_CaseProperty_company_id', 'case_property', type_='foreignkey')
    op.create_foreign_key('fk_case_property_company_id', 'case_property', 'case_company_serving', ['company_id'],
                          ['id'])
    op.create_foreign_key('fk_case_property_property_id', 'case_property', 'property', ['property_id'], ['id'])
    op.drop_constraint('fk_Application_property_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_Application_company_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_case_application_company_id', 'case_application', 'case_company_serving', ['company_id'],
                          ['id'])
    op.create_foreign_key('fk_case_application_property_id', 'case_application', 'property', ['property_id'], ['id'])
    op.create_table('case_assessment',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('fee_percent', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('case_property_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['case_property_id'], ['case_property.id'],
                                            name='fk_case_assessment_case_property_id'),
                    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_CaseAssessment_created_by_id'),
                    sa.ForeignKeyConstraint(['state_id'], ['case_assessment_state.id'],
                                            name='fk_case_assessment_state_id'),
                    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_CaseAssessment_updated_by_id'),
                    sa.PrimaryKeyConstraint('id', name='case_assessment_pkey')
                    )
    # ### end Alembic commands ###
