"""attachment binary to notes

Revision ID: 16d9b4c4b57e
Revises: 7907b03f60ff
Create Date: 2020-07-23 21:52:48.110880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16d9b4c4b57e'
down_revision = '7907b03f60ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('attachment', sa.LargeBinary(), nullable=True))
    op.add_column('case_note', sa.Column('attachment_extension', sa.String(), nullable=True))
    op.drop_column('case_note', 'details')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('case_note', 'attachment_extension')
    op.drop_column('case_note', 'attachment')
    # ### end Alembic commands ###
