"""create ApplicationTag many to many association

Revision ID: 170cc6cc813a
Revises: 9b98b26fcd85
Create Date: 2020-05-03 17:40:18.654187

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '170cc6cc813a'
down_revision = '9b98b26fcd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_tag',
                    sa.Column('application_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['application_id'], ['case_application.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['case_tag.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_application_tag')
    # ### end Alembic commands ###
