"""add coordinate_x and coordinate_y to property table

Revision ID: 189b883a676c
Revises: caee292729ad
Create Date: 2020-01-18 00:35:28.514634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '189b883a676c'
down_revision = 'caee292729ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('coordinate_x', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('coordinate_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'coordinate_y')
    op.drop_column('property', 'coordinate_x')
    # ### end Alembic commands ###
