"""add land_use attribute to property table

Revision ID: 18c82008ef6e
Revises: 85cfbe4fa34b
Create Date: 2020-04-24 23:11:20.117165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c82008ef6e'
down_revision = '85cfbe4fa34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('land_use', sa.Integer(), nullable=True))
    op.add_column('property_original', sa.Column('land_use', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'land_use')
    op.drop_column('property', 'land_use')
    # ### end Alembic commands ###
