"""assessment_id to assessment

Revision ID: 19a96f7aff94
Revises: ff1704f6f698
Create Date: 2020-02-18 21:32:39.121630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b48d4148fc'
down_revision = '19a96f7aff94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
ALTER TABLE assessment ADD COLUMN assessment_id INT;

ALTER TABLE assessment
  ADD CONSTRAINT assessment_assessment_dates_fkey FOREIGN KEY (assessment_id)
      REFERENCES assessment_dates (id)
      ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE assessment DROP COLUMN assessment_date;

UPDATE assessment
SET    assessment_id = assessment_dates.id
FROM   assessment_dates
JOIN   property on assessment_dates.county = property.county
WHERE  property.id = assessment.property_id;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    ALTER TABLE assessment DROP COLUMN assessment_id;

    ALTER TABLE assessment
      DROP CONSTRAINT assessment_assessment_dates_fkey;
        ''')    # ### end Alembic commands ###
