"""add approved_contract note type

Revision ID: 1b0f5c720074
Revises: 52e55e7e4d48
Create Date: 2020-09-10 00:26:29.859081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0f5c720074'
down_revision = '52e55e7e4d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (13, 'System', 'approved_contract')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id=13;
        '''
    )
    # ### end Alembic commands ###
