"""add override_value to assessment table

Revision ID: 1b22dbc9f22a
Revises: c6a634adda29
Create Date: 2020-06-16 01:24:49.743693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b22dbc9f22a'
down_revision = 'c6a634adda29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('override_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'override_value')
    # ### end Alembic commands ###
