"""inventory rules on delete cascade

Revision ID: 1c02cd914977
Revises: d2a1977866bf
Create Date: 2020-01-21 19:29:14.790268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c02cd914977'
down_revision = 'd2a1977866bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_rules_parent_id_fkey', 'inventory_rules', type_='foreignkey')
    op.create_foreign_key('inventory_rules_parent_id_fkey', 'inventory_rules', 'properties_rules', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_rules_parent_id_fkey', 'inventory_rules', type_='foreignkey')
    op.create_foreign_key('inventory_rules_parent_id_fkey', 'inventory_rules', 'properties_rules', ['parent_id'], ['id'])
    # ### end Alembic commands ###
