"""change zip_code type to integer

Revision ID: 1c7c3f3819da
Revises: 69fa5c7c1324
Create Date: 2020-04-29 16:26:17.624991

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1c7c3f3819da'
down_revision = '69fa5c7c1324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''alter table case_application alter column zip_code type int using zip_code::int;''')
    op.execute('''alter table case_client alter column zip_code type int using zip_code::int;''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_client', 'zip_code',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.alter_column('case_application', 'zip_code',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
