"""obsolescences table

Revision ID: 235139cdf248
Revises: ce3f5f379938
Create Date: 2020-06-11 16:53:18.505356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235139cdf248'
down_revision = 'ce3f5f379938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obsolescences',
    sa.Column('affected_property_id', sa.Integer(), nullable=False),
    sa.Column('obs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affected_property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['obs_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('affected_property_id', 'obs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obsolescences')
    # ### end Alembic commands ###
