"""selected column to assessmentRatio

Revision ID: 237998ed1d42
Revises: 3de92f99e236
Create Date: 2019-12-22 16:37:17.397910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '237998ed1d42'
down_revision = '3de92f99e236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_ratio', sa.Column('selected', sa.Boolean(), nullable=True))
    op.alter_column('assessment_ratio', 'town_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('cma_result', 'good_avg',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cma_result', 'good_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cma_result', 'sale_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('cma_result', 'sale_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cma_result', 'sale_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cma_result', 'sale_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('cma_result', 'good_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cma_result', 'good_avg',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('assessment_ratio', 'selected')
    # ### end Alembic commands ###
