"""baths from float to ints

Revision ID: 237d92ddfde6
Revises: 63f7bcd937cb
Create Date: 2019-12-15 19:43:10.899460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '237d92ddfde6'
down_revision = '63f7bcd937cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'full_baths',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=True)
    op.alter_column('property', 'half_baths',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'half_baths',
                    existing_type=sa.Integer(),
                    type_=postgresql.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True)
    op.alter_column('property', 'full_baths',
                    existing_type=sa.Integer(),
                    type_=postgresql.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True)
    # ### end Alembic commands ###
