"""propertyvalidation no foreign key

Revision ID: 237e86aa2400
Revises: 82ce702dc384
Create Date: 2019-12-17 02:38:47.347818

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '237e86aa2400'
down_revision = '82ce702dc384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_validation_property_id_fkey', 'property_validation', type_='foreignkey')
    op.drop_column('property_validation', 'property_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_validation', sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('property_validation_property_id_fkey', 'property_validation', 'property', ['property_id'],
                          ['id'])
    # ### end Alembic commands ###
