"""add mailing_address to contact info mixin

Revision ID: 23c9fccd2300
Revises: e5f1d64032dd
Create Date: 2020-05-13 03:17:41.684870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c9fccd2300'
down_revision = 'e5f1d64032dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('mailing_address', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'mailing_address')
    op.drop_column('case_application', 'mailing_address')
    # ### end Alembic commands ###
