"""clients-tags many-to-many association

Revision ID: 23e10f64b3c6
Revises: 170cc6cc813a
Create Date: 2020-05-04 16:14:12.228749

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '23e10f64b3c6'
down_revision = '170cc6cc813a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_client_tag',
                    sa.Column('client_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['client_id'], ['case_client.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['case_tag.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_client_tag')
    # ### end Alembic commands ###
