"""gist index to speed up single cma

Revision ID: 23fb837495a6
Revises: aa6efb26cc7b
Create Date: 2020-05-21 16:29:54.333117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fb837495a6'
down_revision = 'aa6efb26cc7b'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sale_price', 'sale', ['price'], unique=False)
    op.create_index('ix_sale_date', 'sale', ['date'], unique=False)
    op.create_index('ix_sale_arms_length', 'sale', ['arms_length'], unique=False)
    op.drop_index(op.f('ix_property_geo'), table_name='property')
    op.drop_index('ix_Property_county', table_name='property')
    op.drop_index('ix_Property_apn', table_name='property')
    op.drop_index('ix_Property_another_combined_index', table_name='property')
    op.create_index('ix_assessment_assessment_id', 'assessment', ['assessment_id'], unique=False)
    op.drop_index('ix_PropertyOriginal_another_combined_index', table_name='property_original')
    op.drop_index('ix_PropertyOriginal_apn', table_name='property_original')
    op.drop_index('ix_PropertyOriginal_county', table_name='property_original')
    op.execute('''
    CREATE INDEX ix_property_geo
    ON property using gist(geography(geo));
    
    CREATE INDEX ix_propertyoriginal_geo
    ON property_original using gist(geography(geo));
    ''')
    # pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('assessment_assessment_id_index', table_name='assessment')
    op.create_index('ix_Property_apn', 'property', ['apn'], unique=False)
    op.create_index('ix_Property_county', 'property', ['county'], unique=False)
    op.create_index(op.f('ix_property_geo'), 'property', ['geo'], unique=False)
    op.drop_index('sale_arms_length_index', table_name='sale')
    op.drop_index('sale_date_index', table_name='sale')
    op.drop_index('sale_price_index', table_name='sale')
    # ### end Alembic commands ###
