"""integrate traceable trait mixin into CaseNote model

Revision ID: 24dcb22e657f
Revises: 8bcc6d9de780
Create Date: 2020-04-23 10:51:27.677647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dcb22e657f'
down_revision = '8bcc6d9de780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('case_note', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('case_note', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('case_note', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseNote_created_by_id', 'case_note', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_CaseNote_updated_by_id', 'case_note', 'users', ['updated_by_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseNote_updated_by_id', 'case_note', type_='foreignkey')
    op.drop_constraint('fk_CaseNote_created_by_id', 'case_note', type_='foreignkey')
    op.drop_column('case_note', 'updated_by_id')
    op.drop_column('case_note', 'updated_at')
    op.drop_column('case_note', 'created_by_id')
    op.drop_column('case_note', 'created_at')
    # ### end Alembic commands ###
