"""user viewer role

Revision ID: 250aecfa5298
Revises: 995f30f6f0ed
Create Date: 2020-08-01 00:21:05.148370

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '250aecfa5298'
down_revision = '995f30f6f0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    INSERT INTO public.role (id, name, description, "default", permissions) VALUES (DEFAULT, 'viewer', 'viewer', null, 1);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
