"""insert values into case_application_status table

Revision ID: 25fdcaa2d7da
Revises: c93a16e3ef08
Create Date: 2020-05-13 15:11:36.446758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fdcaa2d7da'
down_revision = 'c93a16e3ef08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_application_status (id, name) VALUES (1, 'Incoming');
        INSERT INTO case_application_status (id, name) VALUES (2, 'Approved');
        INSERT INTO case_application_status (id, name) VALUES (3, 'Rejected');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_application_status;
        '''
    )
    # ### end Alembic commands ###
