"""add settings_misc table

Revision ID: 2828086c6d4e
Revises: 5400f5bfc400
Create Date: 2020-03-10 23:55:57.621189

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2828086c6d4e'
down_revision = '5400f5bfc400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_misc',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('county', sa.String(), nullable=True),
                    sa.Column('key', sa.String(length=50), nullable=False),
                    sa.Column('value', sa.String(), nullable=True),
                    sa.Column('data_type', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('county', 'key', name='uc_county_key')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_misc')
    # ### end Alembic commands ###
