"""added owner_city, owner_zip in owner table

Revision ID: 29869e9e74b9
Revises: a75389fe24b1
Create Date: 2020-02-09 18:25:07.122810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29869e9e74b9'
down_revision = 'a75389fe24b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('owner_city', sa.String(), nullable=True))
    op.add_column('owner', sa.Column('owner_zip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'owner_zip')
    op.drop_column('owner', 'owner_city')
    # ### end Alembic commands ###
