"""add apn, county to property_gis table

Revision ID: 2c463a7af2f1
Revises: 36d652698aab
Create Date: 2020-04-11 00:45:35.003154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c463a7af2f1'
down_revision = '36d652698aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_gis', sa.Column('apn', sa.String(), nullable=True))
    op.add_column('property_gis', sa.Column('county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_gis', 'county')
    op.drop_column('property_gis', 'apn')
    # ### end Alembic commands ###
