"""add initials column to case_application table

Revision ID: 2dad48cb6b94
Revises: 23c9fccd2300
Create Date: 2020-05-13 03:25:52.476319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dad48cb6b94'
down_revision = '23c9fccd2300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('initials', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'initials')
    # ### end Alembic commands ###
