"""removing high sale date range

Revision ID: 2e545b257d97
Revises: 536a612e381b
Create Date: 2020-07-06 19:29:50.636124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e545b257d97'
down_revision = '536a612e381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'high_sale_date_lower')
    op.drop_column('properties_rules', 'high_sale_date_higher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('high_sale_date_higher', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('properties_rules', sa.Column('high_sale_date_lower', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
