"""add description to case_payment_status

Revision ID: 2e81db286047
Revises: df1d969b3cca
Create Date: 2020-07-21 20:54:38.631713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e81db286047'
down_revision = 'df1d969b3cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_payment_status', sa.Column('description', sa.String(), nullable=True))

    op.execute(
        '''
        UPDATE case_payment_status
        SET description = 'Unpaid'
        WHERE id = 1;

        UPDATE case_payment_status
        SET description = 'Paid'
        WHERE id = 2;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_payment_status', 'description')
    # ### end Alembic commands ###
