"""rule_name to PropertiesRules

Revision ID: 2fc56b8b5606
Revises: 84171bd315c3
Create Date: 2020-01-13 19:25:08.929843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc56b8b5606'
down_revision = '84171bd315c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('rule_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_properties_rules_rule_name'), 'properties_rules', ['rule_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_rules_rule_name'), table_name='properties_rules')
    op.drop_column('properties_rules', 'rule_name')
    # ### end Alembic commands ###
