"""update adjustments_all in properties_rules table

Revision ID: 312948659d0d
Revises: 3f16fc5bca94
Create Date: 2020-04-14 11:44:01.519077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312948659d0d'
# down_revision = '3f16fc5bca94'
down_revision = '0d50572a7bc6'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- update 'palmbeach' adjustments_all
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,HEAT,GARAGE,POOL,PATIO,PORCH}'
        where county = 'palmbeach' and id=52;

        -- update 'miamidade' adjustments_all
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,BEDROOMS,PATIO,POOL}'
        where county = 'miamidade' and id=62;
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
