"""assessment village columns for nassau

Revision ID: 325e468feb62
Revises: d34b94050460
Create Date: 2020-02-02 18:58:16.838143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325e468feb62'
down_revision = 'd34b94050460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('village_1', sa.String(), nullable=True))
    op.add_column('assessment', sa.Column('village_1_pct', sa.Float(), nullable=True))
    op.add_column('assessment', sa.Column('village_2', sa.String(), nullable=True))
    op.add_column('assessment', sa.Column('village_2_pct', sa.Float(), nullable=True))
    op.add_column('assessment', sa.Column('village_3', sa.String(), nullable=True))
    op.add_column('assessment', sa.Column('village_3_pct', sa.Float(), nullable=True))
    op.add_column('owner', sa.Column('owner_address_1', sa.String(), nullable=True))
    op.add_column('owner', sa.Column('owner_address_2', sa.String(), nullable=True))
    op.add_column('owner', sa.Column('owner_address_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'owner_address_3')
    op.drop_column('owner', 'owner_address_2')
    op.drop_column('owner', 'owner_address_1')
    op.drop_column('assessment', 'village_3_pct')
    op.drop_column('assessment', 'village_3')
    op.drop_column('assessment', 'village_2_pct')
    op.drop_column('assessment', 'village_2')
    op.drop_column('assessment', 'village_1_pct')
    op.drop_column('assessment', 'village_1')
    # ### end Alembic commands ###
