"""set default is_primary to false

Revision ID: 32705a1b512b
Revises: 4c96426560ec
Create Date: 2020-09-22 21:02:23.021246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32705a1b512b'
down_revision = '4c96426560ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE ONLY single_sma_workups ALTER COLUMN is_primary SET DEFAULT false;
        '''
    )

    op.execute(
        '''
        UPDATE single_sma_workups SET is_primary = false WHERE is_primary IS NULL;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
