"""fix SAWarning wargings, indexes name conventions

Revision ID: 339072537168
Revises: 397c2bb3f2b2
Create Date: 2020-05-02 03:35:18.821871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339072537168'
down_revision = '397c2bb3f2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_rules_county_town_year', 'properties_rules', ['county', 'town', 'year'], unique=True)
    op.create_index('ix_properties_rules_county_year', 'properties_rules', ['county', 'year'], unique=True)
    op.drop_index('properties_rules_county_town_year_index', table_name='properties_rules')
    op.drop_index('properties_rules_county_year_index', table_name='properties_rules')
    op.create_index('ix_property_photo_property_id', 'property_photo', ['property_id'], unique=False)
    op.create_index('ix_property_photo_property_id_is_best', 'property_photo', ['property_id', 'is_best'], unique=True,
                    postgresql_where=sa.text('is_best'))
    op.drop_index('only_one_best_photo', table_name='property_photo')
    op.drop_index('property_photo_property_id_index', table_name='property_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('property_photo_property_id_index', 'property_photo', ['property_id'], unique=False)
    op.create_index('only_one_best_photo', 'property_photo', ['property_id', 'is_best'], unique=True)
    op.drop_index('ix_property_photo_property_id_is_best', table_name='property_photo')
    op.drop_index('ix_property_photo_property_id', table_name='property_photo')
    op.create_index('properties_rules_county_year_index', 'properties_rules', ['county', 'year'], unique=True)
    op.create_index('properties_rules_county_town_year_index', 'properties_rules', ['county', 'town', 'year'],
                    unique=True)
    op.drop_index('ix_properties_rules_county_year', table_name='properties_rules')
    op.drop_index('ix_properties_rules_county_town_year', table_name='properties_rules')
    # ### end Alembic commands ###
