"""add takeover fields to case_application table

Revision ID: 343fe52ed8b4
Revises: fad191763141
Create Date: 2020-05-25 15:36:41.624646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343fe52ed8b4'
down_revision = 'fad191763141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('takeover_client_id', sa.Integer(), nullable=True))
    op.add_column('case_application', sa.Column('takeover_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'takeover_year')
    op.drop_column('case_application', 'takeover_client_id')
    # ### end Alembic commands ###
