"""fix sale foreign key names

Revision ID: 3479a7c6f0b9
Revises: 028edcb91ab8
Create Date: 2020-05-02 01:55:29.211321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3479a7c6f0b9'
down_revision = '028edcb91ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_property_id', table_name='sale')
    op.drop_constraint('sale_property_id_fkey', 'sale', type_='foreignkey')
    op.create_foreign_key('sale_property_id_fkey', 'sale', 'property', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sale_property_id_fkey', 'sale', type_='foreignkey')
    op.create_foreign_key('sale_property_id_fkey', 'sale', 'property', ['property_id'], ['id'], onupdate='CASCADE',
                          ondelete='CASCADE')
    op.create_index('ix_sale_property_id', 'sale', ['property_id'], unique=False)
    # ### end Alembic commands ###
