"""add address_unit to property table

Revision ID: 34d2ca77eb48
Revises: 6074474fc8a4
Create Date: 2020-06-01 19:49:50.202960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d2ca77eb48'
down_revision = '6074474fc8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('address_unit', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('address_unit', sa.String(), nullable=True))

    op.drop_column('property', 'unit_number')
    op.drop_column('property', 'unit_string')
    op.drop_column('property_original', 'unit_number')
    op.drop_column('property_original', 'unit_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_original', sa.Column('unit_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property_original', sa.Column('unit_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('unit_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('unit_number', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_column('property_original', 'address_unit')
    op.drop_column('property', 'address_unit')
    # ### end Alembic commands ###
