"""remove settings_misc table

Revision ID: 35db97217128
Revises: b5374e6568a1
Create Date: 2020-03-16 15:23:01.504774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '35db97217128'
down_revision = 'b5374e6568a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_misc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_misc',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
                    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='settings_misc_pkey'),
                    sa.UniqueConstraint('county', 'key', name='uc_county_key')
                    )
    # ### end Alembic commands ###
