"""property basement type to integer

Revision ID: 37228d4529e8
Revises: 758e5872ce57
Create Date: 2020-01-12 21:07:27.209930

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '37228d4529e8'
down_revision = '758e5872ce57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE property
    SET basement_type = CASE
                        WHEN lower(basement_type) = 'none' THEN '0'
                        when lower(basement_type) = 'slab' THEN '1'
                        when lower(basement_type) = 'crawl' THEN '2'
                        when lower(basement_type) = 'half' THEN '3'
                        when lower(basement_type) = 'full' THEN '4'
                        when lower(basement_type) = 'pier' THEN '5'
                        when lower(basement_type) = 'partial' THEN '6'
                        when lower(basement_type) = 'part' THEN '7'
                        when lower(basement_type) = '' THEN null
                        else
                            basement_type
    END
    ''')
    op.execute('''
    alter table property alter column basement_type type int using basement_type::int;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'basement_type',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
