"""capitalize Suffolk address, address_line_1, address_line_2, city in property table

Revision ID: 39f29588a777
Revises: ad2ea1921ab8
Create Date: 2020-08-16 16:11:54.110725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f29588a777'
down_revision = 'ad2ea1921ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     '''
    #     -- capitalize Suffolk 'address', 'address_line_1', 'address_line_2', 'city'
    #     update property set
    #                         address = initcap(address),
    #                         address_line_1 = initcap(address_line_1),
    #                         address_line_2 = initcap(address_line_2),
    #                         city = initcap(city)
    #     where county = 'suffolk';
    #
    #     -- make uppercase stop words in 'address' attribute
    #     DO
    #     $do$
    #     DECLARE
    #        stop_word varchar[] := '{NY}';
    #     BEGIN
    #        FOR i IN array_lower(stop_word, 1) .. array_upper(stop_word, 1)
    #        LOOP
    #           update property
    #           set address = replace(initcap(address), initcap(' '||stop_word[i]||' '), ' '||stop_word[i]||' ')
    #           WHERE upper(address) ilike '% '||stop_word[i]||' %'
    #           AND county = 'suffolk';
    #        END LOOP;
    #     END
    #     $do$;
    #
    #     '''
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
