"""add cost_of_sale into properties_rules table

Revision ID: 3afdb52104f3
Revises: f7aa928fbac1
Create Date: 2020-06-20 00:14:52.409007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afdb52104f3'
down_revision = 'f7aa928fbac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('cost_of_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'cost_of_sale')
    # ### end Alembic commands ###
