"""add patios table

Revision ID: 3b7b221dbd20
Revises: 584fc155c01c
Create Date: 2020-02-26 15:30:16.781656

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b7b221dbd20'

down_revision = '584fc155c01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
