"""fix phone types

Revision ID: 3c11f405f874
Revises: 859f817b4707
Create Date: 2020-04-20 14:02:53.585911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c11f405f874'
down_revision = '859f817b4707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('_cell_number', sa.Unicode(length=20), nullable=True))
    op.add_column('case_application', sa.Column('_phone_number', sa.Unicode(length=20), nullable=True))
    op.add_column('case_client', sa.Column('_cell_number', sa.Unicode(length=20), nullable=True))
    op.add_column('case_client', sa.Column('_phone_number', sa.Unicode(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', '_phone_number')
    op.drop_column('case_client', '_cell_number')
    op.drop_column('case_application', '_phone_number')
    op.drop_column('case_application', '_cell_number')
    # ### end Alembic commands ###
