"""add pin_entered to application

Revision ID: 3c13170a4d18
Revises: ba6fdbdab4ec
Create Date: 2020-08-10 00:11:15.538709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c13170a4d18'
down_revision = 'ba6fdbdab4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE case_application ADD COLUMN pin_entered BOOLEAN DEFAULT FALSE;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'pin_entered')
    # ### end Alembic commands ###
