"""add district, section, block, lot to case_application table

Revision ID: 3d44a5c90b17
Revises: 1644fb2c8211
Create Date: 2020-06-02 15:06:52.567476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d44a5c90b17'
down_revision = '1644fb2c8211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('block', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('district', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('lot', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'section')
    op.drop_column('case_application', 'lot')
    op.drop_column('case_application', 'district')
    op.drop_column('case_application', 'block')
    # ### end Alembic commands ###
