"""dev_rules tables

Revision ID: 3de92f99e236
Revises: b929b5796e8f
Create Date: 2019-12-20 19:43:44.603893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3de92f99e236'
down_revision = 'b929b5796e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_rules')
    op.drop_table('selection_rules')
    op.drop_table('ruleset')

    op.create_table('cma_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_ts', sa.DateTime(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('town', sa.String(), nullable=True),
    sa.Column('selection_rule', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proximity_range', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sale_days_delta', sa.Integer(), nullable=True),
    sa.Column('gla_range', sa.Integer(), nullable=True),
    sa.Column('same_school_district', sa.Boolean(), nullable=False),
    sa.Column('same_town', sa.Boolean(), nullable=False),
    sa.Column('same_street', sa.Boolean(), nullable=False),
    sa.Column('same_property_style', sa.Boolean(), nullable=False),
    sa.Column('same_property_class', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cma_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('good_avg', sa.Float(), nullable=False),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('all_avg', sa.Float(), nullable=False),
    sa.Column('all_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cma_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_set', sa.Integer(), nullable=False),
    sa.Column('price_start', sa.Integer(), nullable=True),
    sa.Column('price_end', sa.Integer(), nullable=True),
    sa.Column('full_bath', sa.Integer(), nullable=True),
    sa.Column('half_bath', sa.Integer(), nullable=True),
    sa.Column('gla_sqft', sa.Integer(), nullable=True),
    sa.Column('lot_sqft', sa.Integer(), nullable=True),
    sa.Column('garage', sa.Integer(), nullable=True),
    sa.Column('basement_prices', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['rule_set'], ['rule_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_rule')
    op.drop_table('cma_result')
    op.drop_table('selection_rule')
    op.drop_table('rule_set')
    op.drop_table('cma_task')
    # ### end Alembic commands ###
