"""time_adjustments assessment_date table

Revision ID: 3e47beb573c7
Revises: 01194cbd308d
Create Date: 2020-02-07 13:00:13.944185

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3e47beb573c7'
down_revision = '01194cbd308d'
branch_labels = None
depends_on = None

ASSESSMENT_TYPES = [
    ('final', 'Final'),
    ('tentative', 'Tentative'),
    ('school', 'School'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_dates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('county', sa.String(), nullable=False),
                    sa.Column('village', sa.String(), nullable=True),
                    sa.Column('assessment_type', sqlalchemy_utils.types.choice.ChoiceType(ASSESSMENT_TYPES),
                              nullable=True),
                    sa.Column('assessment_year', sa.Integer(), nullable=True),
                    sa.Column('assessment_month', sa.Integer(), nullable=True),
                    sa.Column('assessment_file', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('time_adjustments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('county', sa.String(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('month', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_adjustments')
    op.drop_table('assessment_dates')
    # ### end Alembic commands ###
