"""create case_note, case_note_type tables

Revision ID: 401d66b378f9
Revises: a442439262dd
Create Date: 2020-04-21 21:04:51.159936

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '401d66b378f9'
down_revision = 'a442439262dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_note_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('note_type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('case_note',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('note_type_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['note_type_id'], ['case_note_type.id'], name='fk_CaseNote_case_note_type_id'
                    ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='fk_CaseNote_users_id'
                    ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_note')
    op.drop_table('case_note_type')
    # ### end Alembic commands ###
