"""add single cma workups table

Revision ID: 415b876d11d0
Revises: f555d9e25bd9
Create Date: 2020-09-22 16:58:15.557436

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '415b876d11d0'
down_revision = 'f555d9e25bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_sma_workups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('property_id', sa.Integer(), nullable=True),
                    sa.Column('report_file_id', sa.Integer(), nullable=True),
                    sa.Column('is_primary', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['property_id'], ['property.id'], name='fk_single_sma_workups_property_id'),
                    sa.ForeignKeyConstraint(['report_file_id'], ['files.id'],
                                            name='fk_single_sma_workups_report_file_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_sma_workups')
    # ### end Alembic commands ###
