"""add fully rejected note type

Revision ID: 42d269e23d8f
Revises: 81e394b1e8e1
Create Date: 2020-07-31 18:15:14.234504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d269e23d8f'
down_revision = '81e394b1e8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (9, 'System', 'fully_rejected');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id=9;
        '''
    )
    # ### end Alembic commands ###
