"""florida property rules update

Revision ID: 43a1152e7d98
Revises: c805deb19d54
Create Date: 2020-06-04 21:54:14.706709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a1152e7d98'
down_revision = 'c805deb19d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE public.selection_rules SET proximity_range = 2.000, percent_gla_lower = 15, percent_gla_higher = 60, percent_sale_lower = 15, percent_sale_higher = 25, same_property_class = false, same_school_district = false, same_town = false, same_street = false, same_property_style = false, same_one_family_types = false, percent_lot_size_higher = 100, percent_lot_size_lower = 50, sale_date_from = '2019-01-01', sale_date_to = '2020-01-01', same_age = true, same_building = true WHERE parent_id = 43;
UPDATE public.selection_rules SET proximity_range = 2.000, percent_gla_lower = 15, percent_gla_higher = 60, percent_sale_lower = 15, percent_sale_higher = 25, same_property_class = false, same_school_district = false, same_town = false, same_street = false, same_property_style = false, same_one_family_types = false, percent_lot_size_higher = 100, percent_lot_size_lower = 50, sale_date_from = '2019-01-01', sale_date_to = '2020-01-01', same_age = true, same_building = true WHERE parent_id = 62;
UPDATE public.selection_rules SET proximity_range = 2.000, percent_gla_lower = 15, percent_gla_higher = 60, percent_sale_lower = 15, percent_sale_higher = 25, same_property_class = false, same_school_district = false, same_town = false, same_street = false, same_property_style = false, same_one_family_types = false, percent_lot_size_higher = 100, percent_lot_size_lower = 50, sale_date_from = '2019-01-01', sale_date_to = '2020-01-01', same_age = true, same_building = true WHERE parent_id = 52;

UPDATE public.properties_rules set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,HEAT,GARAGE,POOL,PATIO,PORCH,LOCATION}' WHERE id = 52;

UPDATE public.inventory_rules SET parent_id = 43, price_start = 0, price_end = 300000, full_bath = 6000, half_bath = 3000, gla_sqft = 30, lot_sqft = 5, garage = 10000, basement_prices = '{}', pool = null, fireplace = null, bedrooms = 6000, heat_type_prices = '{}', patio_type_prices = '{}', paving_type_prices = '{}', porch_type_prices = '{}', floor_height = 10000 WHERE id = 11;
UPDATE public.inventory_rules SET parent_id = 43, price_start = 300001, price_end = 500000, full_bath = 8000, half_bath = 4000, gla_sqft = 40, lot_sqft = 10, garage = 12000, basement_prices = '{}', pool = null, fireplace = null, bedrooms = 8000, heat_type_prices = '{}', patio_type_prices = '{}', paving_type_prices = '{}', porch_type_prices = '{}', floor_height = 15000 WHERE id = 10;
UPDATE public.inventory_rules SET parent_id = 43, price_start = 500001, price_end = 800000, full_bath = 12000, half_bath = 6000, gla_sqft = 50, lot_sqft = 15, garage = 14000, basement_prices = '{}', pool = null, fireplace = null, bedrooms = 10000, heat_type_prices = '{}', patio_type_prices = '{}', paving_type_prices = '{}', porch_type_prices = '{}', floor_height = 20000 WHERE id = 9;
UPDATE public.inventory_rules SET parent_id = 43, price_start = 800001, price_end = 1500000, full_bath = 15000, half_bath = 7500, gla_sqft = 70, lot_sqft = 20, garage = 16000, basement_prices = '{}', pool = null, fireplace = null, bedrooms = 12000, heat_type_prices = '{}', patio_type_prices = '{}', paving_type_prices = '{}', porch_type_prices = '{}', floor_height = 25000 WHERE id = 8;
UPDATE public.inventory_rules SET parent_id = 43, price_start = 1500001, price_end = 10000000, full_bath = 18000, half_bath = 9000, gla_sqft = 80, lot_sqft = 25, garage = 18000, basement_prices = '{}', pool = null, fireplace = null, bedrooms = 14000, heat_type_prices = '{}', patio_type_prices = '{}', paving_type_prices = '{}', porch_type_prices = '{}', floor_height = 30000 WHERE id = 7;
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft, garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices, patio_type_prices, paving_type_prices, porch_type_prices, floor_height) VALUES (DEFAULT, 43, 10000001, 100000000, 25000, 12500, 90, 30, 20000, '{}', null, null, 16000, '{}', '{}', '{}', '{}', 40000);

UPDATE public.inventory_rules SET parent_id = 52, price_start = 0, price_end = 300000, full_bath = 6000, half_bath = 3000, gla_sqft = 30, lot_sqft = 5, garage = 10000, basement_prices = '{}', pool = 6000, fireplace = null, bedrooms = 6000, heat_type_prices = '{0,1250,2500,3750,5000,6250,7500,8750,10000,11250}', patio_type_prices = '{1250,2500}', paving_type_prices = '{}', porch_type_prices = '{0,1250,2500,3750,5000}', floor_height = 10000 WHERE id = 16;
UPDATE public.inventory_rules SET parent_id = 52, price_start = 300001, price_end = 500000, full_bath = 8000, half_bath = 4000, gla_sqft = 40, lot_sqft = 10, garage = 12000, basement_prices = '{}', pool = 8000, fireplace = null, bedrooms = 8000, heat_type_prices = '{0,2500,5000,7500,10000,12500,15000,17500,20000,22500}', patio_type_prices = '{2500,5000}', paving_type_prices = '{}', porch_type_prices = '{0,2500,5000,7500,10000}', floor_height = 15000 WHERE id = 15;
UPDATE public.inventory_rules SET parent_id = 52, price_start = 500001, price_end = 800000, full_bath = 12000, half_bath = 6000, gla_sqft = 50, lot_sqft = 15, garage = 14000, basement_prices = '{}', pool = 10000, fireplace = null, bedrooms = 10000, heat_type_prices = '{0,5000,10000,15000,20000,25000,30000,35000,40000,45000}', patio_type_prices = '{5000,10000}', paving_type_prices = '{}', porch_type_prices = '{0,5000,10000,15000,20000}', floor_height = 20000 WHERE id = 14;
UPDATE public.inventory_rules SET parent_id = 52, price_start = 800001, price_end = 1500000, full_bath = 15000, half_bath = 7500, gla_sqft = 70, lot_sqft = 20, garage = 16000, basement_prices = '{}', pool = 12000, fireplace = null, bedrooms = 12000, heat_type_prices = '{0,7500,15000,22500,30000,37500,45000,52500,60000,67500}', patio_type_prices = '{7500,15000}', paving_type_prices = '{}', porch_type_prices = '{0,7500,15000,22500,30000}', floor_height = 25000 WHERE id = 13;
UPDATE public.inventory_rules SET parent_id = 52, price_start = 1500001, price_end = 10000000, full_bath = 18000, half_bath = 9000, gla_sqft = 80, lot_sqft = 25, garage = 18000, basement_prices = '{}', pool = 14000, fireplace = null, bedrooms = 14000, heat_type_prices = '{0,10000,20000,30000,40000,50000,60000,70000,80000,90000}', patio_type_prices = '{10000,20000}', paving_type_prices = '{}', porch_type_prices = '{0,10000,20000,30000,40000}', floor_height = 30000 WHERE id = 12;
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft, garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices, patio_type_prices, paving_type_prices, porch_type_prices, floor_height) VALUES (DEFAULT, 52, 10000001, 100000000, 25000, 12500, 90, 30, 20000, '{}', null, null, 16000, '{}', '{}', '{}', '{}', 40000);

UPDATE public.inventory_rules SET parent_id = 62, price_start = 0, price_end = 300000, full_bath = 6000, half_bath = 3000, gla_sqft = 30, lot_sqft = 5, garage = 10000, basement_prices = '{}', pool = 6000, fireplace = null, bedrooms = 6000, heat_type_prices = '{}', patio_type_prices = '{0,1250,2500,3750,5000,6250,7500,8750,5000,11250,5000,5000,5000}', paving_type_prices = '{1250,2500,2000}', porch_type_prices = '{}', floor_height = 10000 WHERE id = 21;
UPDATE public.inventory_rules SET parent_id = 62, price_start = 300001, price_end = 500000, full_bath = 8000, half_bath = 4000, gla_sqft = 40, lot_sqft = 10, garage = 12000, basement_prices = '{}', pool = 8000, fireplace = null, bedrooms = 8000, heat_type_prices = '{}', patio_type_prices = '{0,2500,5000,7500,10000,12500,15000,17500,10000,22500,7500,7500,7500}', paving_type_prices = '{2500,5000,4000}', porch_type_prices = '{}', floor_height = 15000 WHERE id = 20;
UPDATE public.inventory_rules SET parent_id = 62, price_start = 500001, price_end = 800000, full_bath = 12000, half_bath = 6000, gla_sqft = 50, lot_sqft = 15, garage = 14000, basement_prices = '{}', pool = 10000, fireplace = null, bedrooms = 10000, heat_type_prices = '{}', patio_type_prices = '{0,5000,10000,15000,20000,25000,30000,35000,20000,45000,15000,15000,10000}', paving_type_prices = '{5000,7500,6000}', porch_type_prices = '{}', floor_height = 20000 WHERE id = 19;
UPDATE public.inventory_rules SET parent_id = 62, price_start = 800001, price_end = 1500000, full_bath = 15000, half_bath = 7500, gla_sqft = 70, lot_sqft = 20, garage = 16000, basement_prices = '{}', pool = 12000, fireplace = null, bedrooms = 12000, heat_type_prices = '{}', patio_type_prices = '{0,7500,15000,22500,30000,37500,45000,52500,30000,67500,22500,22500,15000}', paving_type_prices = '{7500,10000,8000}', porch_type_prices = '{}', floor_height = 25000 WHERE id = 18;
UPDATE public.inventory_rules SET parent_id = 62, price_start = 1500001, price_end = 10000000, full_bath = 18000, half_bath = 9000, gla_sqft = 80, lot_sqft = 25, garage = 18000, basement_prices = '{}', pool = 14000, fireplace = null, bedrooms = 14000, heat_type_prices = '{}', patio_type_prices = '{0,10000,20000,30000,40000,50000,60000,70000,40000,90000,30000,30000,20000}', paving_type_prices = '{10000,12000,10000}', porch_type_prices = '{}', floor_height = 30000 WHERE id = 17;

INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft, garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices, patio_type_prices, paving_type_prices, porch_type_prices, floor_height) VALUES (DEFAULT, 62, 10000001, 100000000, 25000, 12500, 90, 30, 20000, '{}', null, null, 16000, '{}', '{}', '{}', '{}', 40000);
    
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
