"""add year, new_record columns to property

Revision ID: 45d98d105669
Revises: 0414899f33d9
Create Date: 2020-07-18 14:35:47.973658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d98d105669'
down_revision = '0414899f33d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        '''
        ALTER TABLE property ADD year int DEFAULT 2019;
        ALTER TABLE property ADD new_record bool DEFAULT false;

        ALTER TABLE property_original ADD year int DEFAULT 2019;
        ALTER TABLE property_original ADD new_record bool DEFAULT false;
        '''
    )
    # op.add_column('property', sa.Column('new_record', sa.Boolean(), nullable=True))
    # op.add_column('property', sa.Column('year', sa.Integer(), nullable=True))
    # op.add_column('property_original', sa.Column('new_record', sa.Boolean(), nullable=True))
    # op.add_column('property_original', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'year')
    op.drop_column('property_original', 'new_record')
    # ### end Alembic commands ###
