"""Normalize Palm Beach lot_size after re-parsing

Revision ID: 488174c74456
Revises: 103f17f8136b
Create Date: 2020-04-12 02:36:33.930970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488174c74456'
down_revision = '103f17f8136b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE
            property
        SET
            lot_size = ROUND((lot_size / 43560)::numeric, 4)
        WHERE
            lot_size IS NOT NULL
        AND
            county = 'palmbeach';      
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
