"""added AssessmentDates table

Revision ID: 489368875a1f
Revises: a71fa6de67fa
Create Date: 2020-02-06 00:56:56.999592

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489368875a1f'
down_revision = 'a71fa6de67fa'
branch_labels = None
depends_on = None


ASSESSMENT_TYPES = [
    ('final', 'Final'),
    ('tentative', 'Tentative'),
    ('school', 'School'),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_dates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('county', sa.String(), nullable=False),
                    sa.Column('village', sa.String(), nullable=True),
                    sa.Column('assessment_type',
                              sqlalchemy_utils.types.choice.ChoiceType(ASSESSMENT_TYPES), nullable=True),
                    sa.Column('assessment_year', sa.Integer(), nullable=True),
                    sa.Column('assessment_month', sa.Integer(), nullable=True),
                    sa.Column('assessment_file', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_dates')
    # ### end Alembic commands ###
