"""add property fields to case_property table

Revision ID: 48e0a14287a0
Revises: b744f42ee7dc
Create Date: 2020-05-28 22:45:18.738975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e0a14287a0'
down_revision = 'b744f42ee7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('initials', sa.String(), nullable=True))
    op.drop_column('case_client', 'address_zip')
    op.drop_column('case_client', 'address_line1')
    op.drop_column('case_client', 'address_state')
    op.drop_column('case_client', 'address_line2')
    op.drop_column('case_client', 'address_city')
    op.drop_column('case_client', 'county')
    op.add_column('case_property', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('case_property', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('case_property', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('case_property', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('case_property', sa.Column('address_zip', sa.Integer(), nullable=True))
    op.add_column('case_property', sa.Column('apn', sa.String(), nullable=True))
    op.add_column('case_property', sa.Column('county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_property', 'county')
    op.drop_column('case_property', 'apn')
    op.drop_column('case_property', 'address_zip')
    op.drop_column('case_property', 'address_state')
    op.drop_column('case_property', 'address_line2')
    op.drop_column('case_property', 'address_line1')
    op.drop_column('case_property', 'address_city')
    op.add_column('case_client', sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('address_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('address_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('address_zip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'initials')
    # ### end Alembic commands ###
