"""add billing table

Revision ID: 4c1a65110b82
Revises: 41ca8828a225
Create Date: 2020-07-23 11:47:22.254286

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c1a65110b82'
down_revision = '41ca8828a225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_billing',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=True),
                    sa.Column('attorney_fee', sa.Float(), nullable=True),
                    sa.Column('late_fee', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_billing')
    # ### end Alembic commands ###
