"""null heat_type to 1 for palmbeach county

Revision ID: 4c8573842e67
Revises: 953a2152fa89
Create Date: 2020-04-17 02:03:03.503916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8573842e67'
down_revision = '953a2152fa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- null --> 1
        update property
        set heat_type = 1
        where heat_type is null
        and county = 'palmbeach';
        '''
    )
    op.execute(
        '''
        -- null --> 1
        update property
        set heat_type = 1
        where heat_type = ''
        and county = 'palmbeach';
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
