"""rename attachment to data

Revision ID: 4c96426560ec
Revises: 415b876d11d0
Create Date: 2020-09-22 17:50:31.745901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c96426560ec'
down_revision = '415b876d11d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.drop_column('files', 'attachment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('attachment', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('files', 'data')
    # ### end Alembic commands ###
