"""add county attribute

Revision ID: 4e26a53e9a94
Revises: 3c11f405f874
Create Date: 2020-04-20 18:02:18.600179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e26a53e9a94'
down_revision = '3c11f405f874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('county', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('county', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'county')
    op.drop_column('case_application', 'county')
    # ### end Alembic commands ###
