"""add good_bad_report_file_id to workups

Revision ID: 4e64e1d3c91d
Revises: 7e09f7db8a1e
Create Date: 2020-10-13 13:45:20.638397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e64e1d3c91d'
down_revision = '7e09f7db8a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('good_bad_report_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_single_sma_workups_good_bad_report_file_id', 'single_sma_workups', 'files',
                          ['good_bad_report_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_single_sma_workups_good_bad_report_file_id', 'single_sma_workups', type_='foreignkey')
    op.drop_column('single_sma_workups', 'good_bad_report_file_id')
    # ### end Alembic commands ###
