"""populate florida inventory data into inventory_rules table

Revision ID: 50d400266dc1
Revises: 2edc59ae1447
Create Date: 2020-03-06 02:18:26.559392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d400266dc1'
down_revision = '2edc59ae1447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # update 'broward' inventory values
    op.execute(
        '''
        update inventory_rules set bedrooms = 14000 where id=7 and parent_id=43;
        update inventory_rules set bedrooms = 12000 where id=8 and parent_id=43;
        update inventory_rules set bedrooms = 10000 where id=9 and parent_id=43;
        update inventory_rules set bedrooms = 8000 where id=10 and parent_id=43;
        update inventory_rules set bedrooms = 6000 where id=11 and parent_id=43;
        '''
    )

    # update 'miamidade' inventory values
    op.execute(
        '''
        update inventory_rules set bedrooms = 14000, pool = 14000,
        patio_type_prices = '{0,10000,20000,30000,40000,50000,60000,70000,80000,90000,100000,110000,120000}',
        paving_type_prices = '{10000,20000}' where id=17 and parent_id=62;
        
        update inventory_rules set bedrooms = 12000, pool = 12000,
        patio_type_prices = '{0,7500,15000,22500,30000,37500,45000,52500,60000,67500,75000,82500,90000}', 
        paving_type_prices = '{7500,15000}' where id=18 and parent_id=62;
        
        update inventory_rules set bedrooms = 10000, pool = 10000,
        patio_type_prices = '{0,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000,55000,60000}', 
        paving_type_prices = '{5000,10000}' where id=19 and parent_id=62;
        
        update inventory_rules set bedrooms = 8000, pool = 8000,
        patio_type_prices = '{0,2500,5000,7500,10000,12500,15000,17500,20000,22500,25000,27500,30000}', 
        paving_type_prices = '{2500,5000}' where id=20 and parent_id=62;
        
        update inventory_rules set bedrooms = 6000, pool = 6000,
        patio_type_prices = '{0,1250,2500,3750,5000,6250,7500,8750,10000,11250,12500,13750,15000}', 
        paving_type_prices = '{1250,2500}' where id=21 and parent_id=62;      
        '''
    )

    # update 'palmbeach' inventory values
    op.execute(
        '''
        update inventory_rules set garage = 7000, pool = 14000,
        patio_type_prices = '{10000,20000}',
        heat_type_prices = '{0,10000,20000,30000,40000,50000,60000,70000,80000,90000}',
        porch_type_prices = '{0,10000,20000,30000,40000}' where id=12 and parent_id=52;

        update inventory_rules set garage = 6000, pool = 12000,
        patio_type_prices = '{7500,15000}',
        heat_type_prices = '{0,7500,15000,22500,30000,37500,45000,52500,60000,67500}',
        porch_type_prices = '{0,7500,15000,22500,30000}' where id=13 and parent_id=52;

        update inventory_rules set garage = 5000, pool = 10000,
        patio_type_prices = '{5000,10000}',
        heat_type_prices = '{0,5000,10000,15000,20000,25000,30000,35000,40000,45000}',
        porch_type_prices = '{0,5000,10000,15000,20000}' where id=14 and parent_id=52;

        update inventory_rules set garage = 4500, pool = 8000,
        patio_type_prices = '{2500,5000}',
        heat_type_prices = '{0,2500,5000,7500,10000,12500,15000,17500,20000,22500}',
        porch_type_prices = '{0,2500,5000,7500,10000}' where id=15 and parent_id=52;

        update inventory_rules set garage = 4000, pool = 6000,
        patio_type_prices = '{1250,2500}',
        heat_type_prices = '{0,1250,2500,3750,5000,6250,7500,8750,10000,11250}',
        porch_type_prices = '{0,1250,2500,3750,5000}' where id=16 and parent_id=52;      
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
