"""add assessment_value to assessment table

Revision ID: 50eb8f48c52a
Revises: 45d98d105669
Create Date: 2020-07-18 14:50:00.980674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50eb8f48c52a'
down_revision = '45d98d105669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('assessment_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'assessment_value')
    # ### end Alembic commands ###
