"""effective year to property table

Revision ID: 514eff96d359
Revises: 58fad0247404
Create Date: 2020-10-27 20:29:10.282965

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '514eff96d359'
down_revision = '58fad0247404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('property', sa.Column('effective_age', sa.Integer(), nullable=True))

    op.add_column('property_original', sa.Column('effective_age', sa.Integer(), nullable=True))


def downgrade():
    op.drop_column('property_original', 'effective_age')

    op.drop_column('property', 'effective_age')
