"""new payment invoice table

Revision ID: 518aad783519
Revises: 6edd59291510
Create Date: 2020-08-14 02:28:24.037090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518aad783519'
down_revision = '6edd59291510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_check_payment_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_application_id', sa.Integer(), nullable=True),
    sa.Column('case_client_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_application_id'], ['case_application.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['case_client_id'], ['case_client.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_check_payment_invoice')
    # ### end Alembic commands ###
