"""email address to lower

Revision ID: 52e55e7e4d48
Revises: fda8f2a92f1a
Create Date: 2020-09-04 13:55:34.929429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e55e7e4d48'
down_revision = 'fda8f2a92f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     '''
    #     UPDATE case_email SET email_address=lower(email_address);
    #     '''
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
