"""rule name not unique in properties_rules

Revision ID: 535145082ebf
Revises: 0b21008389c4
Create Date: 2020-06-17 20:03:01.298651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535145082ebf'
down_revision = '0b21008389c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_properties_rules_rule_name', table_name='properties_rules')
    op.create_index(op.f('ix_properties_rules_rule_name'), 'properties_rules', ['rule_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_rules_rule_name'), table_name='properties_rules')
    op.create_index('ix_properties_rules_rule_name', 'properties_rules', ['rule_name'], unique=True)
    # ### end Alembic commands ###
