"""add case_property_id to workup

Revision ID: 538d44f6b009
Revises: 8f607c9b7098
Create Date: 2020-10-14 22:14:56.489570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '538d44f6b009'
down_revision = '8f607c9b7098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('case_property_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_single_cma_workups_case_property_id', 'single_sma_workups', 'case_property',
                          ['case_property_id'], ['id'])

    op.execute(
        '''
        update single_sma_workups
        set case_property_id = (
            select id from case_property where case_property.property_id = single_sma_workups.property_id
            limit 1
            )
        where property_id is not null;        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_single_cma_workups_case_property_id', 'single_sma_workups', type_='foreignkey')
    op.drop_column('single_sma_workups', 'case_property_id')
    # ### end Alembic commands ###
