"""null miamidade patio to 0

Revision ID: 53dd39e10e10
Revises: 2fab7ff65d80
Create Date: 2020-04-17 01:31:34.544014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dd39e10e10'
down_revision = '2fab7ff65d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- update miamidade 'patio_type'
        update property
        set patio_type = 0
        where patio_type is null
        and county = 'miamidade';
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
