"""add type to settings_ratios table

Revision ID: 5609172e70b6
Revises: c897d50690d1
Create Date: 2020-02-14 16:20:14.202170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5609172e70b6'
down_revision = 'c897d50690d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings_ratios', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings_ratios', 'type')
    # ### end Alembic commands ###
