"""update adjustments in properties rules table

Revision ID: 5896f85f2e2e
Revises: 9948f951613a
Create Date: 2020-03-06 01:51:57.231658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5896f85f2e2e'
down_revision = '9948f951613a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- update 'miamidade' adjustments
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,BEDROOMS,PATIO_TYPE,POOL,PAVING_TYPE}'
        where county = 'miamidade' and town = 'All';

        -- update 'broward' adjustments
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,BEDROOMS}'
        where county = 'broward' and town = 'All';
        
        -- update 'palmbeach' adjustments
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,HEAT_TYPE,GARAGE,POOL,PATIO_TYPE,PORCH_TYPE}'
        where county = 'palmbeach' and town = 'All';
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
