"""sender ip to case_application

Revision ID: 58e795c2f7e4
Revises: a6c02d1ca3ad
Create Date: 2020-05-27 03:20:54.648899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e795c2f7e4'
down_revision = 'a6c02d1ca3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('sender_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'sender_ip')
    # ### end Alembic commands ###
