"""add more inventory attributes to inventory_rules

Revision ID: 58f65642d044
Revises: a2d0b455f716
Create Date: 2020-02-24 21:56:19.781966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f65642d044'
down_revision = 'a2d0b455f716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rules', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('inventory_rules', sa.Column('heat_type', sa.String(), nullable=True))
    op.add_column('inventory_rules', sa.Column('patio_type', sa.Integer(), nullable=True))
    op.add_column('inventory_rules', sa.Column('paving_type', sa.Integer(), nullable=True))
    op.add_column('inventory_rules', sa.Column('pool', sa.Boolean(), nullable=True))
    op.add_column('inventory_rules', sa.Column('porch_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_rules', 'porch_type')
    op.drop_column('inventory_rules', 'pool')
    op.drop_column('inventory_rules', 'paving_type')
    op.drop_column('inventory_rules', 'patio_type')
    op.drop_column('inventory_rules', 'heat_type')
    op.drop_column('inventory_rules', 'bedrooms')
    # ### end Alembic commands ###
