"""recreate data_mappers

Revision ID: 58fad0247404
Revises: ac5233b23f56
Create Date: 2020-10-21 16:42:54.956336

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58fad0247404'
down_revision = 'ac5233b23f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_mappers',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('fields', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('name')
                    )

    petition_fields = {"apn": "Parcel ID", "petition_number": "PetitionNumber", "hearing_date": "HearingDate"}

    op.execute(
        '''
        INSERT INTO data_mappers (name, fields, created_at, updated_at) 
        VALUES ('petition', '{"apn": "Parcel ID", "petition_number": "PetitionNumber", "board_room": "BoardRoom", "hearing_date": "HearingDate"}', 
        NOW(), NULL ) 
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_mappers')
    # ### end Alembic commands ###
