"""fix florida assessment type

Revision ID: 59e3f68e475a
Revises: f574deb87fc3
Create Date: 2020-06-24 19:39:49.243444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e3f68e475a'
down_revision = 'f574deb87fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update assessment
        set assessment_type = 'final'
        where assessment_type in ('NAL', 'NAP')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
