"""add unit_number, unit_string to property, property_original tables

Revision ID: 5a44b28d6bdd
Revises: 995f215d8c57
Create Date: 2020-05-30 01:32:42.221304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a44b28d6bdd'
down_revision = '995f215d8c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('unit_number', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('unit_string', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('unit_number', sa.Integer(), nullable=True))
    op.add_column('property_original', sa.Column('unit_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'unit_string')
    op.drop_column('property_original', 'unit_number')
    op.drop_column('property', 'unit_string')
    op.drop_column('property', 'unit_number')
    # ### end Alembic commands ###
