"""add other adjustment to property

Revision ID: 5b2263dfbc6f
Revises: 5d5ee7e23793
Create Date: 2020-10-02 01:51:35.983427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2263dfbc6f'
down_revision = '5d5ee7e23793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('other_adjustment', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('other_adjustment_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'other_adjustment_description')
    op.drop_column('property', 'other_adjustment')

    # ### end Alembic commands ###
