"""add takeover type to case_application_type table

Revision ID: 5b35080568dd
Revises: f633a321c2e6
Create Date: 2020-05-27 18:37:18.438308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b35080568dd'
down_revision = 'f633a321c2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_application_type (id, name, description) VALUES (3, 'takeover', 'Takeover');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_application_type WHERE id=3;
        '''
    )
    # ### end Alembic commands ###
