"""empty message

Revision ID: 5c4a44dee0e2
Revises: bf944115fb0d
Create Date: 2020-01-07 08:53:29.224673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4a44dee0e2'
down_revision = 'bf944115fb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('adjustments_all', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties_rules', sa.Column('adjustments_required', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'adjustments_required')
    op.drop_column('properties_rules', 'adjustments_all')
    # ### end Alembic commands ###
