"""add property_gis table

Revision ID: 5ca7d5267643
Revises: c9d2f8cd5523
Create Date: 2020-04-07 02:19:20.131375

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca7d5267643'
down_revision = 'c9d2f8cd5523'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_gis',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('county', sa.String(), nullable=True),
                    sa.Column('apn', sa.String(), nullable=True),
                    sa.Column('geometry', geoalchemy2.types.Geometry(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_gis')
    # ### end Alembic commands ###
