"""create case_note_sender table

Revision ID: 5cb21306cc9e
Revises: 8acc7f630c70
Create Date: 2020-05-20 14:42:59.543551

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5cb21306cc9e'
down_revision = '8acc7f630c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_note_sender',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('fk_CaseApplication_case_client_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_case_application_client_id', 'case_application', 'case_client', ['client_id'], ['id'])
    op.add_column('case_note', sa.Column('sender', sa.Integer(), nullable=True))
    op.add_column('case_note', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_CaseNote_case_application_id', 'case_note', type_='foreignkey')
    op.create_foreign_key('fk_case_note_sender', 'case_note', 'case_note_sender', ['sender'], ['id'])
    op.drop_column('case_note', 'application_id')

    op.execute(
        '''
        INSERT INTO case_note_sender (id, name) VALUES (1, 'Application');
        INSERT INTO case_note_sender (id, name) VALUES (2, 'Client');
        INSERT INTO case_note_sender (id, name) VALUES (3, 'Property');
        INSERT INTO case_note_sender (id, name) VALUES (4, 'Assessment');
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_case_note_sender', 'case_note', type_='foreignkey')
    op.create_foreign_key('fk_CaseNote_case_application_id', 'case_note', 'case_application', ['application_id'],
                          ['id'], onupdate='CASCADE')
    op.drop_column('case_note', 'sender_id')
    op.drop_column('case_note', 'sender')
    op.drop_constraint('fk_case_application_client_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_CaseApplication_case_client_id', 'case_application', 'case_client', ['client_id'], ['id'],
                          onupdate='CASCADE')
    op.drop_table('case_note_sender')
    # ### end Alembic commands ###
