"""add year field to PropertiesRules table

Revision ID: 60c711d4fb0b
Revises: 5609172e70b6
Create Date: 2020-02-18 17:49:43.458635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c711d4fb0b'
down_revision = '5609172e70b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'year')
    # ### end Alembic commands ###
