"""rule_set last_updated

Revision ID: 60d7846e510d
Revises: d6caf79af7dd
Create Date: 2020-01-15 00:09:30.435218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d7846e510d'
down_revision = 'd6caf79af7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'last_updated')
    # ### end Alembic commands ###
