"""migrate payment status, payment type from client to cases

Revision ID: 61b2c6d2978e
Revises: d657e9213252
Create Date: 2020-07-30 23:04:59.698980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b2c6d2978e'
down_revision = 'd657e9213252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
            UPDATE case_property cp
            SET
                payment_type_id = cc.payment_type_id,
                payment_status_id = cc.payment_status_id
            FROM case_client cc
            WHERE cp.client_id = cc.id
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
