"""assessment_files names prefix

Revision ID: 634ec36c9b13
Revises: 0255381b2f0c
Create Date: 2020-03-18 17:39:24.704073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634ec36c9b13'
down_revision = '0255381b2f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE assessment_files set file_name = 'final_2019/' || file_name where assessment_date_id = 1;
    UPDATE assessment_files set file_name = 'tentative_2020/' || file_name where assessment_date_id = 6;
    UPDATE assessment_files set file_name = 'tentative_2019/' || file_name where assessment_date_id = 7;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE assessment_files set file_name = LTRIM(file_name, 'final_2019/') where assessment_date_id = 1;
    UPDATE assessment_files set file_name = LTRIM(file_name, 'tentative_2020/') where assessment_date_id = 6;
    UPDATE assessment_files set file_name = LTRIM(file_name, 'tentative_2019/') where assessment_date_id = 7;
    ''')
    # ### end Alembic commands ###
