"""add move payment from case_property to case_client

Revision ID: 643bbb50b104
Revises: c00c97b1104a
Create Date: 2020-07-07 11:27:11.395977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643bbb50b104'
down_revision = 'c00c97b1104a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('payment_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_case_client_payment_type_id', 'case_client', 'case_payment_type', ['payment_type_id'], ['id'])

    # move payment data from case_property to case_client table
    op.execute(
        '''
        UPDATE case_client
        SET payment_type_id = case_property.payment_type_id
        FROM case_property
        WHERE case_client.id = case_property.id;
        '''
    )
    op.drop_constraint('fk_case_property_payment_type_id', 'case_property', type_='foreignkey')
    op.drop_column('case_property', 'payment_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property', sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_case_property_payment_type_id', 'case_property', 'case_payment_type', ['payment_type_id'], ['id'])

    # move payment from case_client to case_property
    op.execute(
        '''
        UPDATE case_property
        SET payment_type_id = case_client.payment_type_id
        FROM case_client
        WHERE case_property.id = case_client.id;
        '''
    )

    op.drop_constraint('fk_case_client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'payment_type_id')
    # ### end Alembic commands ###
