"""add marketing code id 6

Revision ID: 64f5d86968ea
Revises: 6edd59291510
Create Date: 2020-08-15 22:13:19.845363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64f5d86968ea'
down_revision = '6edd59291510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_marketing_code (id, name) VALUES (6, 'DM Miami Dade Broward 12,000 #2');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_marketing_code WHERE id=6;
        '''
    )
    # ### end Alembic commands ###
