"""add fully rejected application status

Revision ID: 655dd03503d3
Revises: 089c5952f166
Create Date: 2020-05-16 00:43:28.486205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655dd03503d3'
down_revision = '089c5952f166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_application_status (id, name) VALUES (4, 'Fully Rejected');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_application_status WHERE id=4;
        '''
    )
    # ### end Alembic commands ###
