"""empty message

Revision ID: 65c9dd69cd4d
Revises: 5a9b082e6ae6
Create Date: 2019-12-14 17:39:38.306384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c9dd69cd4d'
down_revision = '5a9b082e6ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
