"""fix application contract agreement note type

Revision ID: 6761e2541db3
Revises: 1b0f5c720074
Create Date: 2020-09-10 00:35:15.206950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6761e2541db3'
down_revision = '1b0f5c720074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update case_note
        set type_id=13
        where type_id=3
        and text='Contract Agreement Attachment was sent'
        and sender=1;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update case_note
        set type_id=3
        where type_id=13
        and text='Contract Agreement Attachment was sent'
        and sender=1;
        '''
    )
    # ### end Alembic commands ###
