"""create case_application table

Revision ID: 679fa2cf08f5
Revises: 106c47edaf6e
Create Date: 2020-04-17 23:15:15.097974

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '679fa2cf08f5'
down_revision = '106c47edaf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('company_serving_id', sa.Integer(), nullable=True),
                    sa.Column('property_address', sa.String(), nullable=True),
                    sa.Column('scan', sa.String(), nullable=True),
                    sa.Column('region', sa.String(), nullable=True),
                    sa.Column('tax_year', sa.Integer(), nullable=True),
                    sa.Column('marketing_code', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('mailing_address', sa.String(), nullable=True),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
                    sa.Column('_phone_number', sa.Unicode(length=20), nullable=True),
                    sa.Column('country_code', sa.Unicode(length=8), nullable=True),
                    sa.ForeignKeyConstraint(['company_serving_id'], ['case_company_serving.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_application')
    # ### end Alembic commands ###
