"""case management unique constraints

Revision ID: 69fa5c7c1324
Revises: c49b1442e5e3
Create Date: 2020-04-24 14:22:08.536122

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '69fa5c7c1324'
down_revision = 'c49b1442e5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'application_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('uc_CaseApplication_first_name_last_name_email', 'case_application',
                                ['first_name', 'last_name', 'email'])
    op.alter_column('case_application_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('case_client', 'client_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('case_client', 'email_alerts',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('case_client', 'sms_alerts',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.create_unique_constraint('uc_CaseClient_first_name_last_name_email', 'case_client',
                                ['first_name', 'last_name', 'email'])
    op.alter_column('case_client_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('case_note', 'note_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('case_note_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_note_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('case_note', 'note_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('case_client_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_constraint('uc_CaseClient_first_name_last_name_email', 'case_client', type_='unique')
    op.alter_column('case_client', 'sms_alerts',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('case_client', 'email_alerts',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('case_client', 'client_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('case_application_type', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_constraint('uc_CaseApplication_first_name_last_name_email', 'case_application', type_='unique')
    op.alter_column('case_application', 'application_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
