"""fireplace to inventory rule

Revision ID: 6abffafc627c
Revises: 6fcdc945e755
Create Date: 2020-05-21 01:14:53.755679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abffafc627c'
down_revision = '6fcdc945e755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rules', sa.Column('fireplace', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_rules', 'fireplace')
    # ### end Alembic commands ###
