"""add condo_view_location, condo_view_influence to property

Revision ID: 6b91875883c9
Revises: 735ab870565a
Create Date: 2020-07-11 01:46:24.299464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b91875883c9'
down_revision = '735ab870565a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('condo_view_influence', sa.String(), nullable=True))
    op.add_column('property', sa.Column('condo_view_location', sa.Integer(), nullable=True))
    op.add_column('property_original', sa.Column('condo_view_influence', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('condo_view_location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'condo_view_location')
    op.drop_column('property_original', 'condo_view_influence')
    op.drop_column('property', 'condo_view_location')
    op.drop_column('property', 'condo_view_influence')
    # ### end Alembic commands ###
