"""add cma payload to single_cma_workups table

Revision ID: 6e094e13f1b0
Revises: 03fbfc39e597
Create Date: 2020-10-04 18:14:20.304607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e094e13f1b0'
down_revision = '03fbfc39e597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('cma_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_sma_workups', 'cma_payload')
    # ### end Alembic commands ###
