"""add email sent note type

Revision ID: 6edd59291510
Revises: 3c13170a4d18
Create Date: 2020-08-11 17:36:01.730969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edd59291510'
down_revision = '3c13170a4d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (12, 'System', 'email_sent');
        UPDATE case_note_type SET action = 'email_bounced' WHERE id = 8;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id = 12;
        UPDATE case_note_type SET action = 'bounced' WHERE id = 8;
        '''
    )
    # ### end Alembic commands ###
