"""adjust mailing address new requirements

Revision ID: 6fcdc945e755
Revises: d6ef36c760dc
Create Date: 2020-05-17 23:22:07.964349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcdc945e755'
down_revision = 'd6ef36c760dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('mailing_address', sa.String(), nullable=True))
    op.drop_column('case_application', 'mailing_address_1')
    op.drop_column('case_application', 'mailing_address_2')
    op.add_column('case_client', sa.Column('mailing_address', sa.String(), nullable=True))
    op.drop_column('case_client', 'mailing_address_1')
    op.drop_column('case_client', 'mailing_address_2')
    # op.drop_index('owner_data_source_index', table_name='owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('mailing_address_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('mailing_address_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'mailing_address')
    op.add_column('case_application', sa.Column('mailing_address_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('mailing_address_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'mailing_address')
    # ### end Alembic commands ###
