"""empty message

Revision ID: 71d6f16641e2
Revises: 8c61c4f57dc4
Create Date: 2020-01-26 20:23:43.324199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d6f16641e2'
down_revision = '8c61c4f57dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=17, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_ratios_year'), 'settings_ratios', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_ratios_year'), table_name='settings_ratios')
    op.drop_table('settings_ratios')
    # ### end Alembic commands ###
