"""add percent to lot_size column names in selection_rules table

Revision ID: 72ec5eaa4f9d
Revises: 8d2cf6b198b9
Create Date: 2020-02-23 19:49:32.357477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72ec5eaa4f9d'
down_revision = '8d2cf6b198b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selection_rules', sa.Column('percent_lot_size_higher', sa.Float(), nullable=True))
    op.add_column('selection_rules', sa.Column('percent_lot_size_lower', sa.Float(), nullable=True))
    op.drop_column('selection_rules', 'lot_size_lower')
    op.drop_column('selection_rules', 'lot_size_higher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selection_rules', sa.Column('lot_size_higher', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('selection_rules', sa.Column('lot_size_lower', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('selection_rules', 'percent_lot_size_lower')
    op.drop_column('selection_rules', 'percent_lot_size_higher')
    # ### end Alembic commands ###
