"""add new miamidade assessment file into assessment_files

Revision ID: 735ab870565a
Revises: b9b8fef46c3a
Create Date: 2020-07-10 15:43:32.235278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735ab870565a'
down_revision = 'b9b8fef46c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO assessment_files (assessment_date_id, file_name) 
        VALUES (10, 'MunRoll - 00 RE - All Properties.csv') 
        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM assessment_files
        WHERE assessment_date_id = 10
        AND file_name = 'MunRoll - 00 RE - All Properties.csv'
        '''
    )
    # ### end Alembic commands ###
