"""rename scan_base64_encoded, signature_base64_encoded in case_application table

Revision ID: 75114a12df00
Revises: 5a7e80dca496
Create Date: 2020-05-12 13:20:31.473515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75114a12df00'
down_revision = '5a7e80dca496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('scan_base64_encoded', sa.LargeBinary(), nullable=True))
    op.add_column('case_application', sa.Column('signature_base64_encoded', sa.LargeBinary(), nullable=False))
    op.drop_column('case_application', 'signature_encoded')
    op.drop_column('case_application', 'scan_encoded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('scan_encoded', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('signature_encoded', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('case_application', 'signature_base64_encoded')
    op.drop_column('case_application', 'scan_base64_encoded')
    # ### end Alembic commands ###
