"""added condition, story_height columns in property table

Revision ID: 758e5872ce57
Revises: 08a00f8f590d
Create Date: 2020-01-10 16:59:33.842625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758e5872ce57'
down_revision = '08a00f8f590d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('property', sa.Column('story_height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'story_height')
    op.drop_column('property', 'condition')
    # ### end Alembic commands ###
