"""change pool type to integer in inventory rules

Revision ID: 76d098bb1921
Revises: c0bf0e78c4f3
Create Date: 2020-03-05 17:41:48.394115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d098bb1921'
down_revision = 'c0bf0e78c4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('inventory_rules', 'pool', existing_type=sa.BOOLEAN(), type_=sa.Integer(), existing_nullable=True)

    op.execute(
        '''
        alter table inventory_rules alter column pool type int using pool::int;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_rules', 'pool', existing_type=sa.Integer(), type_=sa.BOOLEAN(), existing_nullable=True)
    # ### end Alembic commands ###
