"""create payment_type table

Revision ID: 7b9d011ce507
Revises: b6d66bb15939
Create Date: 2020-05-19 00:14:24.142787

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7b9d011ce507'
down_revision = 'b6d66bb15939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_payment_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('payment_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_case_application_payment_type_id', 'case_application', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_application_payment_type_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'payment_type_id')
    op.drop_table('case_payment_type')
    # ### end Alembic commands ###
