"""added property print key

Revision ID: 7be0bcd33489
Revises: 11f206cffda6
Create Date: 2019-12-29 23:17:34.486106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be0bcd33489'
down_revision = '11f206cffda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('print_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'print_key')
    # ### end Alembic commands ###
