"""unique tag name

Revision ID: 7ce2578d5998
Revises: 00276e4641c3
Create Date: 2020-05-02 17:40:26.909469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce2578d5998'
down_revision = '00276e4641c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_case_tag_name', 'case_tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_case_tag_name', 'case_tag', type_='unique')
    # ### end Alembic commands ###
