"""remove evidence_file from workup

Revision ID: 7e09f7db8a1e
Revises: 0fc891b5a7ee
Create Date: 2020-10-06 17:45:28.804687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e09f7db8a1e'
down_revision = '0fc891b5a7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_single_cma_workups_evidence_file_id', 'single_sma_workups', type_='foreignkey')
    op.drop_column('single_sma_workups', 'evidence_file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('evidence_file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_single_cma_workups_evidence_file_id', 'single_sma_workups', 'files', ['evidence_file_id'], ['id'])
    # ### end Alembic commands ###
