"""add mailing city, zip, state fiels to ContactInfoMixin

Revision ID: 7e19a120201c
Revises: 68a046d2aae1
Create Date: 2020-05-11 13:57:36.373324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e19a120201c'
down_revision = '68a046d2aae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('mailing_city', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_state', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_zip_code', sa.Integer(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_city', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_state', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'mailing_zip_code')
    op.drop_column('case_client', 'mailing_state')
    op.drop_column('case_client', 'mailing_city')
    op.drop_column('case_application', 'mailing_zip_code')
    op.drop_column('case_application', 'mailing_state')
    op.drop_column('case_application', 'mailing_city')
    # ### end Alembic commands ###
