"""add case_application_type table

Revision ID: 7e3e94dca267
Revises: 679fa2cf08f5
Create Date: 2020-04-17 23:21:27.458286

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7e3e94dca267'
down_revision = '679fa2cf08f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('application_type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('application_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_CaseApplication_case_application_type_id',
        'case_application', 'case_application_type',
        ['application_type_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseApplication_case_application_type_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'application_type_id')
    op.drop_table('case_application_type')
    # ### end Alembic commands ###
