"""add reference property to case_application

Revision ID: 7e54c7c9e967
Revises: b1b0be510fef
Create Date: 2020-05-13 14:32:06.090482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e54c7c9e967'
down_revision = 'b1b0be510fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseApplication_property_id', 'case_application', 'property', ['property_id'], ['id'],
                          onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseApplication_property_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'property_id')
    # ### end Alembic commands ###
