"""add address gin index to property table

Revision ID: 813509ba021a
Revises: f8c526863b37
Create Date: 2020-05-23 15:17:13.184281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813509ba021a'
down_revision = 'f8c526863b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
            CREATE INDEX property_address_gin_idx ON property USING GIN (to_tsvector('english', address));
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DROP INDEX property_address_gin_idx;
        '''
    )
    # ### end Alembic commands ###
