"""fix nassau assessment type to tent

Revision ID: 817114474a37
Revises: caba32a41a3f
Create Date: 2020-12-15 03:20:39.790163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '817114474a37'
down_revision = 'caba32a41a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE assessment_dates SET assessment_type = 2 WHERE id = 9;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE assessment_dates SET assessment_type = 1 WHERE id = 9;
        '''
    )
    # ### end Alembic commands ###
