"""renaming column

Revision ID: 836c1c1496e6
Revises: 8b5bc36b6a9f
Create Date: 2020-07-22 16:50:09.339729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836c1c1496e6'
down_revision = '8b5bc36b6a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
