"""cmatask county name and description

Revision ID: 84171bd315c3
Revises: 06fb66b640af
Create Date: 2020-01-13 17:18:54.245095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84171bd315c3'
down_revision = '06fb66b640af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cma_task', sa.Column('county_name', sa.String(), nullable=True))
    op.add_column('cma_task', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_cma_task_county_name'), 'cma_task', ['county_name'], unique=False)
    op.drop_column('cma_task', 'params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cma_task', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cma_task_county_name'), table_name='cma_task')
    op.drop_column('cma_task', 'description')
    op.drop_column('cma_task', 'county_name')
    # ### end Alembic commands ###
