"""empty message

Revision ID: 855fa731604f
Revises: 65c9dd69cd4d
Create Date: 2019-12-15 10:10:30.484490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855fa731604f'
down_revision = '65c9dd69cd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
