"""add age adjustment coeff column to properties_rules

Revision ID: 8578f28cbc6a
Revises: 58fad0247404
Create Date: 2020-10-27 18:55:20.694344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8578f28cbc6a'
down_revision = '58fad0247404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('age', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'age')
    # ### end Alembic commands ###
