"""phone number, cell_phone types in contact info mixin

Revision ID: 859f817b4707
Revises: e3a15d2a0448
Create Date: 2020-04-20 03:10:42.465561

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859f817b4707'
down_revision = 'e3a15d2a0448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', '_phone_number')
    op.drop_column('case_application', '_cell_phone')
    op.drop_column('case_client', '_phone_number')
    op.drop_column('case_client', '_cell_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('_cell_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('_cell_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
