"""add case_assessment, case_property tables

Revision ID: 86b07e0ce907
Revises: 7e3e94dca267
Create Date: 2020-04-18 22:45:50.449903

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '86b07e0ce907'
down_revision = '7e3e94dca267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_assessment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tax_year', sa.Integer(), nullable=True),
                    sa.Column('fee_percent', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('case_property',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('case_client_id', sa.Integer(), nullable=True),
                    sa.Column('full_address', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['case_client_id'], ['case_client.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseApplication_case_client_id', 'case_application', 'case_client', ['client_id'], ['id'])
    op.add_column('case_client', sa.Column('default_fee_percent', sa.Integer(), nullable=True))
    op.drop_column('case_client', 'default_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('default_fee', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'default_fee_percent')
    op.drop_constraint('fk_CaseApplication_case_client_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'client_id')
    op.drop_table('case_property')
    op.drop_table('case_assessment')
    # ### end Alembic commands ###
