"""add order to case_property_status table

Revision ID: 8855e1cc8230
Revises: 34c6ea562ce3
Create Date: 2020-07-08 19:03:18.239799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8855e1cc8230'
down_revision = '34c6ea562ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property_status', sa.Column('status_order', sa.Integer(), nullable=True))

    op.execute(
        '''
        UPDATE case_property_status
        SET status_order = 1
        WHERE id = 1;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_property_status', 'status_order')
    # ### end Alembic commands ###
