"""add sign_email_sent_at to application

Revision ID: 888b250bde90
Revises: 3c4bcc1aaf5f
Create Date: 2020-08-26 21:04:43.175636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888b250bde90'
down_revision = '3c4bcc1aaf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('sign_email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'sign_email_sent_at')
    # ### end Alembic commands ###
