"""token and email confirmed at to case_application table

Revision ID: 8b5bc36b6a9f
Revises: 2e81db286047
Create Date: 2020-07-22 03:46:10.422759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5bc36b6a9f'
down_revision = '2e81db286047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('case_application', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'token')
    op.drop_column('case_application', 'email_confirmed_at')
    # ### end Alembic commands ###
