"""same_one_family_types to boolean

Revision ID: 8c61c4f57dc4
Revises: ac39a87d6bf2
Create Date: 2020-01-23 00:12:31.974167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c61c4f57dc4'
down_revision = 'ac39a87d6bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''alter table selection_rules drop column same_one_family_types;
''')
    op.execute('''alter table selection_rules add same_one_family_types bool default null;
               ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selection_rules', 'same_one_family_types',
                    existing_type=sa.Boolean(),
                    type_=postgresql.ARRAY(sa.VARCHAR()),
                    existing_nullable=True)
    # ### end Alembic commands ###
