"""indexing search fields in property model

Revision ID: 8cd19c3aba58
Revises: ff7a23c97fa9
Create Date: 2020-03-28 01:38:14.100536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd19c3aba58'
down_revision = 'ff7a23c97fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_property_address'), 'property', ['address'], unique=False)
    op.create_index(op.f('ix_property_block'), 'property', ['block'], unique=False)
    op.create_index(op.f('ix_property_lot'), 'property', ['lot'], unique=False)
    op.create_index(op.f('ix_property_school_district'), 'property', ['school_district'], unique=False)
    op.create_index(op.f('ix_property_section'), 'property', ['section'], unique=False)
    op.create_index(op.f('ix_property_number'), 'property', ['number'], unique=False)
    op.create_index(op.f('ix_property_state'), 'property', ['state'], unique=False)
    op.create_index(op.f('ix_property_street'), 'property', ['street'], unique=False)
    op.create_index(op.f('ix_property_village'), 'property', ['village'], unique=False)
    op.create_index(op.f('ix_property_zip'), 'property', ['zip'], unique=False)
    op.create_index(op.f('ix_property_town'), 'property', ['town'], unique=False)

    op.create_index(op.f('ix_property_overridden_address'), 'property_overridden', ['address'], unique=False)
    op.create_index(op.f('ix_property_overridden_block'), 'property_overridden', ['block'], unique=False)
    op.create_index(op.f('ix_property_overridden_lot'), 'property_overridden', ['lot'], unique=False)
    op.create_index(op.f('ix_property_overridden_school_district'), 'property_overridden', ['school_district'], unique=False)
    op.create_index(op.f('ix_property_overridden_section'), 'property_overridden', ['section'], unique=False)
    op.create_index(op.f('ix_property_overridden_number'), 'property_overridden', ['number'], unique=False)
    op.create_index(op.f('ix_property_overridden_state'), 'property_overridden', ['state'], unique=False)
    op.create_index(op.f('ix_property_overridden_street'), 'property_overridden', ['street'], unique=False)
    op.create_index(op.f('ix_property_overridden_village'), 'property_overridden', ['village'], unique=False)
    op.create_index(op.f('ix_property_overridden_zip'), 'property_overridden', ['zip'], unique=False)
    op.create_index(op.f('ix_property_overridden_town'), 'property_overridden', ['town'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_section'), table_name='property')
    op.drop_index(op.f('ix_property_school_district'), table_name='property')
    op.drop_index(op.f('ix_property_lot'), table_name='property')
    op.drop_index(op.f('ix_property_block'), table_name='property')
    op.drop_index(op.f('ix_property_address'), table_name='property')
    op.drop_index(op.f('ix_property_zip'), table_name='property')
    op.drop_index(op.f('ix_property_village'), table_name='property')
    op.drop_index(op.f('ix_property_street'), table_name='property')
    op.drop_index(op.f('ix_property_state'), table_name='property')
    op.drop_index(op.f('ix_property_number'), table_name='property')
    op.drop_index(op.f('ix_property_town'), table_name='property')

    op.drop_index(op.f('ix_property_overridden_section'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_school_district'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_lot'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_block'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_address'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_zip'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_village'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_street'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_state'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_number'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_town'), table_name='property_overridden')

    # ### end Alembic commands ###
