"""rename TIME to TIME_ADJ in properties_rules table

Revision ID: 8cf8814baa0a
Revises: f2b69d97e41e
Create Date: 2020-03-13 23:32:55.315950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf8814baa0a'
down_revision = 'f2b69d97e41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,GARAGE,BASEMENT,TIME_ADJ,LOCATION}'
        where county = 'nassau' and town = 'All';
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
