"""village at properties_rules

Revision ID: 8d2cf6b198b9
Revises: 5581fc608abe
Create Date: 2020-02-21 19:37:45.699428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2cf6b198b9'
down_revision = '5581fc608abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('village', sa.String(), nullable=True))
    op.drop_constraint('area_composite', 'properties_rules', type_='unique')
    op.create_unique_constraint('area_composite', 'properties_rules', ['county', 'town', 'village'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('area_composite', 'properties_rules', type_='unique')
    op.create_unique_constraint('area_composite', 'properties_rules', ['town', 'county'])
    op.drop_column('properties_rules', 'village')
    # ### end Alembic commands ###
