"""allow viewer single cma

Revision ID: 8d40a3689d7a
Revises: 926d4a79ae8b
Create Date: 2020-08-02 17:17:52.815983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d40a3689d7a'
down_revision = '926d4a79ae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE role
    SET permissions = 9
    WHERE name = 'viewer';
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE role
    SET permissions = 1
    WHERE name = 'viewer';
    ''')
    # ### end Alembic commands ###
