"""reference_building column

Revision ID: 8dbddabbbf91
Revises: c498e5b02364
Create Date: 2020-05-12 00:32:12.458099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbddabbbf91'
down_revision = 'c498e5b02364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('reference_building', sa.Integer(), nullable=True))
    op.create_foreign_key('property_reference_building_fkey', 'property', 'property', ['reference_building'], ['id'])
    op.add_column('property_original', sa.Column('reference_building', sa.Integer(), nullable=True))
    op.create_foreign_key('property_original_reference_building_fkey',
                          'property_original', 'property', ['reference_building'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_original_reference_building_fkey',
                       'property_original', type_='foreignkey')
    op.drop_column('property_original', 'reference_building')
    op.drop_constraint('property_reference_building_fkey', 'property', type_='foreignkey')
    op.drop_column('property', 'reference_building')
    # ### end Alembic commands ###
