"""create email table

Revision ID: 8ddc3fd9843e
Revises: 0627ab60f0a9
Create Date: 2020-07-25 20:50:46.523438

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8ddc3fd9843e'
down_revision = '0627ab60f0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_email_originator',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('case_email',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email_address', sa.String(), nullable=True),
                    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
                    sa.Column('originated_from_id', sa.Integer(), nullable=True),
                    sa.Column('failed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['originated_from_id'], ['case_email_originator.id'],
                                            name='fk_case_email_originator_originated_from_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute(
        '''
        INSERT INTO case_email_originator (id, name) VALUES (1, 'application');
        INSERT INTO case_email_originator (id, name) VALUES (2, 'manual_edit_application');
        INSERT INTO case_email_originator (id, name) VALUES (3, 'manual_edit_client');
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_email')
    op.drop_table('case_email_originator')
    # ### end Alembic commands ###
