"""assessment ratios table

Revision ID: 8e3568fe768f
Revises: 97968511b59f
Create Date: 2019-12-19 17:23:55.021241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e3568fe768f'
down_revision = '97968511b59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=False),
    sa.Column('town_code', sa.Integer(), nullable=False),
    sa.Column('town_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    op.drop_table('assessment_ratio')
    # ### end Alembic commands ###
