"""add land_type_code

Revision ID: 8f196b60e829
Revises: ac017659756d
Create Date: 2020-07-08 17:30:40.206666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f196b60e829'
down_revision = 'ac017659756d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('land_type_code', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('land_type_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'land_type_code')
    op.drop_column('property', 'land_type_code')
    # ### end Alembic commands ###
