"""add reference property to property_county table

Revision ID: 8fe1c3b36e9d
Revises: 8233a8f7632c
Create Date: 2020-08-02 23:09:42.915678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe1c3b36e9d'
down_revision = '8233a8f7632c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_Property_property_county_id', 'property', 'property_county', ['county'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_PropertyOriginal_property_county_id', 'property_original', 'property_county', ['county'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_PropertyOriginal_property_county_id', 'property_original', type_='foreignkey')
    op.drop_constraint('fk_Property_property_county_id', 'property', type_='foreignkey')
    # ### end Alembic commands ###
