"""palmbeach assessments assessment_id update

Revision ID: 92001734fb43
Revises: c9d2f8cd5523
Create Date: 2020-04-08 20:33:24.271852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92001734fb43'
down_revision = 'c9d2f8cd5523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute('''
    UPDATE assessment AS a
    SET assessment_id = 3
    FROM property AS p
    WHERE a.property_id = p.id
      AND p.county = 'palmbeach'
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
