"""fix palmbeach patio

Revision ID: 926a8aaac137
Revises: 53dd39e10e10
Create Date: 2020-04-17 01:41:16.104214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926a8aaac137'
down_revision = '53dd39e10e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- 0 --> 1
        update property
        set patio_type = 1
        where patio_type = 0
        and county = 'palmbeach';
        '''
    )

    op.execute(
        '''
        -- null --> 0
        update property
        set patio_type = 0
        where patio_type is null
        and county = 'palmbeach';
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
