"""selection rules and properties rules update

Revision ID: 93b4d66561d1
Revises: abcd77944dbd
Create Date: 2020-03-04 16:32:21.814680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b4d66561d1'
down_revision = 'abcd77944dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('''
    update selection_rules
    set sale_days_before_assessment = 1000,
        percent_gla_lower=31,
        percent_sale_lower=31,
        percent_lot_size_higher=115,
        percent_lot_size_lower=80 where parent_id = 42;
    
    update properties_rules
    set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,GARAGE,BASEMENT,TIME}'
    where county='nassau' and town = 'All';
    
    delete from time_adjustments;
    
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (1, 'nassau', 2019, 3, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (2, 'nassau', 2019, 4, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (3, 'nassau', 2019, 5, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (4, 'nassau', 2019, 6, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (6, 'nassau', 2019, 8, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (7, 'nassau', 2018, 8, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (9, 'nassau', 2018, 9, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (10, 'broward', 2018, 1, 0.5);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (11, 'broward', 2018, 2, 1.5);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (12, 'broward', 2018, 3, -0.3);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (13, 'broward', 2018, 4, 0.6);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (14, 'broward', 2018, 5, 1.6);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (15, 'broward', 2018, 6, 3.2);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (16, 'broward', 2019, 6, 3.1);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (18, 'broward', 2019, 7, 4);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (19, 'broward', 2019, 8, 5.2);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (21, 'broward', 2019, 9, 2.4);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (22, 'broward', 2019, 10, 2.2);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (23, 'palmbeach', 2019, 10, 2);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (24, 'palmbeach', 2019, 8, 2);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (25, 'palmbeach', 2019, 6, 1);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (26, 'palmbeach', 2019, 4, 6.1);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (27, 'nassau', 2020, 4, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (28, 'nassau', 2020, 3, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (29, 'nassau', 2020, 5, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (30, 'nassau', 2020, 2, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (31, 'nassau', 2019, 12, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (32, 'nassau', 2020, 1, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (33, 'nassau', 2019, 9, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (34, 'nassau', 2019, 11, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (35, 'nassau', 2019, 10, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (36, 'nassau', 2019, 7, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (37, 'nassau', 2019, 2, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (38, 'nassau', 2019, 1, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (39, 'nassau', 2018, 12, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (40, 'nassau', 2018, 10, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (41, 'nassau', 2018, 11, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (42, 'nassau', 2018, 7, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (43, 'nassau', 2018, 6, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (44, 'nassau', 2018, 4, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (45, 'nassau', 2018, 5, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (46, 'nassau', 2018, 3, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (47, 'nassau', 2018, 2, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (48, 'nassau', 2018, 1, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (49, 'nassau', 2017, 12, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (50, 'nassau', 2017, 11, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (51, 'nassau', 2017, 10, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (52, 'nassau', 2017, 9, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (53, 'nassau', 2017, 8, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (54, 'nassau', 2017, 7, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (55, 'nassau', 2017, 6, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (56, 'nassau', 2017, 5, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (57, 'nassau', 2017, 4, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (58, 'nassau', 2017, 2, 0.75);
INSERT INTO time_adjustments (id, county, year, month, value) VALUES (59, 'nassau', 2017, 3, 0.75);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###
