"""user roles

Revision ID: 93febfbe02f9
Revises: da023fe42564
Create Date: 2020-05-07 17:36:04.924835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93febfbe02f9'
down_revision = 'da023fe42564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users',
    #               sa.Column('role_id', sa.Integer(), nullable=False, default=4)
    #               )
    op.execute('''
    alter table users
	add role_id int default 4 not null;
    update users set role_id = 1;
    update users set role_id = 4 where email = 'rustamallakov@gmail.com';
    DROP TABLE roles_users;
    ''')
    op.create_foreign_key('users_role_id_fkey', 'users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
