"""null paving to 0 for miamidade county

Revision ID: 953a2152fa89
Revises: 926a8aaac137
Create Date: 2020-04-17 01:56:07.725488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953a2152fa89'
down_revision = '926a8aaac137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        -- null --> 0
        update property
        set paving_type = 0
        where paving_type is null        
        and county = 'miamidade';
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
