"""make all applicatins physical

Revision ID: 95d99876e0f4
Revises: 1f8cc8636381
Create Date: 2020-06-03 01:41:21.876362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d99876e0f4'
down_revision = '1f8cc8636381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application
        SET source_id=1
        WHERE source_id=2
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
