"""rename application source from Digital to Online

Revision ID: 971349c9e120
Revises: 52c898f54a25
Create Date: 2020-06-29 12:36:40.713150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971349c9e120'
down_revision = '52c898f54a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application_source
        SET name = 'Online'
        WHERE id = 2
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application_source
        SET name = 'Digital'
        WHERE id = 2
        '''
    )
    # ### end Alembic commands ###
