"""add created note type

Revision ID: 9733d894586d
Revises: 8fe1c3b36e9d
Create Date: 2020-08-04 09:28:31.485648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9733d894586d'
down_revision = '8fe1c3b36e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (11, 'System', 'created');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id=11;
        '''
    )
    # ### end Alembic commands ###
