"""remove tax_year from case_client table

Revision ID: 97ae31e87c56
Revises: 5b35080568dd
Create Date: 2020-05-28 21:36:23.940987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ae31e87c56'
down_revision = '5b35080568dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'tax_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('tax_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
