"""unique not null data source name

Revision ID: 97e59e58b414
Revises: 64210ba4c65d
Create Date: 2020-10-16 21:57:36.213400

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '97e59e58b414'
down_revision = '64210ba4c65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_mappers', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_unique_constraint('uq_data_mappers_name', 'data_mappers', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_data_mappers_name', 'data_mappers', type_='unique')
    op.alter_column('data_mappers', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
