"""district to property table

Revision ID: 980aeb472420
Revises: 82c7be0f4e2d
Create Date: 2020-11-06 21:16:56.044651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980aeb472420'
down_revision = '82c7be0f4e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('district', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('district', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'district')
    op.drop_column('property', 'district')
    # ### end Alembic commands ###
