"""properties_rules nassau year

Revision ID: 9948f951613a
Revises: 4a4a7f8d3f86
Create Date: 2020-03-05 20:22:57.045684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9948f951613a'
down_revision = '4a4a7f8d3f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    update properties_rules set year = 2019 where county = 'nassau'
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###
