"""add city to property, property_original tables

Revision ID: 995f215d8c57
Revises: 58e795c2f7e4
Create Date: 2020-05-29 00:19:22.982981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995f215d8c57'
down_revision = '58e795c2f7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('city', sa.String(), nullable=True))
    op.add_column('property_original', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'city')
    op.drop_column('property', 'city')
    # ### end Alembic commands ###
