"""add payment_link to application

Revision ID: 995f30f6f0ed
Revises: 42d269e23d8f
Create Date: 2020-07-31 23:26:46.856001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995f30f6f0ed'
down_revision = '42d269e23d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('payment_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'payment_link')
    # ### end Alembic commands ###
