"""drop user_id foreign key constraint from case_note table

Revision ID: 9b98b26fcd85
Revises: be8260a7b4e3
Create Date: 2020-05-03 13:47:45.130869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b98b26fcd85'
down_revision = 'be8260a7b4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseNote_users_id', 'case_note', type_='foreignkey')
    op.drop_column('case_note', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_CaseNote_users_id', 'case_note', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
