"""add case_signature table

Revision ID: 9cfbbc9c2e09
Revises: 7e19a120201c
Create Date: 2020-05-11 14:04:39.269023

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9cfbbc9c2e09'
down_revision = '7e19a120201c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_signature',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('application_id', sa.Integer(), nullable=True),
                    sa.Column('file_name', sa.String(), nullable=True),
                    sa.Column('base64_encoded', sa.LargeBinary(), nullable=True),
                    sa.ForeignKeyConstraint(['application_id'], ['case_application.id'],
                                            name='fk_CaseSignature_case_application_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_signature')
    # ### end Alembic commands ###
