"""add updated system note type

Revision ID: 9da883abb410
Revises: 992d8cd2a3f6
Create Date: 2020-07-24 14:38:09.776144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da883abb410'
down_revision = '992d8cd2a3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (7, 'System', 'updated')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id = 7;
        '''
    )
    # ### end Alembic commands ###
