"""data_composite String to ARRAY in property table

Revision ID: 9dcbdf8ab2e2
Revises: 68047a88e734
Create Date: 2020-01-16 04:13:54.649104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dcbdf8ab2e2'
down_revision = '68047a88e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('''
    alter table property alter data_composite type integer[] using data_composite::integer[];
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'data_composite',
                    existing_type=sa.ARRAY(sa.Integer()),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
