"""remove email_bad, email_confirm_token from application, client

Revision ID: a0157d1640be
Revises: f32b3c336663
Create Date: 2020-07-27 00:41:37.663075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0157d1640be'
down_revision = 'f32b3c336663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'email_confirm_token')
    op.drop_column('case_application', 'email_confirmed_at')
    op.drop_column('case_application', 'email')
    op.drop_constraint('uc_case_client_email', 'case_client', type_='unique')
    op.drop_column('case_client', 'email_alerts')
    op.drop_column('case_client', 'email')
    op.drop_column('case_client', 'email_bad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('email_bad', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('email_alerts', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uc_case_client_email', 'case_client', ['email'])
    op.add_column('case_application', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('email_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('email_confirm_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
