"""helper obsolescence table

Revision ID: a1b992184ee7
Revises: 75114a12df00
Create Date: 2020-05-12 20:45:08.538149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b992184ee7'
down_revision = '75114a12df00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    -- auto-generated definition
CREATE TABLE obsolescence
(
    id          serial NOT NULL
        CONSTRAINT obsolescence_pk
            PRIMARY KEY,
    property_id integer,
    geom        geometry
);
Alter table obsolescence set schema helper;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    drop table helper.obsolescence''')
    # ### end Alembic commands ###
