"""fix other adjustment migration

Revision ID: a1bebecbea53
Revises: 5b2263dfbc6f
Create Date: 2020-10-02 19:47:22.675537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bebecbea53'
down_revision = '5b2263dfbc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('property_original', sa.Column('other_adjustment', sa.Integer(), nullable=True))
    op.add_column('property_original', sa.Column('other_adjustment_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'other_adjustment_description')
    op.drop_column('property_original', 'other_adjustment')
    # ### end Alembic commands ###
