"""empty message

Revision ID: a3235a3643da
Revises: 63f7bcd937cb
Create Date: 2019-12-15 14:44:01.130389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3235a3643da'
down_revision = '63f7bcd937cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
