"""renaming Multiple TX files

Revision ID: a418ffbe5937
Revises: b9f26a7914e4
Create Date: 2020-03-18 02:13:05.532123

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a418ffbe5937'
down_revision = 'b9f26a7914e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE assessment_dates
    SET assessment_file = 'TX451TWN5RS18400.TXT, TX451TWN1RS6400.TXT, TX451TWN1RS18400.TXT, TX451TWN1RS5400.TXT, TX451TWN2RS5400.TXT, TX451TWN2RS6400.TXT, TX451TWN2RS18400.TXT, TX451TWN3RS5400.TXT, TX451TWN3RS6400.TXT, TX451TWN3RS18400.TXT, TX451TWN3RS18405.TXT, TX451TWN4RS5400.TXT, TX451TWN4RS6400.TXT, TX451TWN4RS18400.TXT, TX451TWN5RS5400.TXT'
    WHERE assessment_file = 'Multiple TX* files';
''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    
    UPDATE assessment_dates
    SET assessment_file = 'Multiple TX* files'
    WHERE county = 'nassau';
    ''')
    # ### end Alembic commands ###
