"""create case_assessment_state table

Revision ID: a442439262dd
Revises: c0a55b2419dd
Create Date: 2020-04-21 17:16:50.247655

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a442439262dd'
down_revision = 'c0a55b2419dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_assessment_state',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_assessment', sa.Column('assessment_state_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseAssessment_case_assessment_state_id', 'case_assessment', 'case_assessment_state',
                          ['assessment_state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseAssessment_case_assessment_state_id', 'case_assessment', type_='foreignkey')
    op.drop_column('case_assessment', 'assessment_state_id')
    op.drop_table('case_assessment_state')
    # ### end Alembic commands ###
