"""amount default 15 to billing

Revision ID: a584e7448698
Revises: b82c1fae24ec
Create Date: 2020-07-24 23:14:37.244069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a584e7448698'
down_revision = 'b82c1fae24ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE case_billing
        ADD amount DECIMAL(10, 2) DEFAULT 15.00;
        '''
    )
    # op.add_column('case_billing', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('case_billing', 'settled_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_billing', sa.Column('settled_amount', postgresql.DOUBLE_PRECISION(precision=53),
                                            autoincrement=False, nullable=True))
    op.drop_column('case_billing', 'amount')
    # ### end Alembic commands ###
