"""adding pool to suffolk properties rules

Revision ID: a6c02d1ca3ad
Revises: f0cba73cb28f
Create Date: 2020-05-26 18:07:19.615367

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a6c02d1ca3ad'
down_revision = 'f0cba73cb28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE properties_rules
    SET adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,GARAGE,BASEMENT,FIREPLACE, POOL}'
    WHERE county = 'suffolk'
    
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
