"""added unique constraints in time_adjustment table

Revision ID: a75389fe24b1
Revises: dd59959fdc6c
Create Date: 2020-02-07 19:03:23.535893

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a75389fe24b1'
down_revision = 'dd59959fdc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_county_year_month', 'time_adjustments', ['county', 'year', 'month'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_county_year_month', 'time_adjustments', type_='unique')
    # ### end Alembic commands ###
