"""new suffolk inventory rules

Revision ID: aa6efb26cc7b
Revises: aca82cfa04ce
Create Date: 2020-05-21 02:38:26.936135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa6efb26cc7b'
down_revision = 'aca82cfa04ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
DELETE
FROM inventory_rules
WHERE parent_id = 39;

alter table inventory_rules alter column lot_sqft type double precision using lot_sqft::double precision;


INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 0, 100000, 5000, 2500, 15, 0.5, 2500, '{0,0,0,2500,5000,0,0,1250}', 10000, 0, NULL, '{}', '{}',
        '{}', '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 100001, 200000, 5000, 2500, 20, 1, 2500, '{0,0,0,2500,5000,0,0,1250}', 10000, 0, NULL, '{}', '{}',
        '{}', '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 200001, 300000, 5000, 2500, 25, 1, 2500, '{0,0,0,2500,5000,0,0,1250}', 10000, 0, NULL, '{}', '{}',
        '{}', '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 300001, 400000, 7000, 3500, 35, 1.5, 5000, '{0,0,0,3570,7500,0,0,1785}', 10000, 0, NULL, '{}',
        '{}', '{}',
        '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 400001, 550000, 8000, 4000, 40, 2, 5000, '{0,0,0,3570,7500,0,0,1785}', 10000, 0, NULL, '{}', '{}',
        '{}', '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 550001, 749000, 8000, 4000, 45, 2, 5000, '{0,0,0,3570,7500,0,0,1785}', 15000, 0, NULL, '{}', '{}',
        '{}', '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 749001, 899000, 10000, 5000, 50, 2.5, 8000, '{0,0,0,5000,10000,0,0,2500}', 15000, 0, NULL, '{}',
        '{}', '{}',
        '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 899001, 1000000, 10000, 5000, 50, 2.5, 8000, '{0,0,0,5000,10000,0,0,2500}', 15000, 0, NULL, '{}',
        '{}', '{}',
        '{}');
INSERT INTO public.inventory_rules (id, parent_id, price_start, price_end, full_bath, half_bath, gla_sqft, lot_sqft,
                                    garage, basement_prices, pool, fireplace, bedrooms, heat_type_prices,
                                    patio_type_prices, paving_type_prices, porch_type_prices)
VALUES (DEFAULT, 39, 1000001, 100000000, 10000, 5000, 50, 2.5, 8000, '{0,0,0,5000,10000,0,0,2500}', 20000, 0, NULL,
        '{}', '{}',
        '{}', '{}');
    
    
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
