"""drop data_mappers table

Revision ID: ac5233b23f56
Revises: 97e59e58b414
Create Date: 2020-10-21 16:37:52.736207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac5233b23f56'
down_revision = '97e59e58b414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_mappers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_mappers',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='data_mappers_pkey'),
                    sa.UniqueConstraint('name', name='uq_data_mappers_name')
                    )
    # ### end Alembic commands ###
