"""fix case property status_id

Revision ID: ad12470578db
Revises: f7e1631559f4
Create Date: 2020-07-27 16:29:57.734919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad12470578db'
down_revision = 'f7e1631559f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_property
        SET status_id = 1
        WHERE status_id is null;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
