"""capitalize Nassau  address, address_line_1, address_line_2 in property table

Revision ID: ad2ea1921ab8
Revises: 84f1fa884331
Create Date: 2020-08-16 16:02:16.512843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2ea1921ab8'
down_revision = '84f1fa884331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute(
    #     '''
    #         -- capitalize Nassau 'address', 'address_line_1', 'address_line_2'
    #         update property set
    #                             address = initcap(address),
    #                             address_line_1 = initcap(address_line_1),
    #                             address_line_2 = initcap(address_line_2),
    #                             city = initcap(city)
    #         where county = 'nassau';
    #
    #         -- make uppercase stop words in 'address' attribute
    #         DO
    #         $do$
    #         DECLARE
    #            stop_word varchar[] := '{NY}';
    #         BEGIN
    #            FOR i IN array_lower(stop_word, 1) .. array_upper(stop_word, 1)
    #            LOOP
    #               update property
    #               set address = replace(initcap(address), initcap(' '||stop_word[i]||' '), ' '||stop_word[i]||' ')
    #               WHERE upper(address) ilike '% '||stop_word[i]||' %'
    #               AND county = 'nassau';
    #            END LOOP;
    #         END
    #         $do$;
    #
    #         -- make uppercase stop words in 'address_line_1' attribute
    #         DO
    #         $do$
    #         DECLARE
    #            stop_word varchar[] := '{NY}';
    #         BEGIN
    #            FOR i IN array_lower(stop_word, 1) .. array_upper(stop_word, 1)
    #            LOOP
    #               update property
    #               set address_line_1 = replace(initcap(address_line_1), initcap(' '||stop_word[i]||' '), ' '||stop_word[i]||' ')
    #               WHERE upper(address_line_1) ilike '% '||stop_word[i]||' %'
    #               AND county = 'nassau';
    #            END LOOP;
    #         END
    #         $do$;
    #
    #         -- make uppercase stop words in 'address_line_1' attribute
    #         DO
    #         $do$
    #         DECLARE
    #            stop_word varchar[] := '{NY}';
    #         BEGIN
    #            FOR i IN array_lower(stop_word, 1) .. array_upper(stop_word, 1)
    #            LOOP
    #               update property
    #               set address_line_2 = replace(initcap(address_line_2), initcap(' '||stop_word[i]||' '), ' '||stop_word[i]||' ')
    #               WHERE upper(address_line_2) ilike '% '||stop_word[i]||' %'
    #               AND county = 'nassau';
    #            END LOOP;
    #         END
    #         $do$;
    #
    #     '''
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
