"""remove take_over_year, take_over_client_id from case_application table

Revision ID: ad37dc58c9d2
Revises: 9eeeb55c141c
Create Date: 2020-06-25 15:52:58.442152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad37dc58c9d2'
down_revision = '9eeeb55c141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'takeover_year')
    op.drop_column('case_application', 'takeover_client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('takeover_client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('case_application', sa.Column('takeover_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
