"""not nullable dates in assessment_dates table

Revision ID: ad87e3e01fed
Revises: 49a671fce3ce
Create Date: 2020-03-09 17:29:12.434014

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ad87e3e01fed'
down_revision = '49a671fce3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_dates', 'tax_year', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('assessment_dates', 'valuation_date', existing_type=sa.DATE(), nullable=False)
    op.alter_column('assessment_dates', 'assessment_file', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_dates', 'valuation_date', existing_type=sa.DATE(), nullable=True)
    op.alter_column('assessment_dates', 'assessment_file', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('assessment_dates', 'tax_year', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
