"""assessment foreign key names fix

Revision ID: ae132df4e00c
Revises: 18c82008ef6e
Create Date: 2020-05-02 01:34:10.254172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae132df4e00c'
down_revision = '18c82008ef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_assessment_dates_fkey', 'assessment', type_='foreignkey')
    op.drop_constraint('assessment_property_id_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key(
        'assessment_assessment_dates_fkey', 'assessment', 'assessment_dates', ['assessment_id'], ['id']
    )
    op.create_foreign_key('assessment_property_id_fkey', 'assessment', 'property', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assessment_property_id_fkey', 'assessment', type_='foreignkey')
    op.drop_constraint('assessment_assessment_dates_fkey', 'assessment', type_='foreignkey')
    op.create_foreign_key('assessment_property_id_fkey', 'assessment', 'property', ['property_id'], ['id'],
                          onupdate='CASCADE', ondelete='CASCADE'
                          )
    op.create_foreign_key('assessment_assessment_dates_fkey', 'assessment', 'assessment_dates',
                          ['assessment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE'
                          )
    # ### end Alembic commands ###
