"""empty message

Revision ID: af6db81e96dc
Revises: 71d6f16641e2
Create Date: 2020-01-27 12:33:24.147954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6db81e96dc'
down_revision = '71d6f16641e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratios_settings_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=17, scale=7), nullable=True),
    sa.ForeignKeyConstraint(['ratios_settings_id'], ['settings_ratios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_settings_ratios_year', table_name='settings_ratios')
    op.drop_column('settings_ratios', 'value')
    op.drop_column('settings_ratios', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings_ratios', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('settings_ratios', sa.Column('value', sa.NUMERIC(precision=17, scale=7), autoincrement=False, nullable=True))
    op.create_index('ix_settings_ratios_year', 'settings_ratios', ['year'], unique=False)
    op.drop_table('ratios')
    # ### end Alembic commands ###
