"""insert case-management initial data types

Revision ID: b1b0be510fef
Revises: ce334f128e16
Create Date: 2020-05-13 03:33:34.921074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b0be510fef'
down_revision = 'ce334f128e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
            DELETE FROM case_client_tag CASCADE;
            DELETE FROM case_client CASCADE;
            DELETE FROM case_application_source CASCADE;
            DELETE FROM case_company_serving CASCADE;
            DELETE FROM case_client_type CASCADE;
            DELETE FROM case_owner_type CASCADE;
            DELETE FROM case_assessment_state CASCADE;
            DELETE FROM case_note_type CASCADE;
            DELETE FROM case_note_type CASCADE;
            DELETE FROM case_marketing_code CASCADE;
        '''
    )

    op.execute(
        '''       
        INSERT INTO case_application_source (id, type) VALUES (1, 'physical');
        INSERT INTO case_application_source (id, type) VALUES (2, 'online');
        
        INSERT INTO case_company_serving (id, company_name) VALUES (1, 'ptrc');
        INSERT INTO case_company_serving (id, company_name) VALUES (2, 'redux');
        
        INSERT INTO case_client_type (id, type) VALUES (1, 'current');
        INSERT INTO case_client_type (id, type) VALUES (2, 'prospect');
        
        INSERT INTO case_owner_type (id, type, description) VALUES (1, 'new_home_owner', 'New Home Owner');
        INSERT INTO case_owner_type (id, type, description) VALUES (2, 'standard', 'Standard');

        INSERT INTO case_assessment_state (id, name) VALUES (1, 'New');
        INSERT INTO case_assessment_state (id, name) VALUES (2, 'Paused');
        INSERT INTO case_assessment_state (id, name) VALUES (3, 'In Process');
        INSERT INTO case_assessment_state (id, name) VALUES (4, 'Finished');
        
        INSERT INTO case_marketing_code (id, code) VALUES (1, 'None');
        INSERT INTO case_marketing_code (id, code) VALUES (2, 'Web');
        INSERT INTO case_marketing_code (id, code) VALUES (3, '123456');
        
        INSERT INTO case_note_type (id, type) VALUES (1, 'System');
        INSERT INTO case_note_type (id, type) VALUES (2, 'Manual');               
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_application_source WHERE id in (1, 2);
        DELETE FROM case_client_type WHERE id in (1, 2);
        DELETE FROM case_owner_type WHERE id in (1, 2);
        DELETE FROM case_assessment_state WHERE id in (1, 2, 3, 4);
        DELETE FROM case_marketing_code WHERE id in (1, 2, 3);
        DELETE FROM case_note_type WHERE id in (1, 2);
        '''
    )
    # ### end Alembic commands ###
