"""add is_residential to property

Revision ID: b26eca0e588b
Revises: 3b594f0cc707
Create Date: 2020-07-15 08:46:51.956123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26eca0e588b'
down_revision = '3b594f0cc707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('property', sa.Column('is_residential', sa.Boolean(), nullable=True))
    # op.execute(
    #     '''
    #     CREATE INDEX ix_Property_is_residential ON property USING btree(is_residential);
    #     '''
    # )
    # op.add_column('property_original', sa.Column('is_residential', sa.Boolean(), nullable=True))
    # op.execute(
    #     '''
    #     CREATE INDEX ix_PropertyOriginal_is_residential ON property USING btree(is_residential);
    #     '''
    # )

    # TODO: update the server but skip this migration as the column and index are already present on the server database
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_PropertyOriginal_is_residential', table_name='property_original')
    # op.drop_column('property_original', 'is_residential')
    # op.drop_index('ix_Property_is_residential', table_name='property')
    # op.drop_column('property', 'is_residential')
    pass
    # ### end Alembic commands ###
