"""remove extension

Revision ID: b361251d5293
Revises: 32705a1b512b
Create Date: 2020-09-23 14:28:51.660953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b361251d5293'
down_revision = '32705a1b512b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'extension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
