"""added owner to property table

Revision ID: b3a52dc9fec3
Revises: a76a03e7d8ae
Create Date: 2020-01-03 16:49:56.635575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a52dc9fec3'
down_revision = 'a76a03e7d8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('owner_first_name', sa.String(), nullable=True))
    op.add_column('property', sa.Column('owner_last_name', sa.String(), nullable=True))
    op.add_column('property', sa.Column('owner_legal_address', sa.String(), nullable=True))
    op.add_column('property', sa.Column('owner_street_address', sa.String(), nullable=True))
    op.add_column('property', sa.Column('second_owner_first_name', sa.String(), nullable=True))
    op.add_column('property', sa.Column('second_owner_last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'second_owner_last_name')
    op.drop_column('property', 'second_owner_first_name')
    op.drop_column('property', 'owner_street_address')
    op.drop_column('property', 'owner_legal_address')
    op.drop_column('property', 'owner_last_name')
    op.drop_column('property', 'owner_first_name')
    # ### end Alembic commands ###
