"""adjusting property indexes

Revision ID: b45def53e17d
Revises: 018e96ab4dee
Create Date: 2020-04-01 17:59:44.280330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45def53e17d'
down_revision = '018e96ab4dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    drop index ix_property_combined;

    CREATE INDEX ix_property_combined
        ON property (county, latitude, longitude, gla_sqft, lot_size);
    
    CREATE INDEX property_another_combined_index
        ON property (county, school_district, property_class, town, street, property_style);
    
    ''')
    # ### end Alembic commands ###


def downgrade():
    pass
