"""unique constraint in settings_global table

Revision ID: b5374e6568a1
Revises: ec95a2bcd0b9
Create Date: 2020-03-16 13:35:18.690774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5374e6568a1'
down_revision = 'ec95a2bcd0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_county', 'settings_global', ['county'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_county', 'settings_global', type_='unique')
    # ### end Alembic commands ###
