"""add address application review page fields

Revision ID: b6d66bb15939
Revises: f92b6df05f46
Create Date: 2020-05-18 20:45:58.832526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d66bb15939'
down_revision = 'f92b6df05f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('address_zip', sa.Integer(), nullable=True))
    op.drop_column('case_application', 'property_address')
    op.add_column('case_client', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('address_zip', sa.Integer(), nullable=True))
    op.drop_column('case_client', 'property_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('property_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'address_zip')
    op.drop_column('case_client', 'address_state')
    op.drop_column('case_client', 'address_line2')
    op.drop_column('case_client', 'address_line1')
    op.drop_column('case_client', 'address_city')
    op.add_column('case_application', sa.Column('property_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'address_zip')
    op.drop_column('case_application', 'address_state')
    op.drop_column('case_application', 'address_line2')
    op.drop_column('case_application', 'address_line1')
    op.drop_column('case_application', 'address_city')
    # ### end Alembic commands ###
