"""remove duplicated contract agreement

Revision ID: b72714d11a43
Revises: 6761e2541db3
Create Date: 2020-09-10 02:07:39.271615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72714d11a43'
down_revision = '6761e2541db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        delete from case_note
        where sender_id in
            (
                select sender_id from (
                                  select sender_id, count(sender_id) as count
                                  from case_note
                                  where sender = 1
                                    and text = 'Contract Agreement Attachment was sent'
                                  group by sender_id
                              ) as tmp
                where tmp.count> 1
                )
        and text='Contract Agreement Attachment was sent'
        and created_by_id is null; -- remove duplicated manually created by cli command
        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
