"""add tax_year to case_property table

Revision ID: b744f42ee7dc
Revises: 97ae31e87c56
Create Date: 2020-05-28 21:40:43.585274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b744f42ee7dc'
down_revision = '97ae31e87c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property', sa.Column('tax_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_property', 'tax_year')
    # ### end Alembic commands ###
