"""billing to application

Revision ID: b82c1fae24ec
Revises: fc38be0342e2
Create Date: 2020-07-24 23:00:37.408060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82c1fae24ec'
down_revision = 'fc38be0342e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('billing_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_Application_billing_id', 'case_application', 'case_billing', ['billing_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('fk_case_client_billing_id', 'case_client', type_='foreignkey')
    op.create_foreign_key('fk_Client_billing_id', 'case_client', 'case_billing', ['billing_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Client_billing_id', 'case_client', type_='foreignkey')
    op.create_foreign_key('fk_case_client_billing_id', 'case_client', 'case_billing', ['billing_id'], ['id'])
    op.drop_constraint('fk_Application_billing_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'billing_id')
    # ### end Alembic commands ###
