"""lat lon index

Revision ID: b8a0dbdc12a8
Revises: 95d99876e0f4
Create Date: 2020-06-04 07:14:33.978873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a0dbdc12a8'
down_revision = '95d99876e0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_property_is_condo'), 'property', ['is_condo'], unique=False)
    op.create_index(op.f('ix_property_latitude'), 'property', ['latitude'], unique=False)
    op.create_index(op.f('ix_property_longitude'), 'property', ['longitude'], unique=False)
    op.create_index(op.f('ix_property_original_is_condo'), 'property_original', ['is_condo'], unique=False)
    op.create_index(op.f('ix_property_original_latitude'), 'property_original', ['latitude'], unique=False)
    op.create_index(op.f('ix_property_original_longitude'), 'property_original', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_original_longitude'), table_name='property_original')
    op.drop_index(op.f('ix_property_original_latitude'), table_name='property_original')
    op.drop_index(op.f('ix_property_original_is_condo'), table_name='property_original')
    op.drop_index(op.f('ix_property_longitude'), table_name='property')
    op.drop_index(op.f('ix_property_latitude'), table_name='property')
    op.drop_index(op.f('ix_property_is_condo'), table_name='property')
    # ### end Alembic commands ###
