"""property town codes, assessment swiss_code

Revision ID: b929b5796e8f
Revises: 8e403c82a243
Create Date: 2019-12-19 21:24:35.621208

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from app.database.models.assessment import NASSAU_SWISS_CODES
from app.database.models.property import TOWNS

revision = 'b929b5796e8f'
down_revision = '8e403c82a243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment',
                  sa.Column('swiss_code', sqlalchemy_utils.types.choice.ChoiceType(NASSAU_SWISS_CODES), nullable=True))
    op.alter_column('property', 'town',
                    existing_type=sa.VARCHAR(),
                    type_=sqlalchemy_utils.types.choice.ChoiceType(
                        TOWNS),
                    existing_nullable=False)
    op.create_index(op.f('ix_property_county'), 'property', ['county'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_county'), table_name='property')
    op.alter_column('property',
                    'town',
                    existing_type=sqlalchemy_utils.types.choice.ChoiceType(TOWNS),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.drop_column('assessment', 'swiss_code')
    # ### end Alembic commands ###
