"""add miamidade tent 2020 in assessment_date

Revision ID: b9b8fef46c3a
Revises: 05c1b09266ab
Create Date: 2020-07-10 13:04:55.264437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b8fef46c3a'
down_revision = '05c1b09266ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO assessment_dates (id, county, assessment_type, tax_year, valuation_date, assessment_name)
        VALUES (10, 'miamidade', 2, 2020, '2020-02-01', 'Tentative 20');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM assessment_dates
        WHERE id=10;
        '''
    )
    # ### end Alembic commands ###
