"""properties rules town all to town null

Revision ID: b9f26a7914e4
Revises: bd3c7a9d2909
Create Date: 2020-03-17 19:53:00.585618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f26a7914e4'
down_revision = 'bd3c7a9d2909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE properties_rules
    SET town=NULL
    WHERE town = 'All'
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
