"""add viewer ability to add notes

Revision ID: ba6fdbdab4ec
Revises: 9733d894586d
Create Date: 2020-08-09 23:48:42.428539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6fdbdab4ec'
down_revision = '9733d894586d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add ability to edit (add notes)
    op.execute(
        '''
        UPDATE role SET permissions = 11 WHERE id=5;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE role SET permissions = 9 WHERE id=5;
        '''
    )
    # ### end Alembic commands ###
