"""update report_file foreign key

Revision ID: bb23e5116a9d
Revises: b361251d5293
Create Date: 2020-09-23 17:49:57.534931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb23e5116a9d'
down_revision = 'b361251d5293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
