"""rename CaseApplicationType to CaseOwneryType

Revision ID: bdbccbf8b69b
Revises: 75114a12df00
Create Date: 2020-05-13 02:42:00.398987

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bdbccbf8b69b'
down_revision = '75114a12df00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_owner_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('owner_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_CaseApplication_case_application_type_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_CaseApplication_case_owner_type_id', 'case_application', 'case_owner_type',
                          ['owner_type_id'], ['id'])
    op.drop_column('case_application', 'application_type_id')
    op.drop_table('case_application_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_type',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='case_application_type_pkey')
                    )

    op.add_column('case_application',
                  sa.Column('application_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_CaseApplication_case_owner_type_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_CaseApplication_case_application_type_id', 'case_application', 'case_application_type',
                          ['application_type_id'], ['id'])
    op.drop_column('case_application', 'owner_type_id')
    op.drop_table('case_owner_type')
    # ### end Alembic commands ###
