"""add case_property_status table

Revision ID: c00c97b1104a
Revises: 536a612e381b
Create Date: 2020-07-07 11:12:40.601450

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c00c97b1104a'
down_revision = '536a612e381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_property_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_property', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_case_property_status_id', 'case_property', 'case_property_status', ['status_id'], ['id'])

    op.execute(
        '''
        INSERT INTO case_property_status (id, name) VALUES (1, 'Application Approved');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_property_status_id', 'case_property', type_='foreignkey')
    op.drop_column('case_property', 'status_id')
    op.drop_table('case_property_status')
    # ### end Alembic commands ###
