"""migrate village data from assessment to property table

Revision ID: c04c65aaecb2
Revises: 29869e9e74b9
Create Date: 2020-02-12 19:01:56.056822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = 'c04c65aaecb2'
down_revision = '29869e9e74b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    op.add_column('property', sa.Column('village', sa.String(), nullable=True))

    op.execute(
            '''
                UPDATE property
                SET village = assessment.village_1
                FROM assessment
                WHERE assessment.property_id = property.id and assessment.village_1 is not null 
            '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'village')
    # ### end Alembic commands ###
