"""add email_alerts, sms_alerts flags to case_client table

Revision ID: c0a55b2419dd
Revises: 4e26a53e9a94
Create Date: 2020-04-21 02:21:08.360075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a55b2419dd'
down_revision = '4e26a53e9a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('email_alerts', sa.Boolean(), nullable=True))
    op.add_column('case_client', sa.Column('sms_alerts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'sms_alerts')
    op.drop_column('case_client', 'email_alerts')
    # ### end Alembic commands ###
