"""property table geo index

Revision ID: c498e5b02364
Revises: fe0b2e7ed476
Create Date: 2020-05-11 20:15:18.680189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c498e5b02364'
down_revision = 'fe0b2e7ed476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_property_geo'), 'property', ['geo'], unique=False)
    op.create_index(op.f('ix_property_original_geo'), 'property_original', ['geo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_original_geo'), table_name='property_original')
    op.drop_index(op.f('ix_property_geo'), table_name='property')
    # ### end Alembic commands ###
