"""rename note_type to type

Revision ID: c49b1442e5e3
Revises: c76998581e4b
Create Date: 2020-04-24 13:54:57.065823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49b1442e5e3'
down_revision = 'c76998581e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note_type', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('case_note_type', 'note_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note_type', sa.Column('note_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_note_type', 'type')
    # ### end Alembic commands ###
