"""add system note paid

Revision ID: c4acaa7ac01a
Revises: b7b37c2e5095
Create Date: 2020-07-21 08:10:53.020687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4acaa7ac01a'
down_revision = 'b7b37c2e5095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (5, 'System', 'paid')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id = 5;
        '''
    )
    # ### end Alembic commands ###
