"""null nassau garages to 1

Revision ID: c673ab29d401
Revises: b45def53e17d
Create Date: 2020-04-02 18:17:11.140967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c673ab29d401'
down_revision = 'b45def53e17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE property
    SET garages = 1
    WHERE county = 'nassau'
      AND garages IS NULL
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
