"""property gis index on property id

Revision ID: c6a634adda29
Revises: 955e26dd4d8f
Create Date: 2020-06-15 11:50:25.363856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a634adda29'
down_revision = '955e26dd4d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_property_gis_property_id'), 'property_gis', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_gis_property_id'), table_name='property_gis')
    # ### end Alembic commands ###
