"""create client_type table, update application_type

Revision ID: c76998581e4b
Revises: 24dcb22e657f
Create Date: 2020-04-24 13:47:52.089974

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c76998581e4b'
down_revision = '24dcb22e657f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_client_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application_type', sa.Column('description', sa.String(), nullable=True))
    op.add_column('case_application_type', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('case_application_type', 'application_type')
    op.add_column('case_client', sa.Column('client_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_CaseClient_case_client_type_id", 'case_client', 'case_client_type', ['client_type_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_CaseClient_case_client_type_id", 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'client_type_id')
    op.add_column('case_application_type',
                  sa.Column('application_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application_type', 'type')
    op.drop_column('case_application_type', 'description')
    op.drop_table('case_client_type')
    # ### end Alembic commands ###
