"""add payment_type to case_client table

Revision ID: c7c0b1038251
Revises: 48e0a14287a0
Create Date: 2020-05-29 20:05:43.572367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c0b1038251'
down_revision = '48e0a14287a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('payment_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_case_client_payment_type_id', 'case_client', 'case_payment_type', ['payment_type_id'],
                          ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_case_client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'payment_type_id')
    # ### end Alembic commands ###
