"""floor height to inventory rules

Revision ID: c805deb19d54
Revises: ce1e0cf256a3
Create Date: 2020-06-04 20:58:02.336654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c805deb19d54'
down_revision = 'ce1e0cf256a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rules', sa.Column('floor_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_rules', 'floor_height')
    # ### end Alembic commands ###
