"""cma task complete time stamp

Revision ID: c897d50690d1
Revises: f5cf8300ba6a
Create Date: 2020-02-13 23:33:17.681990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c897d50690d1'
down_revision = 'f5cf8300ba6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cma_task', sa.Column('task_complete_ts', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cma_task', 'task_complete_ts')
    # ### end Alembic commands ###
