"""update case-application tables content

Revision ID: c93a16e3ef08
Revises: c6e13c904f92
Create Date: 2020-05-13 14:55:54.968623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93a16e3ef08'
down_revision = 'c6e13c904f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note_type', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('case_note_type', 'type')

    op.execute('''
        UPDATE case_client_type set name = 'prospect' WHERE id=1;
        UPDATE case_client_type set name = 'current' WHERE id=2;
        
        UPDATE case_application_source set name = 'physical' WHERE id=1;
        UPDATE case_application_source set name = 'online' WHERE id=2;
        
        UPDATE case_company_serving set name = 'ptrc' WHERE id=1;
        UPDATE case_company_serving set name = 'redux' WHERE id=2;
        
        UPDATE case_marketing_code set name = 'None' WHERE id=1;
        UPDATE case_marketing_code set name = 'Web' WHERE id=2;
        UPDATE case_marketing_code set name = '123456' WHERE id=3;
            
        UPDATE case_note_type set name = 'System' WHERE id=1;
        UPDATE case_note_type set name = 'Manual' WHERE id=2;

        UPDATE case_owner_type set name = 'new_home_owner' WHERE id=1;
        UPDATE case_owner_type set name = 'standard' WHERE id=2;      
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_note_type', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_note_type', 'name')
    # ### end Alembic commands ###
