"""property_id index on property photo

Revision ID: c9d2f8cd5523
Revises: c673ab29d401
Create Date: 2020-04-04 16:39:09.714139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d2f8cd5523'
down_revision = 'c673ab29d401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    create index property_photo_property_id_index
	on property_photo (property_id);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    drop index property_photo_property_id_index;
    ''')
    # ### end Alembic commands ###
