"""empty message

Revision ID: caee292729ad
Revises: cde31029bd3c
Create Date: 2020-01-16 12:56:04.764320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee292729ad'
down_revision = 'cde31029bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obsolescence_rules')
    op.add_column('properties_rules', sa.Column('obsolescence_rules', sa.ARRAY(sa.Numeric(precision=6, scale=3)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'obsolescence_rules')
    op.create_table('obsolescence_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['properties_rules.id'], name='obsolescence_rules_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='obsolescence_rules_pkey')
    )
    # ### end Alembic commands ###
