"""str year to int in properties_rules table

Revision ID: cb0869951b48
Revises: 1b22dbc9f22a
Create Date: 2020-06-17 19:10:56.646736

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb0869951b48'
down_revision = '1b22dbc9f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('properties_rules', 'year',
    #                 existing_type=sa.VARCHAR(),
    #                 type_=sa.Integer(),
    #                 existing_nullable=True)

    op.execute(
        '''
        ALTER TABLE properties_rules ALTER COLUMN year TYPE integer USING (year::integer);
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties_rules', 'year',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
