"""add lot_size_sqft coeff to inventory_rules table

Revision ID: cba9e185d319
Revises: d91c5ee8509d
Create Date: 2020-09-28 22:01:00.195088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba9e185d319'
down_revision = 'd91c5ee8509d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rules', sa.Column('lot_size_sqft', sa.Float(), nullable=True))

    # set initial data as copy from lot_sqft
    op.execute(
        '''
        UPDATE inventory_rules
        SET lot_size_sqft = lot_sqft;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_rules', 'lot_size_sqft')
    # ### end Alembic commands ###
