"""high sale dates columns to property rules

Revision ID: cc230cd147b3
Revises: 14a80a230bc7
Create Date: 2020-03-31 21:50:11.660657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc230cd147b3'
down_revision = '14a80a230bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('high_sale_date_higher', sa.Date(), nullable=True))
    op.add_column('properties_rules', sa.Column('high_sale_date_lower', sa.Date(), nullable=True))
    op.execute('''
    alter table properties_rules 
    add constraint high_sale_dates check (high_sale_date_lower <= high_sale_date_higher);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    alter table properties_rules
    drop constraint high_sale_dates''')
    op.drop_column('properties_rules', 'high_sale_date_lower')
    op.drop_column('properties_rules', 'high_sale_date_higher')
    # ### end Alembic commands ###
