"""empty message

Revision ID: cc3d86859bf4
Revises: e25d87c10ca8
Create Date: 2020-01-04 16:45:51.420738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3d86859bf4'
down_revision = 'e25d87c10ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apn', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_validation')
    # ### end Alembic commands ###
