"""unique indexes to property_rules to avoid duplication of rules

Revision ID: cc7928fa6bad
Revises: dd121a31c290
Create Date: 2020-04-13 15:05:14.787879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7928fa6bad'
down_revision = 'dd121a31c290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    CREATE UNIQUE INDEX properties_rules_county_town_year_index
        ON properties_rules (county, town, year);
    
    CREATE UNIQUE INDEX properties_rules_county_town_index
        ON properties_rules (county, town)
        WHERE (town IS NULL);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
