"""add signature_approve attribute to case_application table

Revision ID: cc9e53ce69dd
Revises: f9eee4f9b0e7
Create Date: 2020-06-29 23:42:25.241776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9e53ce69dd'
down_revision = 'f9eee4f9b0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('signature_approve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'signature_approve')
    # ### end Alembic commands ###
