"""add hearing_date to case_client

Revision ID: ce0664de2e2d
Revises: 953ecd8542b0
Create Date: 2020-07-23 11:26:21.633596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0664de2e2d'
down_revision = '953ecd8542b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('hearing_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_client', 'hearing_date')
    # ### end Alembic commands ###
