"""same age and same building switches to selection rules

Revision ID: ce1e0cf256a3
Revises: b8a0dbdc12a8
Create Date: 2020-06-04 20:39:31.866533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1e0cf256a3'
down_revision = 'b8a0dbdc12a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selection_rules', sa.Column('same_age', sa.Boolean(), nullable=True))
    op.add_column('selection_rules', sa.Column('same_building', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selection_rules', 'same_building')
    op.drop_column('selection_rules', 'same_age')
    # ### end Alembic commands ###
