"""change case_application constraints

Revision ID: ce334f128e16
Revises: 2dad48cb6b94
Create Date: 2020-05-13 03:28:44.967538

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ce334f128e16'
down_revision = '2dad48cb6b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'application_source_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('case_application', 'owner_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'owner_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('case_application', 'application_source_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
