"""add under_air_gla_sqft config in inventory_rules table

Revision ID: cfc152b5b081
Revises: d3c4d54f90af
Create Date: 2020-06-20 01:43:40.755097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc152b5b081'
down_revision = 'd3c4d54f90af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_rules', sa.Column('under_air_gla_sqft', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_rules', 'under_air_gla_sqft')
    # ### end Alembic commands ###
