"""remove spaces, space tabs in property address

Revision ID: d024f337e34d
Revises: 3b7b221dbd20
Create Date: 2020-02-26 23:26:29.433024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd024f337e34d'
down_revision = '3b7b221dbd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE property SET address = trim(regexp_replace(address, '\s+', ' ', 'g'));
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
