"""fix state for palmbeach, miamidade in property table

Revision ID: d05bf453fa81
Revises: fd8a3f2ff4fb
Create Date: 2020-06-29 13:40:10.663439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05bf453fa81'
down_revision = 'fd8a3f2ff4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE property
        SET state = 'FL'
        WHERE state = 'FLORIDA'
        AND county in ('palmbeach', 'miamidade')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
