"""drop old assessment ratio table

Revision ID: d254d3d367b9
Revises: d4c6bd5654eb
Create Date: 2020-03-13 18:23:37.978511

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd254d3d367b9'
down_revision = 'd4c6bd5654eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    DROP TABLE assessment_ratio;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
