"""added paving type to property table

Revision ID: d2a1977866bf
Revises: de99480a93fc
Create Date: 2020-01-21 01:13:36.182461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a1977866bf'
down_revision = 'de99480a93fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('paving_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'paving_type')
    # ### end Alembic commands ###
