"""owner property_id index

Revision ID: d34b94050460
Revises: 8c61c4f57dc4
Create Date: 2020-01-29 17:15:41.136384

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd34b94050460'
down_revision = '8c61c4f57dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_owner_property_id'), 'owner', ['property_id'], unique=False)
    op.create_index(op.f('ix_assessment_property_id'), 'assessment', ['property_id'], unique=False)
    op.create_index(op.f('ix_sale_property_id'), 'sale', ['property_id'], unique=False)
    op.execute('''
    alter table owner drop constraint owner_property_id_fkey;

    alter table owner
        add constraint owner_property_id_fkey
            foreign key (property_id) references property
                on update cascade on delete cascade ;
                
    alter table sale drop constraint sale_property_id_fkey;
    
    alter table sale
        add constraint sale_property_id_fkey
            foreign key (property_id) references property
                on update cascade on delete cascade;

    alter table assessment drop constraint assessment_property_id_fkey;
    
    alter table assessment
        add constraint assessment_property_id_fkey
            foreign key (property_id) references property
                on update cascade on delete cascade;
                
    alter table cma_result drop constraint cma_result_property_id_fkey;

    alter table cma_result
        add constraint cma_result_property_id_fkey
            foreign key (property_id) references property
                on update cascade on delete cascade;

''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_property_id'), table_name='owner')
    op.drop_index(op.f('ix_assessment_property_id'), table_name='assessment')
    op.drop_index(op.f('ix_sale_property_id'), table_name='sale')
    # ### end Alembic commands ###
