"""fix Property combined indexes creation

Revision ID: d3acb192b194
Revises: 04aaf0b4c2cf
Create Date: 2020-05-02 03:01:58.805625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3acb192b194'
down_revision = '04aaf0b4c2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('property_another_combined_index', table_name='property')
    op.create_index('property_another_combined_index', 'property_original',
                    ['county', 'school_district', 'property_class', 'town', 'street', 'property_style'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('property_another_combined_index', table_name='property_original')
    op.create_index('property_another_combined_index', 'property',
                    ['county', 'school_district', 'property_class', 'town', 'street', 'property_style'], unique=False)
    # ### end Alembic commands ###
