"""add under_air_gla_sqft to property, property_original tables

Revision ID: d3c4d54f90af
Revises: f7aa928fbac1
Create Date: 2020-06-20 01:35:27.884772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c4d54f90af'
down_revision = 'f7aa928fbac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('under_air_gla_sqft', sa.Float(), nullable=True))
    op.add_column('property_original', sa.Column('under_air_gla_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'under_air_gla_sqft')
    op.drop_column('property', 'under_air_gla_sqft')
    # ### end Alembic commands ###
