"""update signature_approved attribute name

Revision ID: d50a9f0e84e3
Revises: cc9e53ce69dd
Create Date: 2020-06-29 23:45:27.315448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50a9f0e84e3'
down_revision = 'cc9e53ce69dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('signature_approved', sa.Boolean(), nullable=True))
    op.drop_column('case_application', 'signature_approve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('signature_approve', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'signature_approved')
    # ### end Alembic commands ###
