"""add payment_type_id, payment_status_id to case_property table

Revision ID: d657e9213252
Revises: 81e394b1e8e1
Create Date: 2020-07-30 22:54:22.033195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd657e9213252'
down_revision = '81e394b1e8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property', sa.Column('payment_status_id', sa.Integer(), nullable=True))
    op.add_column('case_property', sa.Column('payment_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseProperty_payment_type_id', 'case_property', 'case_payment_type', ['payment_type_id'], ['id'])
    op.create_foreign_key('fk_CaseProperty_payment_status_id', 'case_property', 'case_payment_status',
                          ['payment_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseProperty_payment_status_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_CaseProperty_payment_type_id', 'case_property', type_='foreignkey')
    op.drop_column('case_property', 'payment_type_id')
    op.drop_column('case_property', 'payment_status_id')
    # ### end Alembic commands ###
