"""added obsolescences

Revision ID: d6caf79af7dd
Revises: bb2f442a8b8f
Create Date: 2020-01-14 22:20:00.269558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6caf79af7dd'
down_revision = 'bb2f442a8b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obsolescence_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['properties_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obsolescence_rules')
    # ### end Alembic commands ###
