"""add mailing_addres_1, mailing_address_2 to case application, client models

Revision ID: d6ef36c760dc
Revises: 1895d53b333f
Create Date: 2020-05-17 00:29:56.653535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ef36c760dc'
down_revision = '1895d53b333f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('mailing_address_1', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_address_2', sa.String(), nullable=True))
    op.drop_column('case_application', 'mailing_address')
    op.add_column('case_client', sa.Column('mailing_address_1', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_address_2', sa.String(), nullable=True))
    op.drop_column('case_client', 'mailing_address')
    op.drop_column('case_property', 'full_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_property', sa.Column('full_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('mailing_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'mailing_address_2')
    op.drop_column('case_client', 'mailing_address_1')
    op.add_column('case_application', sa.Column('mailing_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'mailing_address_2')
    op.drop_column('case_application', 'mailing_address_1')
    # ### end Alembic commands ###
