"""add subject_sales_from to properties_rules table

Revision ID: d7e14112d885
Revises: 2828086c6d4e
Create Date: 2020-03-11 12:34:01.986341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e14112d885'
down_revision = '2828086c6d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules', sa.Column('subject_sales_from', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'subject_sales_from')
    # ### end Alembic commands ###
