"""add lot_size_sqft to property

Revision ID: d91c5ee8509d
Revises: bb23e5116a9d
Create Date: 2020-09-28 19:15:26.642133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c5ee8509d'
down_revision = 'bb23e5116a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('lot_size_sqft', sa.Float(), nullable=True))
    op.add_column('property_original', sa.Column('lot_size_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'lot_size_sqft')
    op.drop_column('property', 'lot_size_sqft')
    # ### end Alembic commands ###
