"""remove applications-tags many2many association

Revision ID: da023fe42564
Revises: 23e10f64b3c6
Create Date: 2020-05-04 17:55:20.333144

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'da023fe42564'
down_revision = '23e10f64b3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_application_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_tag',
                    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['application_id'], ['case_application.id'],
                                            name='case_application_tag_application_id_fkey'),
                    sa.ForeignKeyConstraint(['tag_id'], ['case_tag.id'], name='case_application_tag_tag_id_fkey')
                    )
    # ### end Alembic commands ###
