"""add condo_view_floor to property

Revision ID: da141728b2a4
Revises: ebc3d89721c0
Create Date: 2020-12-10 15:46:03.994752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da141728b2a4'
down_revision = 'ebc3d89721c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('condo_view_floor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_original', 'condo_view_floor')
    # ### end Alembic commands ###
