"""sale price to integer

Revision ID: daad7a7ecc67
Revises: 7be0bcd33489
Create Date: 2019-12-29 23:57:33.031645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'daad7a7ecc67'
down_revision = '7be0bcd33489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'price',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'price',
                    existing_type=sa.Integer(),
                    type_=postgresql.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True)
    # ### end Alembic commands ###
