"""add authorized signer

Revision ID: dbf12d63549f
Revises: ac0b433a54a3
Create Date: 2020-08-02 11:55:55.873760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf12d63549f'
down_revision = 'ac0b433a54a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('case_application', sa.Column('authorized_signer', sa.Boolean(), nullable=True))
    op.execute(
        '''
        ALTER TABLE case_application ADD COLUMN authorized_signer BOOLEAN DEFAULT TRUE;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'authorized_signer')
    # ### end Alembic commands ###
