"""reseting primary key sequence for rule tables

Revision ID: dd121a31c290
Revises: 488174c74456
Create Date: 2020-04-13 00:25:50.759054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd121a31c290'
down_revision = '488174c74456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    SELECT setval('properties_rules_id_seq', max(id))
    FROM properties_rules;
    SELECT setval('inventory_rules_id_seq', max(id))
    FROM inventory_rules;
    SELECT setval('selection_rules_id_seq', max(id))
    FROM selection_rules;    
    ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
