"""splitting bath column

Revision ID: de4d7f6b12f7
Revises: 855fa731604f
Create Date: 2019-12-15 18:57:22.416588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de4d7f6b12f7'
down_revision = '855fa731604f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('truncate property cascade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('full_baths', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('half_baths', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('hamlet', sa.String(), nullable=True))
    op.add_column('property', sa.Column('is_condo', sa.Boolean(), nullable=True))
    op.add_column('property', sa.Column('is_listed', sa.Boolean(), nullable=True))
    op.add_column('property', sa.Column('kitchens', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('town', sa.String(), nullable=False))
    op.add_column('property', sa.Column('zip', sa.Integer(), nullable=True))
    op.drop_column('property', 'city')
    op.drop_column('property', 'baths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('truncate property cascade')
    op.add_column('property', sa.Column('baths', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('property', 'zip')
    op.drop_column('property', 'town')
    op.drop_column('property', 'kitchens')
    op.drop_column('property', 'is_listed')
    op.drop_column('property', 'is_condo')
    op.drop_column('property', 'hamlet')
    op.drop_column('property', 'half_baths')
    op.drop_column('property', 'full_baths')
    # ### end Alembic commands ###
