"""property location to integer

Revision ID: de99480a93fc
Revises: 189b883a676c
Create Date: 2020-01-19 16:39:36.640997

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'de99480a93fc'
down_revision = '189b883a676c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    update property
    set coordinate_x = latitude,
        coordinate_y = longitude,
        latitude = null,
        longitude = null
    where county='nassau' or county='suffolk'
    ''')
    op.execute('''
    update property
    set location = null
    where location = ''
    ''')
    op.execute('''alter table property alter location type integer using location::integer''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'location',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
