"""add payment type description

Revision ID: df1d969b3cca
Revises: c4acaa7ac01a
Create Date: 2020-07-21 10:55:52.568652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1d969b3cca'
down_revision = 'c4acaa7ac01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_payment_type', sa.Column('description', sa.String(), nullable=True))

    op.execute(
        '''
        UPDATE case_payment_type
        SET description='Credit Card'
        WHERE id=1;
        
        UPDATE case_payment_type
        SET description='Check'
        WHERE id=2;
        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_payment_type', 'description')
    # ### end Alembic commands ###
