"""remove payment type, payment status from case_client table

Revision ID: df29b1fb4821
Revises: 61b2c6d2978e
Create Date: 2020-07-30 23:58:55.998838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df29b1fb4821'
down_revision = '61b2c6d2978e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Client_payment_status_id', 'case_client', type_='foreignkey')
    op.drop_constraint('fk_Client_payment_type_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'payment_status_id')
    op.drop_column('case_client', 'payment_type_id')
    op.drop_constraint('fk_CaseProperty_payment_status_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_CaseProperty_payment_type_id', 'case_property', type_='foreignkey')
    op.create_foreign_key('fk_CaseProperty_payment_type_id', 'case_property', 'case_payment_type',
                          ['payment_type_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_CaseProperty_payment_status_id', 'case_property', 'case_payment_status',
                          ['payment_status_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_CaseProperty_payment_status_id', 'case_property', type_='foreignkey')
    op.drop_constraint('fk_CaseProperty_payment_type_id', 'case_property', type_='foreignkey')
    op.create_foreign_key('fk_CaseProperty_payment_type_id', 'case_property', 'case_payment_type',
                          ['payment_type_id'], ['id'])
    op.create_foreign_key('fk_CaseProperty_payment_status_id', 'case_property', 'case_payment_status',
                          ['payment_status_id'], ['id'])
    op.add_column('case_client', sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('case_client', sa.Column('payment_status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_Client_payment_type_id', 'case_client', 'case_payment_type', ['payment_type_id'],
                          ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_Client_payment_status_id', 'case_client', 'case_payment_status', ['payment_status_id'],
                          ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
