"""add suffolk assessment_date file

Revision ID: e24fa420a5d6
Revises: 6607f6fc39ca
Create Date: 2020-12-03 00:07:28.510061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e24fa420a5d6'
down_revision = '6607f6fc39ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO assessment_files (assessment_date_id, file_name) 
        VALUES (11, 'assessment.txt') 

        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM assessment_files
        WHERE assessment_date_id = 11
        AND file_name = 'assessment.txt'
        '''
    )
    # ### end Alembic commands ###
