"""owner separate table

Revision ID: e25d87c10ca8
Revises: b3a52dc9fec3
Create Date: 2020-01-03 18:45:06.307403

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e25d87c10ca8'
down_revision = 'b3a52dc9fec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('data_source', sa.String(), nullable=False),
            sa.Column('property_id', sa.Integer(), nullable=False),
            sa.Column('created_on', sa.Date(), nullable=True, default=datetime.today()),
            sa.Column('first_name', sa.String(), nullable=True),
            sa.Column('last_name', sa.String(), nullable=True),
            sa.Column('street_address', sa.String(), nullable=True),
            sa.Column('second_owner_first_name', sa.String(), nullable=True),
            sa.Column('second_owner_last_name', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.CheckConstraint(
        r"owner.data_source IN ('sale', 'assessment', 'property')")
                    )
    op.drop_column('property', 'owner_street_address')
    op.drop_column('property', 'owner_legal_address')
    op.drop_column('property', 'second_owner_first_name')
    op.drop_column('property', 'owner_last_name')
    op.drop_column('property', 'second_owner_last_name')
    op.drop_column('property', 'owner_first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('owner_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('second_owner_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('owner_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('second_owner_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('owner_legal_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('owner_street_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('owner')
    # ### end Alembic commands ###
