"""user mass cma filter

Revision ID: e38b17f86538
Revises: 325e468feb62
Create Date: 2020-02-04 01:03:44.596321

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e38b17f86538'
down_revision = '325e468feb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mass_cma_filter',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('county', sa.String(), nullable=True),
                    sa.Column('town', sa.String(), nullable=True),
                    sa.Column('village', sa.String(), nullable=True),
                    sa.Column('section', sa.String(), nullable=True),
                    sa.Column('block', sa.String(), nullable=True),
                    sa.Column('lot', sa.String(), nullable=True),
                    sa.Column('street', sa.String(), nullable=True),
                    sa.Column('number', sa.String(), nullable=True),
                    sa.Column('school_district', sa.Integer(), nullable=True),
                    sa.Column('saving_min', sa.Integer(), nullable=True),
                    sa.Column('saving_max', sa.Integer(), nullable=True),
                    sa.Column('market_value_min', sa.Integer(), nullable=True),
                    sa.Column('market_value_max', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_mass_cma_filter')
    # ### end Alembic commands ###
