"""remove region from case_application, update contactinfo mixin

Revision ID: e3a15d2a0448
Revises: 5ef8b28bc70a
Create Date: 2020-04-19 16:22:48.714815

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e3a15d2a0448'
down_revision = '5ef8b28bc70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'region',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Unicode(length=8),
                    existing_nullable=True)
    op.drop_column('case_application', 'country_code')
    op.add_column('case_client', sa.Column('region', sa.Unicode(length=8), nullable=True))
    op.drop_column('case_client', 'country_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('country_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'region')
    op.add_column('case_application',
                  sa.Column('country_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.alter_column('case_application', 'region',
                    existing_type=sa.Unicode(length=8),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
