"""create case_marketing_code table

Revision ID: e5f1d64032dd
Revises: bdbccbf8b69b
Create Date: 2020-05-13 03:12:01.833294

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e5f1d64032dd'
down_revision = 'bdbccbf8b69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_marketing_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('marketing_code_id', sa.Integer(), nullable=True))
    op.drop_constraint('case_application_company_serving_id_fkey', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_CaseApplication_case_client_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_CaseApplication_case_client_id', 'case_application', 'case_client', ['client_id'], ['id'],
                          onupdate='CASCADE')
    op.create_foreign_key('fk_CaseApplication_case_company_serving_id', 'case_application', 'case_company_serving',
                          ['company_serving_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_CaseApplication_case_marketing_code_id', 'case_application', 'case_marketing_code',
                          ['marketing_code_id'], ['id'], onupdate='CASCADE')
    op.drop_column('case_application', 'marketing_code')
    op.add_column('case_client', sa.Column('marketing_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_CaseClient_case_marketing_code_id', 'case_client', 'case_marketing_code',
                          ['marketing_code_id'], ['id'], onupdate='CASCADE')
    op.drop_column('case_client', 'marketing_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('marketing_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_CaseClient_case_marketing_code_id', 'case_client', type_='foreignkey')
    op.drop_column('case_client', 'marketing_code_id')
    op.add_column('case_application', sa.Column('marketing_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_CaseApplication_case_marketing_code_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_CaseApplication_case_company_serving_id', 'case_application', type_='foreignkey')
    op.drop_constraint('fk_CaseApplication_case_client_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_CaseApplication_case_client_id', 'case_application', 'case_client', ['client_id'], ['id'])
    op.create_foreign_key('case_application_company_serving_id_fkey', 'case_application', 'case_company_serving',
                          ['company_serving_id'], ['id'])
    op.drop_column('case_application', 'marketing_code_id')
    op.drop_table('case_marketing_code')
    # ### end Alembic commands ###
