"""Florida lot_size normalization

Revision ID: e7192d6c0b50
Revises: c32c8a05179a
Create Date: 2020-03-19 14:33:23.314477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7192d6c0b50'
down_revision = 'c32c8a05179a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE 
            property
        SET 
            lot_size = lot_size / 43560
        WHERE 
            lot_size IS NOT NULL
        AND 
            county in ('broward', 'miamidade', 'palmbeach');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE 
            property
        SET 
            lot_size = lot_size * 43560
        WHERE 
            lot_size IS NOT NULL
        AND
            county in ('broward', 'miamidade', 'palmbeach');
        '''
    )
    # ### end Alembic commands ###
