"""ruleset foreign key

Revision ID: e81863536bbc
Revises: 79beca112f4d
Create Date: 2019-12-23 18:33:40.054513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81863536bbc'
down_revision = '79beca112f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rule_set_sr_id_fkey', 'rule_set', 'selection_rule', ['selection_rule'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rule_set_sr_id_fkey', 'rule_set', type_='foreignkey')
    # ### end Alembic commands ###
