"""assessment_dates valuation date

Revision ID: e9329960b2b9
Revises: 2e373f6ab57d
Create Date: 2020-03-11 18:09:57.641938

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e9329960b2b9'
down_revision = '2e373f6ab57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    UPDATE assessment_dates
    SET valuation_date = valuation_date + INTERVAL '2 year'
    WHERE id = 2;
    UPDATE assessment_dates
    SET valuation_date = valuation_date - INTERVAL '1 year'
    WHERE id != 2;
    UPDATE assessment_dates
    SET valuation_date = valuation_date + INTERVAL '1 year'
    WHERE id IN (2, 3, 4, 5);
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
