"""add mailing state to owner table

Revision ID: e95899f379d2
Revises: 3d44a5c90b17
Create Date: 2020-06-02 15:23:37.783117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95899f379d2'
down_revision = '3d44a5c90b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('owner', sa.Column('owner_state', sa.String(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('owner', 'owner_state')
    pass
    # ### end Alembic commands ###
