"""insert payment type data, udpate application source data

Revision ID: e9ea6f0fedbf
Revises: 7b9d011ce507
Create Date: 2020-05-19 00:18:36.277304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ea6f0fedbf'
down_revision = '7b9d011ce507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_payment_type (id, name) VALUES (1, 'card');
        INSERT INTO case_payment_type (id, name) VALUES (2, 'check');
        
        UPDATE case_application_source SET name = 'digital' WHERE id = 2;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application_source SET name = 'online' WHERE id = 2;
        '''
    )
    op.execute(
        '''
        DELETE FROM case_payment_type;
        '''
    )

    # ### end Alembic commands ###
