"""change condo_view_location to string type

Revision ID: eaf47f32f00b
Revises: 6b91875883c9
Create Date: 2020-07-11 15:50:23.369659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaf47f32f00b'
down_revision = '6b91875883c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'condo_view_location',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('property_original', 'condo_view_location',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_original', 'condo_view_location',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('property', 'condo_view_location',
                    existing_type=sa.String(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
