"""add settings_global table

Revision ID: ec95a2bcd0b9
Revises: 36f2c22998fd
Create Date: 2020-03-16 11:18:26.196900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = 'ec95a2bcd0b9'
down_revision = '36f2c22998fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_global',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('county', sa.String(), nullable=True),
                    sa.Column('settings', JSONB(), nullable=False, server_default='{}'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_global')
    # ### end Alembic commands ###
