"""token to email_token in applicaiton table

Revision ID: ed6b57ef0882
Revises: 8b5bc36b6a9f
Create Date: 2020-07-22 17:15:57.837591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6b57ef0882'
down_revision = '8b5bc36b6a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('email_confirm_token', sa.String(), nullable=True))
    op.drop_column('case_application', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'email_confirm_token')
    # ### end Alembic commands ###
