"""remove property_id from workup

Revision ID: edbe5b24c0ea
Revises: 4b8c941d6481
Create Date: 2020-10-15 23:59:36.185750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edbe5b24c0ea'
down_revision = '4b8c941d6481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_single_sma_workups_property_id', 'single_sma_workups', type_='foreignkey')
    op.drop_column('single_sma_workups', 'property_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_sma_workups', sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_single_sma_workups_property_id', 'single_sma_workups', 'property', ['property_id'], ['id'])
    # ### end Alembic commands ###
