"""fix county values to lowercase in properties_rules table

Revision ID: efe3848e93a7
Revises: 1bfcc0c484b3
Create Date: 2020-02-19 20:19:12.491430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe3848e93a7'
down_revision = '1bfcc0c484b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='nassau' where county='Nassau';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='suffolk' where county='Suffolk';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='broward' where county='Broward';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='palmbeach' where county='Palmbeach';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='miamidade' where county='Miamidade';        
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='Nassau' where county='nassau';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='Suffolk' where county='suffolk';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='Broward' where county='broward';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='Palmbeach' where county='palmbeach';        
        '''
    )
    op.execute(
        '''
        UPDATE properties_rules 
        SET county='Miamidade' where county='miamidade';        
        '''
    )
    # ### end Alembic commands ###
