"""road obsolescence rules to properties rules table

Revision ID: f21bfea23982
Revises: ac017659756d
Create Date: 2020-07-08 03:38:19.127795

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f21bfea23982'
down_revision = 'ac017659756d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_rules',
                  sa.Column('road_obsolescence_rules', sa.ARRAY(sa.Numeric(precision=6, scale=3)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_rules', 'road_obsolescence_rules')
    # ### end Alembic commands ###
