"""update OBSOLESCENCE to LOCATION in properties_rules table

Revision ID: f2b69d97e41e
Revises: d4c6bd5654eb
Create Date: 2020-03-13 19:50:16.425839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b69d97e41e'
down_revision = 'd254d3d367b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update properties_rules
        set adjustments_all = '{GLA,LOT,FULL_BATH,HALF_BATH,GARAGE,BASEMENT,TIME,LOCATION}'
        where county = 'nassau' and town = 'All';
        '''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
