"""email_address unique

Revision ID: f32b3c336663
Revises: 749eb4cdc93e
Create Date: 2020-07-25 23:29:19.664138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32b3c336663'
down_revision = '749eb4cdc93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_case_email_email_address', 'case_email', ['email_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_case_email_email_address', 'case_email', type_='unique')
    # ### end Alembic commands ###
