"""total column to cma_task

Revision ID: f5cf8300ba6a
Revises: c04c65aaecb2
Create Date: 2020-02-13 19:05:09.748355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cf8300ba6a'
down_revision = 'c04c65aaecb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cma_task', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cma_task', 'total')
    # ### end Alembic commands ###
