"""add case_id attributes to case_property, case_client tables

Revision ID: f633a321c2e6
Revises: da40ae42f365
Create Date: 2020-05-26 00:58:43.579497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f633a321c2e6'
down_revision = 'da40ae42f365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('case_id', sa.String(), nullable=True))
    op.create_unique_constraint('uc_case_client_case_id', 'case_client', ['case_id'])
    op.add_column('case_property', sa.Column('case_id', sa.String(), nullable=True))
    op.create_unique_constraint('uc_case_property_case_id', 'case_property', ['case_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_case_property_case_id', 'case_property', type_='unique')
    op.drop_column('case_property', 'case_id')
    op.drop_constraint('uc_case_client_case_id', 'case_client', type_='unique')
    op.drop_column('case_client', 'case_id')
    # ### end Alembic commands ###
