"""nassau assessment year shift

Revision ID: f6df22f5619e
Revises: 76d098bb1921
Create Date: 2020-03-05 18:17:02.862285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6df22f5619e'
down_revision = '76d098bb1921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('''
    update ratios set value = 0.0010000 where year = 2018 and ratios_settings_id = 10;
    update ratios set value = 0.0014000 where year = 2019 and ratios_settings_id = 10;
    
    
    update assessment_dates set assessment_year = 2019 where county='suffolk';
    update assessment_dates set assessment_year = 2018 where assessment_year = 2019 and county='nassau';
    update assessment_dates set assessment_year = 2019 where assessment_year = 2020 and county='nassau';
    
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
