"""add email note sender

Revision ID: f7e1631559f4
Revises: a0157d1640be
Create Date: 2020-07-27 01:48:32.837046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e1631559f4'
down_revision = 'a0157d1640be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_sender (id, name) VALUES (4, 'Case Email');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_sender WHERE id = 4;
        '''
    )
    # ### end Alembic commands ###
