"""remove signature constraint

Revision ID: f7e6ced8768a
Revises: 536a612e381b
Create Date: 2020-07-06 18:17:37.413999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7e6ced8768a'
down_revision = '536a612e381b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'signature_base64_encoded',
                    existing_type=postgresql.BYTEA(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_application', 'signature_base64_encoded',
                    existing_type=postgresql.BYTEA(),
                    nullable=False)
    # ### end Alembic commands ###
