"""assessment ratios level column

Revision ID: f88d20bc7dc0
Revises: 8e3568fe768f
Create Date: 2019-12-19 18:16:02.393339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88d20bc7dc0'
down_revision = '8e3568fe768f'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('assessment_ratio', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_ratio', 'level')
