"""new mailing requirements

Revision ID: f92b6df05f46
Revises: 6fcdc945e755
Create Date: 2020-05-18 20:34:42.852789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92b6df05f46'
down_revision = '6fcdc945e755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('mailing_city', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_line1', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_line2', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_line3', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_state', sa.String(), nullable=True))
    op.add_column('case_application', sa.Column('mailing_zip', sa.Integer(), nullable=True))
    op.drop_column('case_application', 'mailing_address')
    op.add_column('case_client', sa.Column('mailing_city', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_line1', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_line2', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_line3', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_state', sa.String(), nullable=True))
    op.add_column('case_client', sa.Column('mailing_zip', sa.Integer(), nullable=True))
    op.drop_column('case_client', 'mailing_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_client', sa.Column('mailing_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_client', 'mailing_zip')
    op.drop_column('case_client', 'mailing_state')
    op.drop_column('case_client', 'mailing_line3')
    op.drop_column('case_client', 'mailing_line2')
    op.drop_column('case_client', 'mailing_line1')
    op.drop_column('case_client', 'mailing_city')
    op.add_column('case_application', sa.Column('mailing_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('case_application', 'mailing_zip')
    op.drop_column('case_application', 'mailing_state')
    op.drop_column('case_application', 'mailing_line3')
    op.drop_column('case_application', 'mailing_line2')
    op.drop_column('case_application', 'mailing_line1')
    op.drop_column('case_application', 'mailing_city')
    # ### end Alembic commands ###
