"""add application type translations in case_application_type table

Revision ID: f9eee4f9b0e7
Revises: d05bf453fa81
Create Date: 2020-06-29 23:11:35.347305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eee4f9b0e7'
down_revision = 'd05bf453fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application_type
        SET description = 'Misspelled In County Records'
        WHERE id=4;
        
        UPDATE case_application_type
        SET description = 'Co Owner'
        WHERE id=5;

        UPDATE case_application_type
        SET description = 'Authorized Signor'
        WHERE id=6;
        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
