"""add reviewed system note type

Revision ID: fa1c31470bcd
Revises: 743417ab69f2
Create Date: 2020-07-23 17:36:55.796857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1c31470bcd'
down_revision = '743417ab69f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_note_type (id, name, action) VALUES (6, 'System', 'reviewed')
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_note_type WHERE id=6;
        '''
    )
    # ### end Alembic commands ###
