"""OwnerType to ApplicationType

Revision ID: fad191763141
Revises: 5cb21306cc9e
Create Date: 2020-05-21 15:44:23.846199

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fad191763141'
down_revision = '5cb21306cc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('case_application', sa.Column('application_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_CaseApplication_case_owner_type_id', 'case_application', type_='foreignkey')
    op.create_foreign_key('fk_case_application_type_id', 'case_application', 'case_application_type',
                          ['application_type_id'], ['id'])
    op.drop_column('case_application', 'owner_type_id')
    op.execute(
        '''
        INSERT INTO case_application_type (id, description, name) VALUES (1, 'New Home Owner', 'new_home_owner');
        INSERT INTO case_application_type (id, description, name) VALUES (2, 'Standard', 'standard');
        '''
    )
    op.drop_table('case_owner_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('owner_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_case_application_type_id', 'case_application', type_='foreignkey')
    op.drop_column('case_application', 'application_type_id')
    op.create_table('case_owner_type',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='case_owner_type_pkey')
                    )
    op.create_foreign_key('fk_CaseApplication_case_owner_type_id', 'case_application', 'case_owner_type',
                          ['owner_type_id'], ['id'])
    op.execute(
        '''
        INSERT INTO case_owner_type (id, description, name) VALUES (1, 'New Home Owner', 'new_home_owner');
        INSERT INTO case_owner_type (id, description, name) VALUES (2, 'Standard', 'standard');
        '''
    )

    op.drop_table('case_application_type')
    # ### end Alembic commands ###
