"""set billing defaults

Revision ID: fb3c1aa60682
Revises: b55d157b5578
Create Date: 2020-07-23 12:01:04.370153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3c1aa60682'
down_revision = 'b55d157b5578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        update case_billing
        set attorney_fee = 0
        where attorney_fee is null;

        update case_billing
        set late_fee = 0
        where late_fee is null;

        update case_billing
        set balance = 0
        where balance is null;       
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
