"""add partially paid payment status

Revision ID: fb6e60471d73
Revises: 3ace7b676472
Create Date: 2020-07-25 00:10:05.553822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6e60471d73'
down_revision = '3ace7b676472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_payment_status (id, name, description) VALUES (3, 'partially paid', 'Partially Paid');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_payment_status WHERE id = 3;
        '''
    )
    # ### end Alembic commands ###
