"""add original_application to application table

Revision ID: fc38be0342e2
Revises: 9da883abb410
Create Date: 2020-07-24 21:54:29.086707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc38be0342e2'
down_revision = '9da883abb410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_application', sa.Column('original_application', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_application', 'original_application')
    # ### end Alembic commands ###
