"""set default payment status

Revision ID: fd09c0831f03
Revises: 2b3517aa15cc
Create Date: 2020-08-01 16:13:49.226361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd09c0831f03'
down_revision = '2b3517aa15cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE ONLY case_application ALTER COLUMN payment_status_id SET DEFAULT 1;
        ALTER TABLE ONLY case_property ALTER COLUMN payment_status_id SET DEFAULT 1;
        '''
    )

    op.execute(
        '''
        UPDATE case_application SET payment_status_id = 1 WHERE payment_status_id IS NULL;
        UPDATE case_property SET payment_status_id = 1 WHERE payment_status_id IS NULL;
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
