"""fix address_state in case_application table

Revision ID: fd8a3f2ff4fb
Revises: 2bcf8d217c31
Create Date: 2020-06-29 13:11:06.548193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8a3f2ff4fb'
down_revision = '2bcf8d217c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE case_application
        SET address_state = 'FL'
        WHERE address_state = 'FLORIDA';        
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
