"""add Re-mail 2020-09 marketing code

Revision ID: fda8f2a92f1a
Revises: 888b250bde90
Create Date: 2020-08-31 22:51:32.375284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda8f2a92f1a'
down_revision = '888b250bde90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO case_marketing_code (id, name) VALUES (7, 'Re-mail 2020-09');
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE FROM case_marketing_code WHERE id='7';
        '''
    )
    # ### end Alembic commands ###
