"""sale proeprty index

Revision ID: fe0b2e7ed476
Revises: 68a046d2aae1
Create Date: 2020-05-11 20:06:33.469752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0b2e7ed476'
down_revision = '68a046d2aae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sale_property_id'), 'sale', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_property_id'), table_name='sale')
