"""abstract property creation

Revision ID: ff7a23c97fa9
Revises: 2dbcc5f775af
Create Date: 2020-03-26 16:22:40.352805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff7a23c97fa9'
down_revision = '2dbcc5f775af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_overridden',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('apn', sa.String(), nullable=False),
                    sa.Column('county', sa.String(), nullable=False),
                    sa.Column('school_district', sa.Integer(), nullable=True),
                    sa.Column('section', sa.String(), nullable=True),
                    sa.Column('block', sa.String(), nullable=True),
                    sa.Column('undefined_field', sa.String(), nullable=True),
                    sa.Column('print_key', sa.String(), nullable=True),
                    sa.Column('lot', sa.String(), nullable=True),
                    sa.Column('village', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('street', sa.String(), nullable=True),
                    sa.Column('number', sa.String(), nullable=True),
                    sa.Column('town', sa.String(), nullable=False),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('zip', sa.Integer(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('coordinate_x', sa.Float(), nullable=True),
                    sa.Column('coordinate_y', sa.Float(), nullable=True),
                    sa.Column('is_condo', sa.Boolean(), nullable=True),
                    sa.Column('is_listed', sa.Boolean(), nullable=True),
                    sa.Column('property_class', sa.Integer(), nullable=True),
                    sa.Column('building_code', sa.Integer(), nullable=True),
                    sa.Column('data_composite', sa.ARRAY(sa.Integer()), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('hamlet', sa.String(), nullable=True),
                    sa.Column('gla_sqft', sa.Float(), nullable=True),
                    sa.Column('waterfront', sa.Boolean(), nullable=True),
                    sa.Column('rooms', sa.Integer(), nullable=True),
                    sa.Column('kitchens', sa.Integer(), nullable=True),
                    sa.Column('full_baths', sa.Integer(), nullable=True),
                    sa.Column('half_baths', sa.Integer(), nullable=True),
                    sa.Column('bedrooms', sa.Integer(), nullable=True),
                    sa.Column('fireplaces', sa.Integer(), nullable=True),
                    sa.Column('property_style', sa.String(), nullable=True),
                    sa.Column('garages', sa.Integer(), nullable=True),
                    sa.Column('garage_type', sa.Integer(), nullable=True),
                    sa.Column('basement_type', sa.Integer(), nullable=True),
                    sa.Column('heat_type', sa.String(), nullable=True),
                    sa.Column('gas', sa.Boolean(), nullable=True),
                    sa.Column('patio_type', sa.Integer(), nullable=True),
                    sa.Column('porch_type', sa.Integer(), nullable=True),
                    sa.Column('sewer_type', sa.Integer(), nullable=True),
                    sa.Column('water_type', sa.Integer(), nullable=True),
                    sa.Column('pool', sa.Boolean(), nullable=True),
                    sa.Column('price_per_sqft', sa.Float(), nullable=True),
                    sa.Column('lot_size', sa.Float(), nullable=True),
                    sa.Column('location', sa.Integer(), nullable=True),
                    sa.Column('condition', sa.String(), nullable=True),
                    sa.Column('story_height', sa.Float(), nullable=True),
                    sa.Column('paving_type', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_property_overridden_apn'), 'property_overridden', ['apn'], unique=False)
    op.create_index(op.f('ix_property_overridden_county'), 'property_overridden', ['county'], unique=False)
    op.create_index(op.f('ix_property_overridden_print_key'), 'property_overridden', ['print_key'], unique=False)
    op.create_index(op.f('ix_property_overridden_undefined_field'), 'property_overridden', ['undefined_field'],
                    unique=False)
    op.drop_table('property_inventories_override')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_inventories_override',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('property_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('gla_sqft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=True),
                    sa.Column('lot_size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=True),
                    sa.Column('full_baths', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('half_baths', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('bedrooms', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('patio_type', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('porch_type', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('pool', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('paving_type', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('garages', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('basement_type', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('heat_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['property_id'], ['property.id'],
                                            name='property_inventories_override_property_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='property_inventories_override_pkey')
                    )
    op.drop_index(op.f('ix_property_overridden_undefined_field'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_print_key'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_county'), table_name='property_overridden')
    op.drop_index(op.f('ix_property_overridden_apn'), table_name='property_overridden')
    op.drop_table('property_overridden')
    # ### end Alembic commands ###
